### ISSUE TITLE
Generating IDs from M3Coordinator should be made invertible

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1001]
Currently generating IDs from tags in M3Coordinator does no escaping, which means that in theory, multiple different groups of tags can map to the same ID if they contain the characters "=" or ";" within their tag names / values.

We should change how we generate IDs from tags such that every ID can only be generated from a single unique set of tags

**Comment by richardartoul** [comment]
@arnikola can we close this

**Comment by arnikola** [comment]
Yeah, sounds good. Closing
