### ISSUE TITLE
Race in topology retrieval during bootstrap between CommitLog and DB

### ISSUE THREAD

**Issue by prateek** [m3db/m3#1011]
During the bootstrap process, we rely on the [Client's topology view](https://github.com/m3db/m3/blob/2c2f509ed217f1b0dec7f289626ee264606a8351/src/dbnode/storage/bootstrap/process.go#L108-L125) to make decisions about the shards to boostrap. This is racy because it can have received an update before the corresponding update on the storage.Database end. 

We should instead rely on the Database's topology view to make consistent decisions about the shards to bootstrap.

**Comment by richardartoul** [comment]
Discussed with @robskillington , thanks for finding this issue for me. Will fix it today
