### ISSUE TITLE
M3Agg placements should store a MaxAggregationWindowSize and WarmupDuration

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1031]
The logic for making placement changes for the M3Agg service require knowledge of two variables:

1. The maximum possible aggregation window size
2. The duration of the warmup period (how long we expect the placement to take to propagate to all clients)

It would be better if these values were stored with the placement itself instead of having to be provided everytime.

**Comment by cw9** [comment]
Could we use default value when starting up the placement service? 
The maximum aggregation window size should equal to the largest resolution among the supported m3db namespaces.
The duration of the warmup period could default to zero, only advanced users need to tune it.

**Comment by richardartoul** [comment]
Spoke offline, but we can't actually use M3DB namespaces because they have no concept of resolution. Will leave this alone for now, but maybe we can add something analogous to the concept of namespaces, but for M3Agg later
