### ISSUE TITLE
Coordinator: unused codepath

### ISSUE THREAD

**Issue by arnikola** [m3db/m3#1037]
Coordinator/Query: The code in `policy/resolver/PolicyResolver` is no longer in use; look into if we still need it, and prune it and associated codepaths if it's no longer required.

**Comment by arnikola** [comment]
`Matcher.Matches()` seems to also be unused outside of test functions

**Comment by andrewmains12** [comment]
Looking into this a bit, it seems like the `PolicyResolver` functionality is covered by a method on `m3storage`:

```
// resolveClusterNamespacesForQuery returns the namespaces that need to be
// fanned out to depending on the query time and the namespaces configured.
func (s *m3storage) resolveClusterNamespacesForQuery(
	start time.Time,
	end time.Time,
) (queryFanoutType, ClusterNamespaces, error) {
	now := s.nowFn()
```
Even if it weren't, it looks like we just have the one implementation, which would be pretty trivial to bring back, so I think we should be good to nix this.

**Comment by arnikola** [comment]
Removed this a while ago, resolving issue :+1:
