### ISSUE TITLE
Investigate flaky test `TestShardTickWriteRace`

### ISSUE THREAD

**Issue by arnikola** [m3db/m3#1056]
Works fine in general, but have been noticing it failing on CI oftenish; tried to get a few repros for it but nothing definitive as of yet. 

Including logs for CI failure:
[ShardTick.log](https://github.com/m3db/m3/files/2462396/ShardTick.log)

**Comment by prateek** [comment]
@arnikola cheers, yeah this has been on the backlog for a while now. First observed way back in https://github.com/m3db/m3/pull/506. I'll take a look this week.

**Comment by arnikola** [comment]
Ah no worries, less of a problem now that rerunning tests is so much faster, was just putting up an issue so we can track it a bit better :)

**Comment by arnikola** [comment]
Also, liking `println(fmt.Sprintf("god this is terrible"))` 😛

**Comment by arnikola** [comment]
Resolved a while ago
