### ISSUE TITLE
`persist fs index bootstrap failed` when adding a node to placement

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#1098]
I added a new node to my placement today, and it looks like it peer bootstrapped all the blocks, but is failing to bootstrap the index with the error message `persist fs index bootstrap failed [{violation invariant_violated}` and is trying again roughly every 30 minutes.

relevant portion of the logs attached.

[persist_failed.txt](https://github.com/m3db/m3/files/2484890/persist_failed.txt)

My block duration is 2h, and my index duration is 12h, so I'm hoping it'll clear up as we hit the end of the index in about 3 hours.

**Comment by richardartoul** [comment]
@BertHartm Thanks for the logs and details, this looks similar to the issue we helped you debug over gitter. We'll get back to you soon about this.

**Comment by BertHartm** [comment]
Dupe of #1039
