### ISSUE TITLE
Flaky test: TestStaleDelete__FromWatch

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1099]
```
Error Trace:	store_test.go:894
--
  | Error:		Should be true
  | Messages:	timed out waiting for client to read values from cache
```

**Comment by prateek** [comment]
@cw9 had bumped timeout to fix this recently. @richardartoul Have you seen this in the last few days?

**Comment by prateek** [comment]
Haven't seen this in the past 4 days. Feel free to reopen if this pops up.
