### ISSUE TITLE
Add guards in code/docs recommending against RF=2

### ISSUE THREAD

**Issue by prateek** [m3db/m3#1107]
RF=2 is a weird deployment we don't really recommend people use. It doesn't buy *enough* reliability (e.g. still need downtime when doing any maintenance - including simple reboots) and introduces lots of failure modes (e.g. can't peer bootstrapping with consistency majority). 

We should disallow users from creating such topologies (at the placement/cluster endpoints, allowing them to override if they know what they're doing.). Similarly, we should document this in our docs explicitly (including other knobs to configure if they do override to RF=2)

**Comment by richardartoul** [comment]
@prateek We already have a "force" variable in our placement APIs so would be easy to make it reject RF2 if that flag is not passed

**Comment by schallert** [comment]
Was going to create an issue about running with RF < 3 and noticed this (github "similar issues" ftw). Just bumping this as a reminder to us to try to at least write something up about the dangers of RF=1 and RF=2. Will try to write some docs for this if I have time, as users of the operator have run into this.

**Comment by schallert** [comment]
I address this somewhat in #1588
