### ISSUE TITLE
Feature Request: Warn on Placement Host ID Mismatch

### ISSUE THREAD

**Issue by jacob-scheatzle** [m3db/m3#1123]
Situation: Placement IDs don't match Host IDs in cluster, nodes will accept placement but initialization will never happen

Requested Behavior: A warning to indicate the placement host IDs do not match the cluster IDs or is not in the cluster.

**Comment by richardartoul** [comment]
To make this more concrete, I think the ask here is to make it such that when a node receives a new placement, it checks if it is in the placement, and if not, emits a warning message.

**Comment by jacob-scheatzle** [comment]
> To make this more concrete, I think the ask here is to make it such that when a node receives a new placement, it checks if it is in the placement, and if not, emits a warning message.

I do like how that sounds, but more specifically I was looking at having a warning message if there are no Host IDs in the cluster matching the IDs called out in the new placement.
