### ISSUE TITLE
m3query prom read (query_range) doesn't set CORS on error, causing grafana retry loops

### ISSUE THREAD

**Issue by andrewmains12** [m3db/m3#1135]
Grafana requires CORS headers on HTTP responses in order to function properly. For the `/api/v1/query_range` endpoint (and probably others), we set these in the success path, but not the failure path. This causes an error in grafana, and makes it keep retrying the request, even on 400's.

Console logs show:

```
GET http://localhost:7201/api/v1/query_range?query=topk(5%2C%20process_virtual_memory_bytes&start=1540498740&end=1540500570&step=30 400 (Bad Request)
 No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Adding the header in all code paths causes the request to fail fast, with an appropriate message displayed in the inspector, as expected. 

m3query should ensure that cors headers are always set.

Steps to reproduce:

1. Open dev console in Chrome.
2. Create a grafana panel with a syntactically incorrect promql expression: `topk(5, process_virtual_memory_bytes`
3. Note that the loading indicator sticks around.
4. Note the retries in the network tab.

**Comment by robskillington** [comment]
Re: pulling in dependencies, that's fine as long as the license is permissive (MIT, Apache, BSD, etc)

**Comment by andrewmains12** [comment]
@robskillington cool thanks for the guidance; I'll check out one of the libs and throw it in in that case.
