### ISSUE TITLE
About loadblance for m3cordition.

### ISSUE THREAD

**Issue by tannh** [m3db/m3#1137]
I would like to develop a reverse proxy to set up loadbalance for multi m3cordition, would that be possible?

**Comment by prateek** [comment]
Hey @tannh! 

I’m unclear what problem you’re trying to solve with the revproxy. There’s a little bit of nuance so bear with me. Consider the following:

m3coordinator can run in a few modes, controlled by configuration. 
(A) It can be embedded in a single process along with the dbnode code. This is what you’d do to spin up a single process cluster to get your feet wet but you’d never use it for a deployment where you need HA. 
(B) As a stateless sidecar for Prometheus remote read/write APIs. i.e. running a coordinator instance on the same host as Prometheus instance and all it does is forward traffic both ingress and egress requests to m3db cluster(s) running on other hosts. 
(C) similar to (B), but also serving to downsample/aggregate incoming write requests before forwarding them to m3db cluster(s)

- What mode are you shooting towards?

- Further, mind sketching out what your deployment with a rebproxy would like? Just a quick 1-2 lines about what processes are running on what hosts and how they talk to each other. Processes would include: Prometheus, m3coordinator, m3dbnode and the new proxy
