### ISSUE TITLE
Consider using [easyjson](https://github.com/mailru/easyjson) for query API JSON serialization

### ISSUE THREAD

**Issue by andrewmains12** [m3db/m3#1144]
We should consider using [easyjson](https://github.com/mailru/easyjson) or similar for this, to avoid handwriting a bunch of boilerplate.

I've used easyjson in the past without difficulty, and iirc it gave us good performance (definitely compared to reflection based `encoding/json`).

**Comment by eahydra** [comment]
Personally recommended github.com/json-iterator/go, A high-performance 100% compatible drop-in replacement of "encoding/json"

**Comment by andrewmains12** [comment]
Thanks a lot for the suggestion @eahydra -- that looks quite promising (and I love that it doesn't require codegen like `easyjson`). I'll take a pass at integrating that when I get a chance (and of course feel free to make a PR if you feel like doing it!).

**Comment by richardartoul** [comment]
I wrote [this benchmark](https://github.com/m3db/m3/pull/1003/files#diff-2be767d16b43e2d70eb4a1cbc423eebbR239) last time I was doing performance work around this so maybe we could use that with some modification as a litmus test for the libraries
