### ISSUE TITLE
Add documentation on Granafa setup

### ISSUE THREAD

**Issue by fire** [m3db/m3#1147]
Can you provide an end to end example that emits to grafana?

It should be possible to use an existing kube wordpress setup.

**Comment by andrewmains12** [comment]
Hey @fire , good question. Want to try https://github.com/m3db/m3/tree/master/scripts/development/m3_stack ? It sets up a dashboard which gets populated by internal M3DB metrics (more info in the README there). If that works out for you, we can link this a bit more prominently in our docs.

**Comment by fire** [comment]
Ping me if you've got something I can try.

**Comment by fire** [comment]
https://gist.github.com/fire/41857b55dee7b220022edb903961b088

This is using the kubernetes setup instructions.

**Comment by fire** [comment]
@andrewmains12 What do you require?

**Comment by richardartoul** [comment]
We have docs on this now: http://m3db.github.io/m3/integrations/grafana/
