### ISSUE TITLE
Add CI target for doc spell check

### ISSUE THREAD

**Issue by fire** [m3db/m3#1149]
https://github.com/m3db/m3#test-it-out

Test it out
(For a fully comprehsensive getting started guide, see our single node how-to).

comprehsensive -> comprehensive.

**Comment by prateek** [comment]
@fire cheers, thanks for all these catches. 

We need to wire up something automated to catch this form of failure, https://github.com/ai/yaspeller-ci is the best I can find.

**Comment by ChrisChinchilla** [comment]
I will add a spell checker as well as a general linter soon, it's already in progress, so will close this for now.
