### ISSUE TITLE
problem with 10 Millions metric every 5 minutes

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [m3db/m3#1158]
Hello guys
I am impressed with this product and try to run it on environment that generate 10-11 millions metrics every 5 minutes. And i got problem that database is too huge almost 65GB for 1h of running, and it consume all memory 192 GB and goes down with OOM. Can you give advise what settings i need to use and if its really can handle that number of metrics? 
i try to run one server configuration with disabled cache, its all changes that i do.

**Comment by richardartoul** [comment]
Hey Dimitry,

That does sound like a lot of data. I need a little more information before I can help you sort this out.

1. Please post your placement config (I.E how many hosts are you running and what replication factor)
2. Please post your namespace config (Blocksize, retention, etc)
3. When you say 10-11 million metrics and every 5 minutes, what does that mean? Does that mean you have 10-11 million unique series that each receive a single datapoint every 5 minutes (cardinality of 10-11 million) or do you mean that over a 5 minute period 10-11 million datapoints are emitted, but for less than 10 million series? What is your approximate cardinality and QPS?
4. When you say the database is too huge, what files are you referring to? Is it the data directory, the snapshots directory, or the commitlogs directory? Could you `ls -ltrh` the various m3db storage directories so we can say whats using so much space?

Also I don't think disabling the cache will help you here. The issue you're probably having is that the working set is too large.

**Comment by dmitriy-lukyanchikov** [comment]
Hello.

1) there is no placement config, its just one big server, 192 GB of memory, i wanted to test before run cluster
2) Its all defaults, maybe you can help with configuration
3) i mean 11 millions uniq series every 5 minutes
4) the server goes OOM before creating blocks so i have near 80GB of commitlogs for almost 1 hour of running

Maybe you can help with configuring or how to test this db for 11 millions of uniq series with one server or small cluster

**Comment by richardartoul** [comment]
@dmitriy-lukyanchikov 11 million NEW unique series every 5 minutes or the same 11 million series every 5 minutes?

Do you have snapshotting disabled? What do you mean everything is defaults? What CURLs did you use to initialize everything?

**Comment by dmitriy-lukyanchikov** [comment]
Hello, every 5 minutes there 11 millions series with the different values, not sure if i can call it uniq or not.
I use this guide to initialize database https://m3db.github.io/m3/how_to/single_node/
So the curl was 
```
curl -X POST http://localhost:7201/api/v1/database/create -d '{
  "type": "local",
  "namespaceName": "default",
  "retentionTime": "48h"
}'
``` 

AS far as i remember by default snapshotting was disabled in my case

**Comment by richardartoul** [comment]
@dmitriy-lukyanchikov I guess what I'm saying is every 5 minutes do you get 11 million new series (I.E completely novel tags that have never seen before) or  do you get 11 million new datapoints for existing series?

You'll need to enable snapshotting otherwise it will use far too much disk space. My guess is that the memory issues you're running into are just that you have far too many series. Are you only running 1 node? You may need several different nodes to handle that many unique series

**Comment by dmitriy-lukyanchikov** [comment]
Yes the series is the same but datapoints is new. 
And yes i run only one node for testing, comparing to prometheus that can handle the same number of metrics with no problem using 10 times smaller space size and need only 64 GB of RAM. Can you describe what option i can use to configure checkpoint and tune settings for infrastructure with 11 millions metrics?

**Comment by richardartoul** [comment]
hmm it really shouldn't be using much more memory than prometheus is using. I wonder if you're accidentally creating new series unintentionally.

If you want 48 hours of retention, then I would try a block size of 2 hours and make sure snapshotting is enabled otherwise it will use a lot of disk space.

Do you want to jump in our gitter? Will probably be faster to debug it this way: https://gitter.im/m3db/Lobby

**Comment by dmitriy-lukyanchikov** [comment]
actually i need 3 years retention )), i need to store all this metrics 3 years with downsampling if it possible, but for testing i can run any of configuration.

Can you help with instruction how i can run testing infrastructure or this number of metrics, what config i need to use and what servers?

**Comment by richardartoul** [comment]
yeah this might be a longer discussion though, do you mind joining our gitter?

**Comment by richardartoul** [comment]
@dmitriy-lukyanchikov Let me know if you want to continue our discussion. I'm happy to help but I need a lot more information to help you and I don't think a Github issue is the correct format.

**Comment by richardartoul** [comment]
Closing as stale
