### ISSUE TITLE
api: expose error if instance was not added to placement

### ISSUE THREAD

**Issue by schallert** [m3db/m3#1167]
https://github.com/m3db/m3/blob/5728975a6fcba5a9ad5f629d9fa7ce88b266f2fa/src/query/api/v1/handler/placement/add.go#L151

In our current placement add logic, we don't check whether the desired instance was actually added to the placement. Based on unit tests it seems like one could attempt to add 1 aggregator instance (which isn't valid since they need to be added in pairs), and the handler will just return the existing placement.

We should validate this behavior.

**Comment by cw9** [comment]
Can you link the test here? If it's the rf is just 1 in the aggregator placement, the algo can just add one instance to it
