### ISSUE TITLE
Create a "debug" endpoint in our services

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1173]
Ideally this endpoint would provide the following information:

1. Write QPS / Series cardinality and other relevant metrics (when applicable)
2. YAML / Namespace / Placement configuration
3. Process/Host information (Num Cores, Memory, etc)
4. Scrape prometheus endpoint (if available)
5. CPU / Heap Profiles (optionally) 
6. Anything else that might be useful for debugging / troubleshooting.

**Comment by lyuboraykov** [comment]
I've started working on it, I'll have it create a zip file with all the data and stream it back in the response.

**Comment by lyuboraykov** [comment]
#1269
