### ISSUE TITLE
Add guide for wiring up external etcd

### ISSUE THREAD

**Issue by prateek** [m3db/m3#1181]
Our current examples all use the embedded etcd cluster, we should add a page to explain how to setup the stack with an external etcd cluster too.

**Comment by huangll** [comment]
good

**Comment by maozi07** [comment]
Hi，I'm using an external etcd cluster for setup，but it can't get up when Initialize Topology.The error show as below:
dbnode:
`2019-02-22T15:12:23.858+0800    ERROR   unable to initialize placement  {"rqID": "d487bcfc-fc8b-4d83-94a8-af0ebe4b7960", "error": "no etcd cluster found for zone embedded"}`

curl cmd:
`{"error":"no etcd cluster found for zone embedded"}`

**Comment by richardartoul** [comment]
Matt took care of this: http://m3db.github.io/m3/operational_guide/etcd/

**Comment by maozi07** [comment]
I've followed the doc.Can m3db create the meatinfo(zone) automatic in etcd or should I create it by myself
