### ISSUE TITLE
Queries over long time ranges balloon index usage

### ISSUE THREAD

**Issue by robskillington** [m3db/m3#1192]
Reported by Yoram Hekma @yhekma

Queries over a long range that return a significant number of IDs (just a single time series seems to be fine) greatly balloon the memory usage of an M3DB usage.

Query (over 14 day range):
```
sum(rate(nginx_http_requests_total{host="$service"}[1m]))
```

Estimate of number of time series being returned:
```
3196
```

Setup:
```
2 namespaces, 1 unaggregated with 96h retention and blocksize of 4h, and one aggregated with 336h retention and blocksize of 24h
```

Memory usage ballooning:
<img width="1389" alt="m3db_memory_usage" src="https://user-images.githubusercontent.com/339615/48850533-e9d87100-ed76-11e8-9357-974a57610483.png">

Heap profile flamegraph shows 16gb consumed in `alloc_space` for QueryIDs:
![screen shot 2018-11-21 at 10 22 38 am](https://user-images.githubusercontent.com/339615/48850842-84d14b00-ed77-11e8-988b-7f97d8a2907a.png)

Heap profile:
https://www.dropbox.com/s/viiy934bp67zix8/heap.prof?dl=0

**Comment by favoretti** [comment]
I'll be listening in on this, as @yhekma and myself are on the same team. Thanks for looking into this folks!

**Comment by richardartoul** [comment]
@favoretti @yhekma

We just tested an index performance improvement that resolves this issue and saw order of magnitude improvements, so we will have a fix for this soon.

We need to contribute code to one of our dependencies (you can follow along in [this issue](https://github.com/pilosa/pilosa/issues/1765) if you like) so it may take a week or two, but this will be resolved soon.

**Comment by yhekma** [comment]
Awesome! Thanks bunches!

**Comment by yhekma** [comment]
@richardartoul great! I'll test it out tomorrow and will let you know. Thanks again

**Comment by yhekma** [comment]
@richardartoul wow, that make a *BIG* difference! I think this means this issue can be closed

**Comment by richardartoul** [comment]
@yhekma Great! @robskillington Has some more very large index performance improvements coming soon so stay tuned.
