### ISSUE TITLE
Scope out work for building M3DB with go1.12

### ISSUE THREAD

**Issue by schallert** [m3db/m3#1193]
We currently build m3db with go1.10, which was release in February 2018. We should scope out the work involved to build m3db with go1.11.

**Comment by richardartoul** [comment]
@schallert I'd like to get us on go1.11 too cause they've improved some of the runtime profiling. Is anything stopping us? We can probably start by modifying C.I to build with Go1.11 for a branch and see what happens.

**Comment by schallert** [comment]
@richardartoul I don't know of anything specifically that'd block us, but I wouldn't be surprised if there's a subtle change or 2 that'd affect us like there have been in the past.

In terms of testing on CI, #1194 just landed which lets you change the version of Go we build with in [YAML config](https://github.com/m3db/m3/blob/531ed7020675ed71f223acc2a47cd60c52d006e0/docker-compose.yml#L2) rather than pushing a new CI base image. We can just bump that on a branch and start testing things out.

**Comment by richardartoul** [comment]
Update this to be for go1.12

**Comment by schallert** [comment]
Build failures from a 1.12 upgrade if anyone's interested: https://buildkite.com/uberopensource/m3-monorepo-ci/builds/544
