### ISSUE TITLE
Nodes can run out of disk space when joining the cluster

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1231]
## Problem

Currently if a node is attempting to join the cluster, it will immediately begin accepting writes (but not reads) for the shards it is acquiring, and at the same time it will peer bootstrap the historical data it is missing from its peers.

During this bootstrapping process, neither flushing nor snapshotting can occur. As a result, all of the commitlogs that are created during the node join process must be retained until the node finishes joining.

In clusters that are heavily loaded such that the nodes don't have a lot of disk space available, even with snapshotting enabled, this can lead to situations where nodes are unable to join the cluster because the commitlogs will fill up the disk before the node can finish joining.

This leads to a situation where operations have to manually intervene and periodically delete commitlogs on the joining node until the process is complete.

## Proposal

Disable writing to the commitlog for any node who has 0 shards in the `available` or `leaving` state I.E all their shards are in the `initializing` state AND is bootstrapping. This is valid because according to our consistency model and once #1183 lands, the expectation is that a node need not have all data for a given shard persisted durably UNTIL it marks that shard as available. 

As a result, what we could do is simply disable the commitlog while all shards are marked as `initializing` and the node is bootstrapping. Once bootstrapping completes, we can reactivate the commitlog before the post-bootstrap snapshot begins. Then once that snapshot begins, the shards will be marked as available (as implemented in #1183) and the M3DB node will meet all of its durability guarantees because all the data that was not captured in the commitlog during the node join / bootstrapping is captured in the snapshot and the node will behave "normally" moving forward.

This would resolve the disk space during node join issue, and have the added benefit of probably increasing the speed at which we can do node joins as node joins are currently bottlenecked by disk throughput (which we artificially constrain to limit competition for IO with the commitlog)

**Comment by richardartoul** [comment]
As an additional datapoint, if we could not throttle FS writes during node joins, my experimentation in our production clusters shows that we could effectively half the amount of time it takes to do a node join.

**Comment by mway** [comment]
@richardartoul where are we on this, have we discussed further? any reason not to move forward?
