### ISSUE TITLE
could not create etcd watch

### ISSUE THREAD

**Issue by Prasoon6667** [m3db/m3#1273]
I am trying to perform read/write services via Prometheus. I have set up the one node m3db cluster for testing and m3coordinator along with prometheus. 

I am getting the error in m3db

 2019/01/01 06:32:34 Go Runtime version: go1.10.7
2019/01/01 06:32:34 Build Version:      v0.4.8
2019/01/01 06:32:34 Build Revision:     8426dac7
2019/01/01 06:32:34 Build Branch:       HEAD
2019/01/01 06:32:34 Build Date:         2018-12-27-14:15:13
2019/01/01 06:32:34 Build TimeUnix:     1545920113
06:32:34.513508[I] resolving seed node configuration [{hostID i-00e8d79bf8236d2a0} {seedNodeHostIDs [i-00e8d79bf8236d2a0]}]
06:32:34.513543[I] seed node, starting etcd server
2019-01-01 06:32:34.551730 W | auth: simple token is not cryptographically signed
2019-01-01T06:32:34.552Z        INFO    resolved cluster namespace      {"namespace": "default"}
2019-01-01T06:32:34.556Z        INFO    no m3msg server configured
2019-01-01T06:32:34.557Z        INFO    starting server {"address": "0.0.0.0:7201"}
06:32:34.895753[W] max index query IDs concurrency was not set, falling back to default value
06:32:34.895928[W] host doesn't support HugeTLB, proceeding without it
06:32:34.965892[I] bytes pool registering bucket capacity=16, size=524288, refillLowWatermark=0.700000, refillHighWatermark=1.000000
06:32:34.965928[I] bytes pool registering bucket capacity=32, size=262144, refillLowWatermark=0.700000, refillHighWatermark=1.000000
06:32:34.965942[I] bytes pool registering bucket capacity=64, size=131072, refillLowWatermark=0.700000, refillHighWatermark=1.000000
06:32:34.965959[I] bytes pool registering bucket capacity=128, size=65536, refillLowWatermark=0.700000, refillHighWatermark=1.000000
06:32:34.965971[I] bytes pool registering bucket capacity=256, size=65536, refillLowWatermark=0.700000, refillHighWatermark=1.000000
06:32:34.965983[I] bytes pool registering bucket capacity=1440, size=16384, refillLowWatermark=0.700000, refillHighWatermark=1.000000
06:32:34.965995[I] bytes pool registering bucket capacity=4096, size=8192, refillLowWatermark=0.700000, refillHighWatermark=1.000000
06:32:34.966081[I] bytes pool simple init
06:32:36.463802[I] creating dynamic config service client with m3cluster
06:32:36.464280[W] could not load cache from file /var/lib/m3kv/_kv_default_env_m3db_embedded.json: error reading cache file /var/lib/m3kv/_kv_default_env_m3db_embedded.json: EOF
06:32:36.464316[I] waiting for dynamic topology initialization.
                If this takes a long time, make sure that a topology / placement is configured
06:32:36.464333[I] adding a watch for service: m3db env: default_env zone: embedded includeUnhealthy: true
06:32:36.464383[W] could not load cache from file /var/lib/m3kv/m3db_embedded.json: error opening cache file /var/lib/m3kv/m3db_embedded.json: open /var/lib/m3kv/m3db_embedded.json: no such file or directory
06:32:46.464658[E] could not create etcd watch: etcd watch create timed out after 10s for key: _sd.placement/default_env/m3db
06:34:30.907259[E] could not create etcd watch: etcd watch create timed out after 10s for key: _sd.placement/default_env/m3db
06:36:11.731868[E] could not create etcd watch: etcd watch create timed out after 10s for key: _sd.placement/default_env/m3db
06:37:55.200738[E] could not create etcd watch: etcd watch create timed out after 10s for key: _sd.placement/default_env/m3db
06:39:35.651628[E] could not create etcd watch: etcd watch create timed out after 10s for key: _sd.placement/default_env/m3db
06:41:20.551338[E] could not create etcd watch: etcd watch create timed out after 10s for key: _sd.placement/default_env/m3db
06:43:03.015497[E] could not create etcd watch: etcd watch create timed out after 10s for key: _sd.placement/default_env/m3db
06:44:46.891288[E] could not create etcd watch: etcd watch create timed out after 10s for key: _sd.placement/default_env/m3db

Below is the configuration I have used.

coordinator:
  listenAddress:
    type: "config"
    value: "0.0.0.0:7201"

  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
    sanitization: prometheus
    samplingRate: 1.0
    extended: none

db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  hostID:
    resolver: config
    value: <host-id from aws>

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority
    writeTimeout: 10s
    fetchTimeout: 15s
    connectTimeout: 20s
    writeRetry:
        initialBackoff: 500ms
        backoffFactor: 3
        maxRetries: 2
        jitter: true
    fetchRetry:
        initialBackoff: 500ms
        backoffFactor: 2
        maxRetries: 3
        jitter: true
    backgroundHealthCheckFailLimit: 4
    backgroundHealthCheckFailThrottleFactor: 0.5

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    bootstrappers:
        - filesystem
        - commitlog
        - peers
        - uninitialized_topology
    fs:
        numProcessorsPerCPU: 0.125

  cache:
    series:
      policy: lru

  commitlog:
    flushMaxBytes: 524288
    flushEvery: 1s
    queue:
        calculationType: fixed
        size: 2097152
    blockSize: 10m

  fs:
    filePathPrefix: /var/lib/m3db
    writeBufferSize: 65536
    dataReadBufferSize: 65536
    infoReadBufferSize: 128
    seekReadBufferSize: 4096
    throughputLimitMbps: 100.0
    throughputCheckEvery: 128

  repair:
    enabled: false
    interval: 2h
    offset: 30m
    jitter: 1h
    throttle: 2m
    checkInterval: 1m

  pooling:
    blockAllocSize: 16
    type: simple
    seriesPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    blockPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    encoderPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    closersPool:
        size: 104857
        lowWatermark: 0.7
        highWatermark: 1.0
    contextPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    segmentReaderPool:
        size: 16384
        lowWatermark: 0.7
        highWatermark: 1.0
    iteratorPool:
        size: 2048
        lowWatermark: 0.7
        highWatermark: 1.0
    fetchBlockMetadataResultsPool:
        size: 65536
        capacity: 32
        lowWatermark: 0.7
        highWatermark: 1.0
    fetchBlocksMetadataResultsPool:
        size: 32
        capacity: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    hostBlockMetadataSlicePool:
        size: 131072
        capacity: 3
        lowWatermark: 0.7
        highWatermark: 1.0
    blockMetadataPool:
        size: 65536
        lowWatermark: 0.7
        highWatermark: 1.0
    blockMetadataSlicePool:
        size: 65536
        capacity: 32
        lowWatermark: 0.7
        highWatermark: 1.0
    blocksMetadataPool:
        size: 65536
        lowWatermark: 0.7
        highWatermark: 1.0
    blocksMetadataSlicePool:
        size: 32
        capacity: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    identifierPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    bytesPool:
        buckets:
            - capacity: 16
              size: 524288
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 32
              size: 262144
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 64
              size: 131072
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 128
              size: 65536
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 256
              size: 65536
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 1440
              size: 16384
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 4096
              size: 8192
              lowWatermark: 0.7
              highWatermark: 1.0

  config:
      service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
              - zone: embedded
                endpoints:
                    - <ip>:2379
      seedNodes:
          initialCluster:
              - hostID: <my host id from AWS>
                endpoint: http://<ip>:2380

Placement configuration:

curl -X POST localhost:7201/api/v1/placement/init -d '{
    "num_shards": 1024,
    "replication_factor": 1,
    "instances": [
        {
            "id": "m3db001",
            "isolation_group": "us-east1-a",
            "zone": "embedded",
            "weight": 100,
            "endpoint": "<ip>:9000",
            "hostname": "m3db001",
            "port": 9000
        }]
}'

**Comment by maozi07** [comment]
Have the problem as your's

**Comment by maozi07** [comment]
I've solved this seednoes hostname must use the full hostname as the cmd `hostname -f`

**Comment by diemus** [comment]
i have the same problem did you solve it ?

**Comment by tianhao960** [comment]
have the same problem,

**Comment by m0rtez4** [comment]
I've fixed this issue by adding hostname to docker-compose file.
`version: '3.1'

services:
  m3db1:
    hostname: m3db1
    image: quay.io/m3db/m3dbnode:latest
    restart: unless-stopped
    volumes:
      - ./m3db_data_1:/var/lib/m3db
      - ./m3dbnode-local-etcd.yml:/etc/m3dbnode/m3dbnode.yml
    ulimits:
      nofile:
        soft: 3000000
        hard: 3000000
    ports:
      - 17201:7201
      - 17203:7203
      - 19003:9003
      - 12379:2379

  m3db2:
    hostname: m3db2
    image: quay.io/m3db/m3dbnode:latest
    restart: unless-stopped
    volumes:
      - ./m3db_data_2:/var/lib/m3db
      - ./m3dbnode-local-etcd.yml:/etc/m3dbnode/m3dbnode.yml
    ulimits:
      nofile:
        soft: 3000000
        hard: 3000000
    ports:
      - 27201:7201
      - 27203:7203
      - 29003:9003
      - 22379:2379


  m3db3:
    hostname: m3db3
    image: quay.io/m3db/m3dbnode:latest
    restart: unless-stopped
    volumes:
      - ./m3db_data_3:/var/lib/m3db
      - ./m3dbnode-local-etcd.yml:/etc/m3dbnode/m3dbnode.yml
    ulimits:
      nofile:
        soft: 3000000
        hard: 3000000
    ports:
      - 37201:7201
      - 37203:7203
      - 39003:9003
      - 32379:2379
                    `
