### ISSUE TITLE
Incorrect OpenAPI Endpoint Paths

### ISSUE THREAD

**Issue by swtch1** [m3db/m3#1274]
## General Issue

The OpenAPI documentation references an incorrect path for requests.  Removing `services/m3db/` from the path corrects the issue.

1. What service is experiencing the issue?
OpenAPI Documentation

2. What is the configuration of the service?
K8s installation using [kubernetes guide](https://m3db.github.io/m3/how_to/kubernetes/)

3. How are you using the service?
Early testing

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
- Install service on Kubernetes
- Expose service on port 7201
- execute GET on OpenAPI documented endpoint http://127.0.0.1:7201/api/v1/services/m3db/namespace  # FAILURE
- execute GET on k8s guide documented endpoint http://127.0.0.1:7201/api/v1/namespace  # SUCCESS

It appears this path prefix is incorrect across all of the API docs and is likely a simple fix, but definitely confusing when the direct request from the docs doesn't work.

**Comment by richardartoul** [comment]
@swtch1 Thanks for the bug report! I'll take a look at this today.

**Comment by richardartoul** [comment]
Should be fixed by #1292 once it lands

**Comment by richardartoul** [comment]
Resolved
