### ISSUE TITLE
Support String Values

### ISSUE THREAD

**Issue by nfrush** [m3db/m3#1337]
With the release of Loki by Grafana, it would be a killer feature if m3 could ingest strings alongside float values. That way you could provide long term storage for unstructured log files.

**Comment by richardartoul** [comment]
So this feature is very alpha, but we're actually working on that now: https://github.com/m3db/m3/pull/1426

The basic idea is that you can provide a ProtoBuf schema then we automagically compress a stream of messages that match the schema.

I don't think it will be a good use case for logs necessarily, the type of compression we're doing is likely to perform very poorly on unstructured logs. However, it will probably be very useful if you want to use it as an "event store" where you're storing a stream of structured events
