### ISSUE TITLE
Remaining index optimizations

### ISSUE THREAD

**Issue by robskillington** [m3db/m3#1365]
Tasks:
- [x] Review and merge the postings list cache P.R. https://github.com/m3db/m3/pull/1355.
- [ ] Modify the index flushing code to rely on mmap'd memory so that we can flush one segment instead of 4 without using a ton of memory during flush.
- [ ] Modify the database/create and database/namespace/create APIs to default to creating index blocksizes that are 2x larger than whatever data block size we recommend.
- [ ] Undo the hacky local to bitmap pilosa pooling implemented in our fork of pilosa and spend a few days trying to implement proper container pooling, and then get that merged back upstream.
- [ ] Update the FS bootstrapper (and even the peers bootstrapper) to always return FST segments rather than memory segments, along the way fixing the invariant violated issue in the FS bootstrapper that leads to a index block not being written to disk when index block size doesn't align with retention exactly.
- [ ] Take a blocking profile to see if postings list cache is highly contended

**Comment by richardartoul** [comment]
#1382 addresses bullet 3
