### ISSUE TITLE
HTTPJSON and TChannel interfaces reallocate identical pools

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1413]
Right now M3DB exposes most of its APIs over tchannel and thrift. For debugging and operator purposes, we also auto-generate HTTP/JSON equivalent endpoints for all of these functionalities.

The HTTP/JSON and TChannel/Thrift endpoints both instantiate instances of the same service layer, but this is wasteful because the service layer implements its own pooling. This means that we increase the pool sizes, they end up using twice as much memory even though only one of the pools is used in normal operations.

We should refactor `NewServer` in `src/dbnode/network/server/tchannelthrift/node/server.go` and `NewServer` in `src/dbnode/network/server/httpjson/node/server.go` to accept a tchannel service from `src/dbnode/network/server/tchannelthrift/node/service.go` instead of instantiating a new one in the `ListenAndServe` method each time so that they can share the same instance and thus share the same pools.

Similarly, we should do the same thing for `NewServer` in `src/dbnode/network/server/tchannelthrift/cluster/server.go` and `NewServer` in `src/dbnode/network/server/httpjson/cluster/server.go`

This change will also allow us to increase the default `writeBatchPooledReqPoolSize` in `src/dbnode/network/server/tchannelthrift/node/service.go` from `1024` to `4096` with very little additional memory usage

**Comment by Haijuncao** [comment]
fixed by
#1420
