### ISSUE TITLE
m3query `ColumBlock` should  preallocate its arrays in `AddCols`

### ISSUE THREAD

**Issue by andrewmains12** [m3db/m3#1416]
Since we know how long each column is when we call `AddCols`, we should preallocate each column appropriately. 

From @arnikola:

> we know the length of columns by len(seriesMeta), as each entry in the column has to match a series metadata value; might be worth refactoring the AppendValue(s) to fail if adding points that do not have associated metadatas.

This also applies to cost accounting (see https://github.com/m3db/m3/pull/1207/files#r257371896)

**Comment by arnikola** [comment]
As a quick addendum, should probably error when trying to create a block that does not have all of its columns (possibly in the `Build` function?) and when trying to add data points that go over the column length
