### ISSUE TITLE
literal is too long

### ISSUE THREAD

**Issue by jasongufeng** [m3db/m3#1424]
Hi dear friends! I am using M3DB for Prometheus remote datastore.  It throws the following exceptions:

<details>
`
11:09:32.550805[I] initial topology / placement value received
2019-03-01T11:09:32.731+0800	INFO	no m3msg server configured
2019-03-01T11:09:32.731+0800	INFO	starting server	{"address": "0.0.0.0:10921"}
11:09:32.846999[I] successfully updated topology to 10 hosts
2019-03-03T01:02:34.234+0800	ERROR	Write error	{"err": "literal is too long"}
github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote.(*PromWriteHandler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote/write.go:105
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
github.com/m3db/m3/src/query/util/logging.withPanicErrorResponderFunc.func1
	/Users/r/gocode/src/github.com/m3db/m3/src/query/util/logging/log.go:172
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
github.com/m3db/m3/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/vendor/github.com/gorilla/mux/mux.go:212
github.com/m3db/m3/src/x/net/http/cors.(*Handler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/x/net/http/cors/cors.go:102
net/http.serverHandler.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741
net/http.(*conn).serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847
2019-03-03T01:02:36.226+0800	ERROR	Write error	{"err": "literal is too long"}
github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote.(*PromWriteHandler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote/write.go:105
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
github.com/m3db/m3/src/query/util/logging.withPanicErrorResponderFunc.func1
	/Users/r/gocode/src/github.com/m3db/m3/src/query/util/logging/log.go:172
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
github.com/m3db/m3/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/vendor/github.com/gorilla/mux/mux.go:212
github.com/m3db/m3/src/x/net/http/cors.(*Handler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/x/net/http/cors/cors.go:102
net/http.serverHandler.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741
net/http.(*conn).serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847
2019-03-03T01:02:37.624+0800	ERROR	Write error	{"err": "literal is too long"}
github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote.(*PromWriteHandler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote/write.go:105
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
github.com/m3db/m3/src/query/util/logging.withPanicErrorResponderFunc.func1
	/Users/r/gocode/src/github.com/m3db/m3/src/query/util/logging/log.go:172
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
github.com/m3db/m3/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/vendor/github.com/gorilla/mux/mux.go:212
github.com/m3db/m3/src/x/net/http/cors.(*Handler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/x/net/http/cors/cors.go:102
net/http.serverHandler.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741
net/http.(*conn).serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847
2019-03-03T01:03:49.320+0800	ERROR	Write error	{"err": "literal is too long"}
github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote.(*PromWriteHandler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote/write.go:105
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
github.com/m3db/m3/src/query/util/logging.withPanicErrorResponderFunc.func1
	/Users/r/gocode/src/github.com/m3db/m3/src/query/util/logging/log.go:172
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
github.com/m3db/m3/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/vendor/github.com/gorilla/mux/mux.go:212
github.com/m3db/m3/src/x/net/http/cors.(*Handler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/x/net/http/cors/cors.go:102
net/http.serverHandler.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741
net/http.(*conn).serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847
2019-03-03T01:03:51.183+0800	ERROR	Write error	{"err": "literal is too long"}
github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote.(*PromWriteHandler).ServeHTTP
`
</details>

Please take a look! Many thanks!

**Comment by richardartoul** [comment]
@jasongufeng It looks like we impose a limit of 4096 bytes for a tag name and value, so this is probably happening because you have some massive tag names or values.

The database code itself allows this limit to be increased, but its not wired up to our YAML config.

Do you really want to retain tags of this size?

**Comment by richardartoul** [comment]
@prateek Is there a reason we have this limit in place?

**Comment by prateek** [comment]
@richardartoul the limit for 4096 is more for sanity than anything else. Can be bumped if needed. 

@jasongufeng What dataset are you trying to retain where Tag names/values are longer than 4096?

**Comment by richardartoul** [comment]
Should we just config it? Can improve the error message to say if you want to bump the limit edit the config and then we can include it in our sample configs

**Comment by stephanieengelhardt** [comment]
I'm also running into the same problem and was wondering if you guys are planning on making it into a configurable option. If so, do you guys have an idea of when it may be implemented by? Thank you!

**Comment by stephanieengelhardt** [comment]
I'm also running into the same problem and was wondering if you are planning on making it into a configurable option. If so, do you have an idea of when it may be implemented by? Thank you!

**Comment by prateek** [comment]
@stephanieengelhardt I'll put up a change to make the limit 64K by default (from 4K currently) for now: https://github.com/m3db/m3/pull/1552. That's the highest it can be set without a more involved change, will it suffice for your needs? 

When you say limit none, how high are you thinking? Like megabytes?

**Comment by prateek** [comment]
@stephanieengelhardt the change is available in latest release: https://github.com/m3db/m3/releases/tag/v0.8.3. 

It's a setting that affects both client/server side of the connection, so you'll need to upgrade all processes (dbnode, coordinator, query) in your deployment.

**Comment by stephanieengelhardt** [comment]
Thank you, @prateek! I think 64K should suffice- thanks again! 👍

**Comment by prateek** [comment]
@stephanieengelhardt great, glad to hear it. 

I'm going to close this for now. @jasongufeng feel free to reopen if 64K isn't going to work for you.

**Comment by jasongufeng** [comment]
Many thanks!
