### ISSUE TITLE
"err": "context canceled"

### ISSUE THREAD

**Issue by jasongufeng** [m3db/m3#1425]
Hi dear friends, any idea about the exceptions? Thanks!
`
2019-03-01T16:12:02.406+0800	INFO	starting server	{"address": "0.0.0.0:10921"}
16:12:02.551416[I] successfully updated topology to 10 hosts
2019-03-01T21:54:48.004+0800	ERROR	Write error	{"err": "context canceled"}
github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote.(*PromWriteHandler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote/write.go:105
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
github.com/m3db/m3/src/query/util/logging.withPanicErrorResponderFunc.func1
	/Users/r/gocode/src/github.com/m3db/m3/src/query/util/logging/log.go:172
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
github.com/m3db/m3/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/vendor/github.com/gorilla/mux/mux.go:212
github.com/m3db/m3/src/x/net/http/cors.(*Handler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/x/net/http/cors/cors.go:102
net/http.serverHandler.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741
net/http.(*conn).serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847
2019-03-01T21:55:04.993+0800	ERROR	Write error	{"err": "context canceled"}
github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote.(*PromWriteHandler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote/write.go:105
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
github.com/m3db/m3/src/query/util/logging.withPanicErrorResponderFunc.func1
	/Users/r/gocode/src/github.com/m3db/m3/src/query/util/logging/log.go:172
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
net/http.Handler.ServeHTTP-fm
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/h2_bundle.go:5592
net/http.HandlerFunc.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964
github.com/m3db/m3/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/vendor/github.com/gorilla/mux/mux.go:212
github.com/m3db/m3/src/x/net/http/cors.(*Handler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/x/net/http/cors/cors.go:102
net/http.serverHandler.ServeHTTP
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741
net/http.(*conn).serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847
2019-03-01T21:55:13.394+0800	ERROR	Write error	{"err": "context canceled"}
github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote.(*PromWriteHandler).ServeHTTP
	/Users/r/gocode/src/github.com/m3db/m3/src/query/api/v1/handler/prometheus/remote/write.go:105
net/http.Handler.ServeHTTP-fm
`

**Comment by richardartoul** [comment]
@arnikola Any idea about this? Usually when its a timeout its something about the context deadline being exceeded

**Comment by arnikola** [comment]
This error indicates that there's a write to multiple backends, at least one of which fails; typically the first failing write will get written out with the appropriate error message, and then any pending writes to other stores will be cancelled. 

Were there any logs prior to this? They should help identify the root issue

**Comment by arnikola** [comment]
Yeah, seeing https://github.com/m3db/m3/issues/1424 this looks like everything should be working as expected; this particular error is more of a warning message that something else has already gone wrong

**Comment by richardartoul** [comment]
@arnikola Could this be related to #1425 as well? I.E write to one namespace gets a tag literal is too large error, which then triggers context cancels for the remaining outstanding namespaces?

**Comment by jasongufeng** [comment]
@richardartoul The errors on #1425 are thrown by  another coordinator. I have more 15 coordinators and 10 data nodes.

**Comment by richardartoul** [comment]
@jasongufeng Sure, its just this error is indicative of some other error happening first. Do you happen to have any additional logs from when this occurred? Its possible #1424 happened first and then you saw this error as well

**Comment by arnikola** [comment]
Yeah this one should fire when another write fails; likely the long literal from #1424 is cancelling any remaining writes

**Comment by jasongufeng** [comment]
@richardartoul  
They are on different VM and on different time. Before the errors, there are no any other errors. "successfully updated topology to 10 hosts" is the node initially up info.

`
2019-03-01T16:12:02.406+0800	INFO	starting server	{"address": "0.0.0.0:10921"}
**16:12:02.551416[I] successfully updated topology to 10 hosts
2019-03-01T21:54:48.004+0800	ERROR	Write error	{"err": "context canceled"}**


2019-03-01T11:09:32.731+0800	INFO	starting server	{"address": "0.0.0.0:10921"}
**11:09:32.846999[I] successfully updated topology to 10 hosts**
**2019-03-03T01:02:34.234+0800	ERROR	Write error	{"err": "literal is too long"}**
`
