### ISSUE TITLE
[feature]Allow unaggregated namespace store in SSD node, route aggregated namespace to SAS/HDD node

### ISSUE THREAD

**Issue by naughtyGitCat** [m3db/m3#1435]
1. What service is experiencing the issue? (M3Coordinator, M3DB)

In Prometheus sidecar situation, we usually pay more attention to the latest unaggregated monitor data, thus we can use SSD machine to boost performance. The aggregated data is less used, should not take up the SSD disk space, we can put them in cheap storage(SAS or HDD)

**Comment by richardartoul** [comment]
@naughtyGitCat I think the only thing stopping you from doing this is the ability to connect to different M3DB clusters in in coordinator. @arnikola @benraskin92 We don't currently support that right?
