### ISSUE TITLE
M3DB Read Performance Issues

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1438]
While looking through the code for unrelated reasons, I noticed that M3DB does two things that make reads more inefficient than they should be:

1. The series holds an RLock() while fetching data from disk. This means that disk reads will be blocked by memory writes which is unnecessary and similarly memory writes will be blocked by disk reads which is also inefficient.

2. For a given series, M3DB will attempt to read all uncached blocks from disk sequentially (and while still holding a series RLock). The Retriever itself already manages concurrency so we could probably reduce P99 latency by issuing the `retriever.Stream` calls in parallel and then allowing the retriever to manage the concurrency limiting with the `FetchConcurrency` config.

**Comment by richardartoul** [comment]
@robskillington thoughts?

**Comment by timchenxiaoyu** [comment]
m3db read three weeks data, cost 78s, 
prometheus tsdb cost 14s

**Comment by robskillington** [comment]
@timchenxiaoyu can you list a few things that might help us discern what kind of query you're experiencing that's slower?

i.e. number of time series that comprise the query (pre-aggregation), the frequency of datapoints, etc?

Ideally sending us all the raw data that would be returned if you didn't add any functions as part of the query (in an anonymized fashion, i.e. replace metric tags, names and values potentially with anonymized values) could help us reproduce your query.

**Comment by robskillington** [comment]
As discussed with @richardartoul there's actually no contention issues due to the fact that when we ask the block retriever to fetch a block for a series from the series reader, we only enqueue the request, we don't actually hold any locks while time series data is fetched from disk since this happens asynchronously returned as as essentially a promise/future from the block retriever.

**Comment by robskillington** [comment]
@timchenxiaoyu if you can provide details we can reopen this issue, but currently there's no issues we know of in particular to address right now on the read side - at least for the non-index part of the query that is.
