### ISSUE TITLE
Missing API docs for non-mangement endpoints

### ISSUE THREAD

**Issue by mstump** [m3db/m3#1444]
Documentation is currently missing for the endpoints below. I had to go to the thrift definition to know that they existed. API reference and docs should be updated to describe the following methods.

- write
- writeTagged
- fetch
- fetchTagged
- fetchBatchRaw
- fetchBlocksRaw
- fetchBlocksMetadataRawV2
- writeBatchRaw
- writeTaggedBatchRaw
- repair
- truncate
- query

**Comment by richardartoul** [comment]
@mstump Yeah these APIs are undocumented because they all use tchannel/thrift unfortunately :/ We have auto-generated http/json versions of them, but those are very inefficient and are use mostly for manual testing / debugging

**Comment by mstump** [comment]
Not at the moment. I was going to use them to push data to m3, but after raising the plan on gitter I was encouraged to use the Prometheus remote write endpoint instead.

**Comment by richardpoole** [comment]
I also ran into the same issue as @mstump. Would it be possible to add these endpoints to the OpenAPI documentation with a comment indicating that they're not suitable for production use? I'd find it clearer if they were documented with a disclaimer than not documented at all.
