### ISSUE TITLE
No clear documentation on how to configure m3coordinator with kubernetes deployment mode

### ISSUE THREAD

**Issue by yunstanford** [m3db/m3#1500]
Hey, I can't find clear documentation around configuring m3coordinator when deploying with kubernetes (or using the kubernetes operator). Any pointer ?

**Comment by richardartoul** [comment]
@schallert Could you chime in here? Are we still recommending embedded coordinator for K8s clusters?

**Comment by schallert** [comment]
Hey, we've started to work on some dedicated coordinator static manifests for both cases and should have this out in the next few days.

**Comment by marcusbooyah** [comment]
Any updates here?
