### ISSUE TITLE
Question around Graphite Integration

### ISSUE THREAD

**Issue by yunstanford** [m3db/m3#1504]
I've set up a cluster with Graphite Integration, also i can fetch metrics from M3 for metrics that sent through carbon protocol(e.g. ```echo "local.random.diceroll 4 `date +%s`" | nc localhost 7204```). But looks like the graphite api could not query metrics that sent through `curl -sS -X POST http://localhost:9003/writetagged`, `seriesByTag` doesn't seem to work...
Are those metrics stored in different namespaces ? Any clear documentation/pointer ?

**Comment by richardartoul** [comment]
@yunstanford There is a bit of nuance here, but the high level TLDR is that M3DB is a time-series data where each time series gets:

1. A unique ID (unindexed)
2. Key-value pairs (queryable via our reverse index)
3. A stream of actual data

When you use the `writetagged` API directly (btw that HTTP/JSON endpoint is heavily reflection based / inefficient so I would not use it for a high throughput production workload) you provide a series IDs as well as tags and you can query it by tags very similarly to if you were using Prometheus or some other tag-based system.

Graphite metrics, on the other hand, are not tag based. So internally what we do is [convert them like this](https://github.com/m3db/m3/blob/8cddc48033f0451d30a596c632299b16880e64e7/src/query/graphite/graphite/tags.go#L26)

Thats why if you write data via one pathway `writetagged` and then try to query it via a different pathway `graphite`, you'll have trouble.

Does that make sense?

If you want to write data via `writetagged` (again not recommended, its slow and inefficient, etc) you'll need to construct it into the tag structure described here: https://github.com/m3db/m3/blob/8cddc48033f0451d30a596c632299b16880e64e7/src/query/graphite/graphite/tags.go#L26

**Comment by yunstanford** [comment]
@richardartoul Thanks for explaining, that makes sense. Also curious if you guys have benchmarked high throughput writing traffic against Graphite protocol ?

**Comment by richardartoul** [comment]
@yunstanford Yeah so I benchmarked the coordinator side of things at least. I was using some medium level GCP hardware (16 core machine I think) and was able to do a few hundred thousand writes per second via the graphite ingestion interface in the coordinator. Wish I could share more concrete values, but I was just doing some optimizations right after I wrote the feature and once I got to a few hundred thousand per second and didn't see any more low hanging fruit in the flame graphs I stopped so that pathway should be relatively efficient

**Comment by richardartoul** [comment]
Closing this unless you have further questions.

Cheers,
     Richie
