### ISSUE TITLE
Programmatically warn on deprecated config fields

### ISSUE THREAD

**Issue by schallert** [m3db/m3#1549]
We currently have a few config fields that are deprecated that we may manually emit warnings on if we see them. It would be convenient if we could add a struct tag or something similar to accomplish the goal of tagging deprecated config fields and warning on them. This is especially relevant as we have strict config parsing, wherein unknown fields fail to parse.

**Comment by schallert** [comment]
@richardartoul @robskillington @prateek can you think of any config params that we currently have that are deprecated? @obitech is taking a look at this issue and wondering if we have any fields we could test this out on :)

**Comment by richardartoul** [comment]
Yeah so we have established this pattern of prefixing the field name in Golang with `Deprecated` while leaving the `yaml` name unchanged. A good example is this one: https://github.com/m3db/m3/blob/master/src/cmd/services/m3dbnode/config/config.go#L275

**Comment by obitech** [comment]
@schallert I have implemented a method which calls `logger.Warn()` when it finds a deprecated field:

```go
// DeprecationCheck checks the config for deprecated fields and emits a warning
// if any are found.
func DeprecationCheck(cfg interface{}, logger *zap.SugaredLogger) {
	n := reflect.TypeOf(cfg).NumField()
	for i := 0; i < n; i++ {
		v := reflect.ValueOf(cfg).Field(i)
		if v.Kind() == reflect.Struct {
			DeprecationCheck(v.Interface(), logger)
		}
		name := reflect.TypeOf(cfg).Field(i).Name
		if strings.HasPrefix(name, "Deprecated") {
			logger.Warn("using deprecated configuration field", zap.String("field", name))
		}
	}
}
```

Although I'm unsure where to apply this function. Ideally it would be called in `config.LoadFiles` however if we just want to warn about the fields we would have to pass a Logger as well  which is usually initialised after the config is loaded.

Also if we're using `logger.Warn()` to indicate deprecation, I'm not sure how to write unit tests for the log message to actually appear.

Any suggestions / feedback on this?

**Comment by schallert** [comment]
Hey @obitech, this seems like a good approach! Two options I can see for logging are either call this function after `LoadFiles` once the logger is constructed like you mentioned, or calling it during and logging using some form of `Fprintf` and `os.Stderr`.

I think it's file to call this once the logger is constructed, as we're just emitting warnings and not actually blocking config loading. For testability I think it would be fine to have `DeprecationCheck` return a slice of non-zero deprecated fields and just warn about each of those.

**Comment by obitech** [comment]
Awesome, thanks @schallert ! I'll start working on a PR.
