### ISSUE TITLE
Turning on a new cluster for the first time can take a long time

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1563]
Nodes will not mark their shards as "Available" until they are "bootstrapped and durable" which means that a complete snapshot has taken place since they've finished bootstrapping any new shards that they have received. In most cases this is fine and correct, however, in the case of turning on a new cluster this safeguard is overly precautious.

Normally the over precaution is not an issue, but when turning on a new cluster that has a large number of blocks (millions due to combinations of namespaces, blocksizes, and retentions) then the node will not mark its shards as available until all of the files on disk for all of the blocks have been created (as either a flush or snapshot, depending on when the operation takes places).

We should find a way to prevent this operation from blocking in the special case that its a new cluster, OR find a way to make creating the files not take so long.

**Comment by richardartoul** [comment]
After some discussions with @prateek it seems like the cleanest solution to this problem would be to add a new type of bootstrapper at the top of the list that would detect when all of the replicas for a given shard are in the INITIALIZING state or when a given shard in an INITIALIZING state has no corresponding LEAVING shard and if thats true then it would pre-emptively create all of the fileset files that are needed for the entire duration of a namespace.

The benefit of doing this in a bootstrapper is that we can increase the concurrency to very high levels knowing with confidence that we aren't interfering with any other database operations since the node will not be accepting writes.

**Comment by kuldeeps88** [comment]
@richardartoul @prateek 
Can you provide inputs for the bootstrap which is taking too long for a retention period of "1440h".

**Comment by kuldeeps88** [comment]
Any new update on this issue ?
