### ISSUE TITLE
PromQL Offset not supported

### ISSUE THREAD

**Issue by Nexucis** [m3db/m3#1569]
Hello,

in promQL you have the modifier **offset** and currently m3coordinator or m3db completely ignores it.

Example of promQL with **offset** : 

```
rate(msg_received_total[5m] offset 1d)
```

## Version used
Grafana : v6.1.3
m3db : v0.8.3
prometheus: v2.9.1

**Comment by prateek** [comment]
@Nexucis thank you for the report! @arnikola is landing support for this via https://github.com/m3db/m3/pull/1561 soon

**Comment by Nexucis** [comment]
oh nice, I didn't see the PR. Thanks @prateek :)

**Comment by robskillington** [comment]
@Nexucis this got merged with this PR:
https://github.com/m3db/m3/pull/1561

And is available as 0.8.4:
https://github.com/m3db/m3/releases/tag/v0.8.4
