### ISSUE TITLE
Issue with cluster metric insert 

### ISSUE THREAD

**Issue by tejasbhosale009** [m3db/m3#1573]
Initial m3data node process installed and also completed. also topology initialization also completed.
But after that i tried to test data insert getting this error ... 

curl -sS -X POST localhost:9003/writetagged -d '{
  "namespace": "metrics",
  "id": "foo",
  "tags": [
    {
      "name": "city",
      "value": "new_york"
    },
    {
      "name": "endpoint",
      "value": "/request"
    }
  ],
  "datapoint": {
    "timestamp": '"$(date "+%s")"',
    "value": 42.123456789
  }
}'
{"error":{"message":"Error({Type:INTERNAL_ERROR Message:failed to meet consistency level majority with 0/3 success, 3 nodes responded, errors: [shard 32 in host mth03-tej is not available (initializing) shard 32 in host mth02-tej is not available (initializing) shard 32 in host mth01-tej is not available (initializing)]})","data":{"type":"INTERNAL_ERROR","message":"failed to meet consistency level majority with 0/3 success, 3 nodes responded, errors: [shard 32 in host mth03-tej is not available (initializing) shard 32 in host mth02-tej is not available (initializing) shard 32 in host mth01-tej is not available (initializing)]"}}}

Can any one please help

**Comment by richardartoul** [comment]
@tejasbhosale009 Sometimes it can take a little while for a new cluster to fully "turn on". Did the issue persist after waiting for awhile?

What CURLs did you use for your namespaces

**Comment by tejasbhosale009** [comment]
Yes its resolved now .. we have to wait for some time
