### ISSUE TITLE
Move dbnode/storage/namespace out of storage, into dbnode

### ISSUE THREAD

**Issue by Haijuncao** [m3db/m3#1599]
dbnode/storage/namespace stores namespace metadata including schema, it is referenced in client, encoder. For this reason, we propose to move namespace out of storage into dbnode. 

The other option is to move schema related code into its own package under storage. 

What do you guys think?

**Comment by robskillington** [comment]
I think a high-level package outside of `storage` likely makes sense since `client` is not in the `storage` tree of `dbnode`.
