### ISSUE TITLE
one m3db node restart for oom, then the cluster error

### ISSUE THREAD

**Issue by iyacontrol** [m3db/m3#1626]
i try a big query , so node restart for oom, but the cluster error.

error log :
`May 10 02:32:57 ip-172-250-77-186.ap-southeast-1.compute.internal m3dbnode[16472]: {"level":"error","ts":1557455577.6187174,"msg":"opting to skip commit log due to corruption","bootstrapper":"commitlog","error":"/m3/m3db/commitlogs/commitlog-0-5662.db: EOF"}
`

but the /m3/m3db/commitlogs/commitlog-0-5662.db is empty.

**Comment by richardartoul** [comment]
@iyacontrol As long as you have https://github.com/m3db/m3/blob/master/src/dbnode/config/m3dbnode-local-etcd.yml#L69 set in your YAML file the node should turn on anyways

**Comment by arnaud-mey** [comment]
Unfortunately, this doesn't seem to help for us on v0.9.0. We had to downgrade to v0.8.4.
@iyacontrol Did it solve your issue?

**Comment by iyacontrol** [comment]
@arnaud-mey  no。 i have to delete commitlogs before restart.
