### ISSUE TITLE
Migrating existing prometheus data to m3db storage.

### ISSUE THREAD

**Issue by kuldeeps88** [m3db/m3#1629]
we are using Prometheus with data stored in Kubernetes node or on EFS.

Query:
1. How can I copy or port old data to m3db storage.
2. Is there a config in m3db-coordinator to support both old or new data.

**Comment by zebozhuang** [comment]
I have met the same problem how to migrate old data to m3db.  Hope m3db team develop a migration tool.

**Comment by martin-mao** [comment]
Hey @kuldeeps88, we're working on a mechanism where you can read your old data and write into M3DB, but that's still a few weeks away. In the meantime, you can emit your new data to M3DB and query your old data from Prom?

**Comment by signmem** [comment]
@martin-mao  do you mean M3DB support cold write function in few week later?  I have two years data in opentsdb. but now I can not put my opentsadb old data into m3db only if I change time of m3db server.

**Comment by martin-mao** [comment]
Hey @signmem, yes the M3DB cold write feature should only be a few weeks away, so I would wait for that. You can dual emit to both in the meantime just so you have the newer data in m3db and backfill when the feature is ready.

**Comment by afzouni** [comment]
Hey, How can I port old data to m3db or support both old Prometheus and m3db?
