### ISSUE TITLE
Remove prom_process_collector.go and report process metrics from process reporter

### ISSUE THREAD

**Issue by robskillington** [m3db/m3#1649]
`prom_process_collector.go` was introduced to alleviate the fact we removed the default Prometheus collector due to it's excessive load when counting open FDs with processes that had a large number of FDs.

A modified version of the Prometheus process collector was restored to add back stats removed from the fix to avoid reporting open FDs from the Prometheus collector.  For more see https://github.com/m3db/m3/pull/1633.

We should remove this modified version of the Prometheus process collector once the M3 process reporter reports the same information.

**Comment by yangxiangyu** [comment]
Solved the problem that bothered me today👍
