### ISSUE TITLE
Move dbnode/encoding package to x/encoding

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1654]
The encoding package is depended on by m3query/coordinator, m3db, as well as some of our internal services. It would be cleaner to move this package out to src/x instead of having everything import dbnode packages.

**Comment by obitech** [comment]
Hey Richard, could this be a good first issue? Do you need any help with this?

**Comment by richardartoul** [comment]
@obitech Sorry this slipped through the cracks. I took a look and I actually don't think this is a good first issue.

This would be a great first issue if you're keen: https://github.com/m3db/m3/issues/1142

If you're interested let me know and I'll be happy to setup a call to walk you through it. You can join our gitter: https://gitter.im/m3db/Lobby to get in touch.

Or i could just share some details in that ticket. Either way.

**Comment by obitech** [comment]
That's awesome! Let me send you a message on Gitter.
