### ISSUE TITLE
m3query cpu  high usage

### ISSUE THREAD

**Issue by signmem** [m3db/m3#1678]
m3cluster
> five Huawei compute here.
>I use 3 compute build m3db cluster.
>another one compute use for m3query.
> another one use for ab tools testing.

useto
>I use ab tools test m3query  to get QPS.
>get metric from m3dbnode in one hour ( in memory)
>time step = 15s
> total metric value is 240.

ab command above:
```
ab -n 6000 -c 30  'http://m3query:7207/api/v1/query_range?query=user_login&start=1559205493&end=1559209092&step=15s'
```

testing resule

>I got about 1111 QPS. (its tooooooo low I believe.)
>in the condition.  compute runing m3query process is high cpu usage . 
>HYPERVISOR is 24CORE INTEL CPU. and just use to run m3query process.  no other process useful.
>cpu load avg is increasing. and cpu idel is about 5% ~ 7%

here is my profile svg example :

[profile002.zip](https://github.com/m3db/m3/files/3236785/profile002.zip)

*can you please tell me how can I resolve this problem ?*

**Comment by martin-mao** [comment]
@benraskin92 @arnikola Can have a deeper look, but from the profile, it seems like most of your CPU is spend on decoding series (fetching data). There is about 20% spend on cost accounting and possibly being rate limited, so maybe we could increase some limitations there, but the bulk of it is spent on actual queries.

**Comment by arnikola** [comment]
Would you be able to show us a flame graph too? We're looking at a similar issue that someone else reported and that would help us understand if it's the same root cause

**Comment by arnikola** [comment]
@signmem Could you also post your coordinator configuration? In particular, the `namespaces` stanza

**Comment by arnikola** [comment]
Also, any chance you can give us your ns config? You can do `curl <address>:7201/api/v1/namespace` to get it

**Comment by signmem** [comment]
# purpose
> We wanna build tsdb perform using M3DB cluster use for production environment.  
> So I tested the m3db query and write performance limit.
> I use ab tools to connect m3query to testing QPS.

# structure
its my hypervisor structure.
<table>
<tr>
<td>hostname</td><td>ram</td><td>cpu</td><td>role</td><td>network</td>
</tr>
<tr>
<td>m3dbnode01</td><td>128GB</td><td>32CORE</td><td>m3dbnode</td><td>10000m X 2 (bonding)</td>
</tr>
<tr>
<td>m3dbnode02</td><td>128GB</td><td>32CORE</td><td>m3dbnode</td><td>10000m X 2 (bonding)</td>
</tr>
<tr>
<td>m3dbnode03</td><td>128GB</td><td>32CORE</td><td>m3dbnode</td><td>10000m X 2 (bonding)</td>
</tr>
<tr>
<td>m3query01</td><td>128GB</td><td>32CORE</td><td>m3query</td><td>1000m X 2 (bonding)</td>
</tr>
<tr>
<td>m3query02</td><td>128GB</td><td>32CORE</td><td>m3query</td><td>10000m X 2 (bonding)</td>
</tr>
<tr>
<td>m3test01</td><td>128GB</td><td>32CORE</td><td>ab test tools</td><td>1000m X 2 (bonding)</td>
</tr>
<tr>
<td>m3test02</td><td>128GB</td><td>32CORE</td><td>ab test tools</td><td>10000m X 2 (bonding)</td>
</tr>
</table>

> m3test01 use to connection m3query01 test for 10000m network status
> m3test02 use to connection m3query02 test for 10000m network status

# Namespace
it my testing namespace

<table>
<tr>
<td>namespace</td><td>retention</td><td>blockSize</td><td>bufferFuture</td><td>bufferPast</td>
</tr>
<tr>
<td>app</td><td>1440h</td><td>2h</td><td>1h</td><td>1h</td>
</tr>
<tr>
<td>dev</td><td>1440h</td><td>4h</td><td>1h</td><td>1h</td>
</tr>
<tr>
<td>opt</td><td>1440h</td><td>24h</td><td>1h</td><td>1h</td>
</tr>
<tr>
<tr>
<td>tools</td><td>1440h</td><td>2h</td><td>1h</td><td>1h</td>
</tr>
<tr>
</table>

# metric
metric infomation
<table>
<tr>
<td>Number of Servers</td><td>100</td>
</tr>
<tr>
<td>Values measured per Server</td><td>100</td>
</tr>
<tr>
<td>Measurement Interval</td><td>10s</td>
</tr>
<tr>
<td>Dataset Duration(s)</td><td>24h</td>
</tr>
<tr>
<td>every 24h metric</td><td>7,776,000</td>
</tr>
</table>

# testing case
[we reference resources about influxdb benchmark example.](https://github.com/influxdata/influxdb-comparisons)

its my testing case.

>  ab -n 8000 -n 50  http://xxx  ( the same query about 50 concurrents , connect 8000 times )
> metric query like  ( max(cpu_usage_user{hostname="host_1"} or cpu_usage_user{hostname="host_0"} ) )
> time frame,   3600s
> step   10s

ab example:

```
ab -n 8000 -n 50 'http://m3query:7205/api/v1/query_range?query=max(cpu_usage_user{hostname="host_1"} or cpu_usage_user{hostname="host_10"})&start=1558179000&end=1558182600&step=10
```

# result 

We tested influxdb and m3db in the same environment,  
M3DB query and write ability is better then influxdb.

<table>
<tr>
<td>role</td><td>result</td>
</tr>
<tr>
<td>m3query</td><td>graph m3query</td>
</tr>
<tr>
<td>m3dbnode</td><td>graph m3dbnode</td>
</tr>
</table>

## graph m3query
![m3query](https://user-images.githubusercontent.com/37522374/59328574-473a0c80-8d1f-11e9-90d8-b31d68f2eb37.png)

## graph m3dbnode
![m3db](https://user-images.githubusercontent.com/37522374/59328986-55d4f380-8d20-11e9-8758-f14372da10de.png)


CPU usage is the bottleneck in this test.
The difference between Gigabit networks and Gigabit networks is that more QPS capabilities can be obtained.

**Comment by dshowing** [comment]
@signmem That's great. How do write tests work? I saw the m3nsch tool, but I don't know how to use it. @arnikola Hopefully an official documentation on performance testing will be provided, m3db has great potential.
