### ISSUE TITLE
Schema backward compatibility check

### ISSUE THREAD

**Issue by Haijuncao** [m3db/m3#1681]
When user deploy a schema, we should perform some schema backward compability check/verification, if a schema is not backward compatible, the schema deployment should be rejected. 

We should first come up with a clear set of backward compatibility rules. 

The verification module should be extensible to allow new rules to be added. Though, we should keep it simple, not over-engineer it to a rule engine or require any domain specific language. The extensibility refers to making code changes easier.

**Comment by richardartoul** [comment]
@Haijuncao can we tie these altogether into a master issue so we have one place to look at to see remaining work?

**Comment by Haijuncao** [comment]
> @Haijuncao can we tie these altogether into a master issue so we have one place to look at to see remaining work?

I have created a new label: C: Schema Management and tag new issues with it.
