### ISSUE TITLE
Unchecked error in updateSchemaRegistry

### ISSUE THREAD

**Issue by justinjc** [m3db/m3#1694]
The call [here](https://github.com/m3db/m3/blob/83d0a46dfcbb350335dbba411f9f9c795a8d4bbd/src/dbnode/storage/database.go#L236) to `GetLatestSchema` should be checked.

**Comment by Haijuncao** [comment]
The error here can be NotFound, which is ok, implies curSchema == nil
still, we can be explicit and check for error other than NotFound.
