### ISSUE TITLE
Increasing weight of a newly added node

### ISSUE THREAD

**Issue by filippog** [m3db/m3#1699]
Hi,
thanks for open sourcing M3 ! I'm reading through the documentation to get an idea of how we could implement M3 in our environment by self-hosting and operating it.

Reading through [adding a node](http://m3db.github.io/m3/operational_guide/placement_configuration/#adding-a-node) it is unclear to me if I can bump the node's weight gradually after add. The scenario I have in mind is not necessarily knowing what's the right value for e.g. a new generation of hardware or not wanting to have full weight on a node right off the bat, does it make sense to you?

thanks in advance!
Filippo

**Comment by martin-mao** [comment]
Yes you can change the weight over time, but you won't see any effects until a new node is added. For example, if your weight is 10 initially and you bump this up to 15, nothing will happen until you change the composition of your cluster (either remove or adding a node). When you do that and we try and figure out how to redistribute the shards, the new number will come into affect and that node should get more shards/data relatively to what it had previously.
