### ISSUE TITLE
API use for check cluster status

### ISSUE THREAD

**Issue by signmem** [m3db/m3#1719]
question
> Is there some RESTful API to check M3DB cluster health status?   
>>  I want check cluster status by one command to one restful api ..
>> m3dbnode:9002/health   it not useful to check cluster status, but host status.
>
> m3db startup after reboot to get into stable is tooooo slow ....
>  [  m3db/data/namespace   ( 1929984 files )  ]   **   is there too much file to boot slowly ??  **

hardware desc.
> In my testing cluster.  3 Hypervisor m3dbnode. 

namespace desc.
> "retentionPeriodDuration": "1440h", 
> "blockSizeDuration": "2h",
> "bufferPastDuration": "1h",

example even.
> input some metric into M3DB cluster..  100 metric total.
>1.  I restart all of the M3DB cluster.
>2.  I can insert data into M3DB cluster.  but  I can not get data from  query api. 
>>   I kown,  M3DB must check index/data consistence.  but it took too long about it.  ( 2 HOURs about)

**Comment by richardartoul** [comment]
@signmem We have metrics for this, is that not sufficient? I'm sure we could add some kind of cluster API but curious if there is a reason metrics aren't good enough. Do you have some programmatic use case?
