### ISSUE TITLE
endpoint parameter is not validated in placement/init

### ISSUE THREAD

**Issue by Freeaqingme** [m3db/m3#1739]
When initiating the placement map, there appears to be no validation on the provided endpoint.

E.g., consider the following init placement:
```
curl -X POST localhost:7201/api/v1/placement/init -d '{
    "num_shards": 64,
    "replication_factor": 1,
    "instances": [
        {
            "id": "m3db1",
            "isolation_group": "hpv1",
            "zone": "embedded",
            "weight": 100,
            "endpoint": "D:E:A:D::BE:EF",
            "hostname": "m3db1",
            "port": 9000
        }
    ]
}'
```

The http api will acept this as-is. However, when trying to write to it, the displayed error is:
```
Jun 14 18:40:10 m3db1 m3dbnode[3084]: {"level":"warn","ts":1560537610.2531402,"msg":"cluster connect with consistency any","error":"timed out connecting, returning success"}
Jun 14 18:40:10 m3db1 m3dbnode[3084]: {"level":"info","ts":1560537610.41023,"msg":"successfully updated topology","numHosts":1}
```

The log files do not appear to log anything out of the ordinary (loglevel=info). Only when the loglevel is elevated to debug, this message is showed continuously:
```
Jun 14 18:45:07 m3db1 m3dbnode[4192]: {"level":"debug","ts":1560537907.3655882,"msg":"could not connect, failed health check","host":"D:E:A:D::BE:EF","error":"dial tcp: address D:E:A:D::BE:EF: too many colons in address"}
```

Turns out, the right syntax was:
```
"endpoint": "[D:E:A:D::BE:EF]:9000"
```

I'd suggest to add something that validates if a valid endpoint was provided when configuring the placement map. Alternatively (and/or), the above displayed error message could be elevated to error so that people have a larger chance to notice it.

I'm well aware this was a case of PEBKAC, but as long as humans are the ones who configure M3 that's probably a factor to keep into account :)

**Comment by Freeaqingme** [comment]
Also, the reason I initially only filled out an ip address only without the port is that there's a separate field called 'port'. At first glance this seems redundant?

**Comment by xkfen** [comment]
hi guys, i have the same problem .
my etcd:
`etcd-0  n4.ha.env.lab.io  10.40.112.1
etcd-1  ceph-node3.ha.env.lab.io  10.40.240.1
etcd-2  ceph-node1.ha.env.lab.io  10.40.16.1`

my instance:
`{
  "type": "cluster",
  "namespaceName": "default",
  "retentionTime": "168h",
  "numShards": "1024",
  "replicationFactor": "3",
  "hosts": [
        {
            "id": "n4.ha.env.lab.io",
            "isolationGroup": "us-east1-a",
            "zone": "embedded",
            "weight": 100,
            "address": "10.40.112.1",
            "port": 9000
        },
        {
            "id": "ceph-node3.ha.env.lab.io",
            "isolationGroup": "us-east1-b",
            "zone": "embedded",
            "weight": 100,
            "address": "10.40.240.1",
            "port": 9000
        },
        {
            "id": "ceph-node1.ha.env.lab.io",
            "isolationGroup": "us-east1-c",
            "zone": "embedded",
            "weight": 100,
            "address": "10.40.16.1",
            "port": 9000
        }
    ]
}`
my m3dbnode.yaml :
`  config:
    service:
      env: default_env
      zone: embedded
      service: m3db
      cacheDir: /var/lib/m3kv
      etcdClusters:
        - zone: embedded
          endpoints:
            - 10.40.112.1:2379
            - 10.40.240.1:2379
            - 10.40.16.1:2379
    seedNodes:
      initialCluster:
        - hostID: n4.ha.env.lab.io
          endpoint: http://10.40.112.1:2380
        - hostID: ceph-node3.ha.env.lab.io
          endpoint: http://10.40.240.1:2380
        - hostID: ceph-node1.ha.env.lab.io
          endpoint: http://10.40.16.1:2380`

my m3db node log shows:
`{"level":"debug","ts":1582095030.802194,"msg":"could not connect, failed health check","host":"10.40.240.1:9000","error":"dial tcp 10.40.240.1:9000: connect: connection refused"}`

how to solve this ? any help.
