### ISSUE TITLE
failed opening lock path /var/lib/m3db/.lock: permission denied

### ISSUE THREAD

**Issue by xiasummer1019** [m3db/m3#1805]
when i start with a docker in a centos7 vmware virtual mechine on win10, it happned to me.
![image](https://user-images.githubusercontent.com/13645930/61171052-a603d780-a5a4-11e9-944d-529b1c310b9b.png)
does anyone know how to handle it ?

ths for watching!

**Comment by richardartoul** [comment]
@xiasummer1019 You can turn off the lock file behavior I believe, but more generally it seems like you don't have permission to create files/folders in the default data directory for m3db. You can change the YAML to point to a folder you do have permissions, or change the permissions on that directory so M3DB can modify it

**Comment by martin-mao** [comment]
@xiasummer1019 Just following up here and making sure you resolved this issue by either giving permission to the cache folder or changing the cache dir.
