### ISSUE TITLE
M3Aggregator is causing huge delay (resolution time) to send the aggregated metric to M3Coordinator

### ISSUE THREAD

**Issue by nightfury1204** [m3db/m3#1807]
I have been trying out M3Aggregator. But i am facing delay issue. It delays for at least resolution time to send the aggregated metric to M3coordinator. For example,
For `3m` resolution, it delays for +10m
For `15m` resolution, it delays for +30m.
For `1h` resolution, it delays for +1.5h.

For this, M3Coordinator failed to write data in th M3DB because data is too far in the past.

I posted my problem in the https://gitter.im/m3db and @martin-mao said to tune the flushManager's maxJitters and maxBufferSize. But that didn't solve the issue. Then i started debugging M3Aggregator code to see the reason. Reason was `targetNanos` is set to too past with compared to the current time. ref:  https://github.com/m3db/m3/blob/996b9b777e57fba466c48d8579d874118021ae46/src/aggregator/aggregator/gauge_elem_gen.go#L227

The `targetNanos` is set in here: https://github.com/m3db/m3/blob/3ce19227f3815ee270678300c059c818c9ea18b5/src/aggregator/aggregator/list.go#L310

The implementation:
https://github.com/m3db/m3/blob/3ce19227f3815ee270678300c059c818c9ea18b5/src/aggregator/aggregator/list.go#L722

So the equations to set `targetNanos` is resolved to something like this: 
```
targetNanos = CurrentTime - Resolution - BufferDurationForPastTimedMetric
```

That's why there is a huge delay when it sends the aggregated metric to M3Coordinator.
Also `flushManager` doesn't consider the `BufferDurationForPastTimedMetric` when determining the next flush time: https://github.com/m3db/m3/blob/3ce19227f3815ee270678300c059c818c9ea18b5/src/aggregator/aggregator/leader_flush_mgr.go#L157

It can also increase the delay, if you consider whole periodic process.

Without code change, I can not find anything that will help to solve the delay.
Why  `targetNanos` is set in that way?
What should i do to solve the delay?

**Comment by nightfury1204** [comment]
cc @robskillington @martin-mao

**Comment by robskillington** [comment]
It is true the logic is pretty conservative and delays resolution by a fair amount. 

If you're using high resolution (like 1h resolution, etc) you do need a significantly high buffer past value for that namespace on the DB side to avoid getting too far in past errors.

We could find a way to wire up configuration similar to the coordinator buffer past limits in the aggregator itself to allow users to configure different values perhaps?

**Comment by nightfury1204** [comment]
But here https://docs.m3db.io/operational_guide/namespace_configuration/. it says, too large buffer past will degrade performance. In addition, M3DB cannot evict a block from memory until it is no longer mutable and large bufferPast and bufferFuture values effectively increase the amount of time that a block is mutable for which means that it must be kept in memory for a longer period of time.

**Comment by meringu** [comment]
I think this sounds like a reasonable approach. The larger the resolution, the less memory the buffer should use. This should balance out with having to set large buffers.

Do you observe a large increase in memory when doing this in practice?
