### ISSUE TITLE
Dynamic Cluster Client Configuration

### ISSUE THREAD

**Issue by nerd0** [m3db/m3#1820]
## Issue 

The [m3 cluster client](https://github.com/m3db/m3/blob/master/src/cluster/client/) interface which is only implemented for [ETCD](https://github.com/m3db/m3/blob/master/src/cluster/client/etcd/client.go) uses static configurations to define the endpoint list for an ETCD cluster. ETCD will use this list to [internally load balance this list of endpoints](https://github.com/etcd-io/etcd/blob/master/docs/client-architecture.rst#clientv3-grpc10-balancer-overview). Combine that feature with the [AutoSyncInterval](https://github.com/etcd-io/etcd/blob/master/clientv3/config.go#L30-L32) configuration, an ETCD client is able to maintain an up to date list of ETCD cluster members to internally balance against. However if the ETCD cluster members completely change, the static configuration can drift from the active list. Perhaps dynamic configuration generation can address this short coming, however it would be convenient if the endpoint list could provide in a more dynamic fashion during runtime of the process. 

## Potential Solutions

1. Implement a standard option and interface pattern which allows for a cluster client channel to be used startup of services such as the [dbnode](https://github.com/m3db/m3/blob/d75fc9d75348df76bc6f4707beaff48d507eed53/src/dbnode/server/server.go#L115-L116) currently allows. 

      Pros: 
      - Allows users to dynamically update the ETCD client during startup of the service process. 

      Cons:
      - Does not reduce the amount of other `main.go` initialising of various objects required to startup of a service process. 

2.  Refactor `main.go` files for each services (aggregator, dbnode, etc.) to [only perform configuration file parsing](https://github.com/m3db/m3/compare/pschooss/create-init-within-main#diff-6d668dbaa020817c90b77c2ad733b2f8R60) afterwards call a `Setup()` or `Init()` function which has an input parameter of a parsed configuration data structure. 

       Pros:
       - Allows users to dynamically update the configuration for services during startup enabling the process to ensure configuration values are up to date. 
       -  Simple refactor and readability of code does not decrease by much. 

       Cons:
       - Would require users to maintain a separate `main.go` to dynamically update the configuration data structure. 
       - Modifying the configuration data structure directly could prove difficult to debug since the configuration values are not deterministic as the configuration inputs can change in an unexpected ways. 
       - Unconventional coding style for the Go language. 

3.  Redesign the ETCD client implementation of the cluster client interface. 

      Pros:
      - Allows the client implementation to be modernize with latest Go paradigms and address short comings discovered over the years. 

      Cons:
      - Riskiest approach due to ensuring backwards compatibility with pre-existing usage. 
      - If a version two of the ETCD client was created, that could lead to confusion among users.

**Comment by nerd0** [comment]
@schallert @mway any opinions?

**Comment by mway** [comment]
Sorry, this slipped through the cracks.

I'll set up some time for us to discuss; there are a handful of solutions here (several of which you called out), but I'd like to discuss the tradeoffs in a bit more detail.
