### ISSUE TITLE
Cold Flushes perform unnecessary merging and re-encoding

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1827]
The logic in `fs/persist/merger.go` currently always creates a `multiiterator` and uses that to perform cold flushes. This is unnecessarily wasteful because in a lot of situations there is only one stream of data (data existed on disk but there are no new data points for it in memory) but we have to decode and re-encode all the data anyways.

This logic could be greatly optimized to check if the number of data streams is equal to one, and if so, use that stream to write to disk directly instead of decoding/encoding. This would greatly increase performance for workloads where there are a large number of series (and potentially large amounts of data) but only a few series have out of order writes that need to be merged in.

**Comment by justinjc** [comment]
Resolved by #1829
