### ISSUE TITLE
Single node example doesn't work??

### ISSUE THREAD

**Issue by pbuxtonccuk** [m3db/m3#1828]
Hi,

Wanting to take a look at M3DB, so trying to run the single node example with docker.

The documentation points to using the example config, but the example config directed to use in the docs simply doesn't work.

I've not changed anything in the config - I (rather stupidly) expected it to just work??

What I actually get when trying to run the docker image is the error

unable to load config from /etc/m3dbnode.yml: yaml: line 619: mapping values are not allowed in this context.

Have I overlooked something?

Thanks
Paul

**Comment by richardartoul** [comment]
@pbuxtonccuk Could you include the exactly YAML you're using?

**Comment by minkangyang-tigergraph** [comment]
I met the same issue: https://github.com/m3db/m3/blob/master/src/dbnode/config/m3dbnode-local-etcd.yml
The exact YAML: (which is the one at this link: )

coordinator:
  listenAddress:
    type: "config"
    value: "0.0.0.0:7201"

  local:
    namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h

  logging:
    level: info

  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
    sanitization: prometheus
    samplingRate: 1.0
    extended: none

  limits:
    maxComputedDatapoints: 10000

  tagOptions:
    # Configuration setting for generating metric IDs from tags.
    idScheme: quoted

db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  hostID:
    resolver: config
    value: m3db_local

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    bootstrappers:
        - filesystem
        - commitlog
        - peers
        - uninitialized_topology
    commitlog:
      returnUnfulfilledForCorruptCommitLogFiles: false

  cache:
    series:
      policy: lru
    postingsList:
      size: 262144

  commitlog:
    flushMaxBytes: 524288
    flushEvery: 1s
    queue:
      calculationType: fixed
      size: 2097152

  fs:
    filePathPrefix: /var/lib/m3db

  config:
      service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
              - zone: embedded
                endpoints:
                    - 127.0.0.1:2379
      seedNodes:
          initialCluster:
              - hostID: m3db_local
                endpoint: http://127.0.0.1:2380

  # un-comment the lines below to enable Jaeger tracing. See https://www.jaegertracing.io/docs/1.9/getting-started/
  # for quick local setup (which this config will send data to).

  # tracing:
  #  backend: jaeger

**Comment by pbuxtonccuk** [comment]
HI all,  Sorry I was aw\y for a few days.

As indicated by MinKang, it is the example provided.

Thanks
Paul

**Comment by benraskin92** [comment]
Do you see any errors along the lines of:
```
unable to load config from /etc/m3dbnode/m3dbnode.yml: yaml: unmarshal errors:
  line 12: field logging not found in type config.Configuration
```

**Comment by marknl** [comment]
> Do you see any errors along the lines of:
> 
> ```
> unable to load config from /etc/m3dbnode/m3dbnode.yml: yaml: unmarshal errors:
>   line 12: field logging not found in type config.Configuration
> ```

Yes. This is the error I'm seeing.

**Comment by mcheepati** [comment]
Any update

**Comment by ChrisChinchilla** [comment]
Hey @pbuxtonccuk @mcheepati etc… I am now taking care of docs for M3, will be getting a lot of things overhauled. I've run through that tutorial a few times, and while it certainly needs an overhaul (in progress), the code works for me. That configuration file is part of the Docker image and the container uses it automatically.

I don't see that error anymore, so I assume there was something else fixed at some point, but id you have time, I'd love if you tried and let me know. Thanks!
