### ISSUE TITLE
Outstanding Background Repairs Work

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1848]
- [ ] Implement an "aggregate" checksum for each Namespace/shard/block so that comparisons can begin with a single checksum comparison and if the nodes have the exact same data can skip a detailed comparison.
- [ ] Handle tags / Index
- [ ] Persist the repair state across dbnode restarts (ideally via etcd)
- [ ] Breakup repair scheduling logic by `namespace/shard/blockStart` instead of just `namespace/blockStart`
- [x] Improve scheduling logic to avoid poison shards (basically shards that cannot be progressed past)
- [x] Prevent a single node down from blocking background repairs
- [x] Implement throttling to prevent too much repaired data from being loaded into memory at once
- [ ] Improve object pooling (`NewReplicaSeriesMetadata` has an internal map)

**Comment by justinjc** [comment]
@richardartoul wondering if you have further context on:
>poison shards (basically shards that cannot be progressed past)
What about the shards or the repair process make them unable to progress past from a repair perspective?

**Comment by richardartoul** [comment]
@justinjc I think that was just a basic sanity thing I thought would be nice if there was something wrong with any given shard. For example if there was something wrong with a single (or small number of shards) like two hosts were down I think the current implementation will get "blocked" until that issue is resolved
