### ISSUE TITLE
[docs] Some pages are "not found" on docs.m3db.io

### ISSUE THREAD

**Issue by jhedev** [m3db/m3#1861]
Some pages on docs.m3db.io are not found while the actual document can be found in the repo here. For example,

* https://docs.m3db.io/m3db/architecture/ (and all sub pages such as https://docs.m3db.io/m3db/architecture/engine/)
* https://docs.m3db.io/operational_guide/availability_consistency_durability/

and a few others

**Comment by richardartoul** [comment]
I believe @justinjc is fixing this

**Comment by martin-mao** [comment]
Seems like an intermittent issue with Netlify @justinjc? Is there some ticket open with them?

I think if you just refresh the doc pages enough, they load in the meantime.

**Comment by justinjc** [comment]
Yeah we've been in contact with Netlify to sort this out. In the meantime, you can replace https://docs.m3db.io/ with https://m3db.github.io/m3/ and everything should work just fine.

**Comment by jhedev** [comment]
Seems to be fixed by now. Thanks!
