### ISSUE TITLE
Add metrics to enable "node down" alert

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1863]
Currently its difficult to monitor if any M3DB nodes are down without writing weird queries or relying on write/read failures.

We can improve this by modifying the M3DB host queues (which are already health checking each other) to emit metrics indicating whether or not B node is reachable from A node. In addition, we can modify the M3DB health check to return whether or not the node is bootstrapping any shards which it should be available for.

The combination of these two metrics would allow us to detect both:

1. When any node is hard down
2. When any node is doing its initial post-restart bootstrap

These metrics would also prevent topology changes from triggering alerts.

**Comment by richardartoul** [comment]
@vdarulis

**Comment by vdarulis** [comment]
> Currently its difficult to monitor if any M3DB nodes are down without writing weird queries or relying on write/read failures.

I'd argue it's impossible to do so if you have any operations (adds, removals) ongoing when a node you're not directly operating on goes wonky/is completely down, since the entire cluster is bootstraping...something.

**Comment by abliqo** [comment]
@richardartoul, does https://github.com/m3db/m3/pull/2588 cover your use case?
