### ISSUE TITLE
Kubernetes Deployment Example Config Map invalid (unmarshal)

### ISSUE THREAD

**Issue by Cnidarias** [m3db/m3#1867]
It seems that the provided config-map.yaml is not valid.

https://github.com/m3db/m3/blob/master/kube/m3dbnode-configmap.yaml#L17 

The parser does not seem to like the logging flag in this section and fails.

Removing the logging section alleviates the problem

**Comment by marknl** [comment]
I've had the same issue when running it in a docker container. Pulling the latest version (0.11.0 at that time) fixed the issue for me.
