### ISSUE TITLE
vm.swappiness error in case of no swap

### ISSUE THREAD

**Issue by anandsinghkunwar** [m3db/m3#1908]
From what I understand, `vm.swappiness` should not have any effect on the system if there is no swap. We run a kubernetes environment which does not have any swap. 

I believe M3DB should not thow any warning in this case, however I see warnings like the following:
```
current value for vm.swappiness(60) is above recommended threshold(1)
```

Can we not warn on these in case swap is not present?

**Comment by martin-mao** [comment]
@benraskin92 ^
