### ISSUE TITLE
Coordinator mirroring feature

### ISSUE THREAD

**Issue by murphyzlaw** [m3db/m3#1910]
We would like a feature in the coordinator which can take all incoming data arriving from remote write, and stream it to a destination such as a Kafka topic. The data can be retained in its protobuf serialized form. This would allow processing on the destination end, e.g. sending to another local coordinator for DR; or exporting to an outside system for archival. From discussion, the data could simply be handed off after normal coordinator processing, from within the HTTP duty loop.
(Per discussion with @robskillington Aug 22)

**Comment by robskillington** [comment]
Hey so we added this and also followed up with an integration test with #1940.  I'll cut a release then close this issue.

**Comment by robskillington** [comment]
This was released with v0.13.0, let us know how it works.
