### ISSUE TITLE
How to set up the cluster by hand

### ISSUE THREAD

**Issue by kengan** [m3db/m3#1920]
I have read the following document and want to set up a 3 nodes cluster.
https://github.com/m3db/m3/blob/master/docs/how_to/cluster_hard_way.md
My node config file m3dbnode.yaml  is as following:

coordinator:
  listenAddress:
    type: "config"
    value: "0.0.0.0:7201"

  local:
    namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h

  logging:
    level: info

  metrics:
    scope:
      prefix: "coordinator"
    prometheus:
      handlerPath: /metrics
      listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
    sanitization: prometheus
    samplingRate: 1.0
    extended: none

  tagOptions:
    # Configuration setting for generating metric IDs from tags.
    idScheme: quoted

db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  hostID:
    resolver: hostname

  config:
    service:
      env: default_env
      zone: embedded
      service: m3db
      cacheDir: /data1/m3db/data
      etcdClusters:
        - zone: embedded
          endpoints:
            - 192.168.0.1:2379
            - 192.168.0.2:2379
            - 192.168.0.3:2379
    seedNodes:
      initialCluster:
        - hostID: m3_01
          endpoint: http://192.168.0.1:2380
        - hostID: m3_02
          endpoint: http://192.168.0.2:2380
        - hostID: m3_03
          endpoint: http://192.168.0.3:2380

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    bootstrappers:
        - filesystem
        - commitlog
        - peers
        - uninitialized_topology
    commitlog:
      returnUnfulfilledForCorruptCommitLogFiles: false

  cache:
    series:
      policy: lru
    postingsList:
      size: 262144

  commitlog:
    flushMaxBytes: 524288
    flushEvery: 1s
    queue:
      calculationType: fixed
      size: 2097152

  fs:
    filePathPrefix: /data1/m3db/data

-----------------------------------------------------------
On each node I have set the /etc/hosts file as following
192.168.0.1  m3_01
192.168.0.2  m3_02
192.168.0.3  m3_03
-------------------------------------------------------------
I run each node by following command:
./m3dbnode  -f m3dbnode.yaml
Everything is OK. And then I run 
curl -X POST http://localhost:7201/api/v1/database/create -d '{
.......

I can get the return result 
{"level":"info","ts":1567415274.5532737,"msg":"successfully updated topology","numHosts":3}
-------------------------------------------------------------------------------------------------

Then when I run the example about  "Test it out"
I get following error:

{"error":{"message":"Error({Type:INTERNAL_ERROR Message:failed to meet consistency level majority with 0/3 success, 3 nodes responded, errors: [error writing to host m3_02: connection pool has no connections error writing to host m3_03: connection pool has no connections error writing to host m3_01: connection pool has no connections]})","data":{"type":"INTERNAL_ERROR","message":"failed to meet consistency level majority with 0/3 success, 3 nodes responded, errors: [error writing to host m3_02: connection pool has no connections error writing to host m3_03: connection pool has no connections error writing to host m3_01: connection pool has no connections]"}}}

Can you tell my how to solve this problem . Thank you .

**Comment by foamdino** [comment]
I'm seeing the same behaviour when rolling a cluster via ansible with 0.12.0

**Comment by xkfen** [comment]
same problem, i'm using cluster v0.14.2
my placement:
`{"placement":{"instances":{"1":{"id":"1","isolationGroup":"us-east-1","zone":"embedded","weight":100,"endpoint":"10.10.13.28:30011","shards":[{"id":0,"state":"INITIALIZING","sourceId":"","cutoverNanos":"0","cutoffNanos":"0"},{"id":1,"state":"INITIALIZING","sourceId":"","cutoverNanos":"0","cutoffNanos":"0"},{"id":2,"state":"INITIALIZING","sourceId":"","cutoverNanos":"0","cutoffNanos":"0"}],"shardSetId":0,"hostname":"ceph-node1.ha.env.lab.io","port":30011}},"replicaFactor":1,"numShards":3,"isSharded":true,"cutoverTime":"0","isMirrored":false,"maxShardSetId":0},"version":1}`

the m3db log shows the flowing errors:
`{"level":"error","ts":1582009547.6539202,"msg":"write error","remoteAddr":"10.40.128.0:52486","httpResponseStatusCode":500,"numRegularErrors":14,"numBadRequestErrors":0,"lastRegularError":"failed to meet consistency level majority with 0/1 success, 1 nodes responded, errors: [error writing to host 1: connection pool has no connections]","lastBadRequestErr":""}`

how to solve this, thanks.
