### ISSUE TITLE
"context canceled" error mis-categorized

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#1933]
Using m3coordinator v0.10.2

We had a prometheus remote writing to m3coordinator and there was a network issue that took the prometheus offline. M3coordinator logged errors that looked like:
`{"level":"error","ts":1567802759.0561562,"msg":"write error","remoteAddr":"x.x.x.x:port","httpResponseStatusCode":500,"numRegularErrors":1,"numBadRequestErrors":0,"lastRegularError":"context canceled","lastBadRequestErr":""}`
and recorded an increase in `coordinator_write_errors{code="5XX"}`

I feel like this issue should probably not be a 5xx, and should maybe be either no code, or 4xx since it's a client error instead of a server error.

Not sure if I can reproduce the underlying issue.

**Comment by robskillington** [comment]
Hey @BertHartm this makes sense.  Let us see how hard it would be to propagate a client error here.   We need to be able to reliably tell why the context was cancelled and correlate that to a client network read error.

I wonder where this context is actually being checked that bubbles the error.  Maybe we should try reproducing this and digging in further first.

**Comment by Betula-L** [comment]
+1

In my situation, M3coordinator reach its capacity, there are hundreds of errors as below,
```
{"level":"error","ts":1570620777.2541175,"msg":"write error","remoteAddr":"x.x.x.x:port","httpResponseStatusCode":500,"numRegularErrors":1358,"numBadRequestErrors":0,"lastRegularError":"context canceled","lastBadRequestErr":""}
```

**Comment by Betula-L** [comment]
**How to reproduce it**
1. Set prometheus remote write timeout as 1s, so query context will be cancel if m3db storage write time was over 1s.
**What is expected**
1. more detailed error message
2. httpResponseStatusCode is 400 rather than 500
