### ISSUE TITLE
M3coordinator memory spike

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#1944]
We're running m3coordinator stateless and load balanced to accept prometheus remote writes. Over the last few days, we went from normal memory levels to maxing out our boxes in a coordinated fashion.
cpu and memory for a 2 day window on 2 coordinators:
![image](https://user-images.githubusercontent.com/508811/64984392-c3993a00-d890-11e9-8c5e-fa0874571fdc.png)

The coordinators have been up and accepting traffic for more than a month, and traffic patterns didn't change significantly (that I can find). Some coordinators did OOM and restart fine, and others are still running with high memory

## Performance issues

If the issue is performance related, please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the performance issue? (M3Coordinator, M3DB, M3Aggregator, etc)
- M3Coordinator
version: build_version="v0_10_2",endpoint="m3coordinator",go_version="go1_12_6",revision="cdadb29a"
commit that was built: https://github.com/m3db/m3/commit/cdadb29a
2. Approximately how many datapoints per second is the service handling?
- about 270k (post RF=3) across 30 coordinators
3. What is the approximate series cardinality that the series is handling in a given time window? I.E How many unique time series are being measured?
- `Ticking` is around 8M
4. What is the hardware configuration (number CPU cores, amount of RAM, disk size and types, etc) that the service is running on? Is the service the only process running on the host or is it colocated with other software?
- 8 Core / 56GB dedicated
5. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
- 1 unaggregated namespace, 1 m3 cluster, nothing weird.
6. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
- remote writes from prometheus

In addition to the above information, CPU and heap profiles are always greatly appreciated.

#### M3Coordinator

included for 2 boxes which haven't OOM'd yet

[coord_mem_pprof.tar.gz](https://github.com/m3db/m3/files/3617904/coord_mem_pprof.tar.gz)

### M3DB Grafana Dashboard Screenshots
DB metrics:
![image](https://user-images.githubusercontent.com/508811/64987516-589f3180-d897-11e9-9402-b434b20697e7.png)
(the rest of the dashboard didn't look interesting) I'm not sure why the new series inserts went weird simultaneously. It could be an effect since our remote write times started maxing out at 10s and so we went into retry loops.

Coordinator Metrics:
![image](https://user-images.githubusercontent.com/508811/64987708-c77c8a80-d897-11e9-82e8-c5724fba78e3.png)

**Comment by BertHartm** [comment]
This may end up being an effect of some data we're pumping in, and I'm trying to track that down as well. One interesting effect to me is that memory never dropped back down once whatever issue there was resolved (it's been over 24 hours now).

**Comment by martin-mao** [comment]
Interesting that memory didn't go down, but it looks like it was caused by introduction of a bunch of new series (M3DB inserting a few thousand per second). Each new series requires a new entry in the coordinator and hence more memory usage.

We will look into why it didn't drop afterwards though - we haven't seen that before. @robskillington FYI ^
