### ISSUE TITLE
Add a KV api to the coordinator for runtime config changes

### ISSUE THREAD

**Issue by schallert** [m3db/m3#1959]
We need to be able to change KV values in etcd, such as m3db bootstrap config. This is currently done by putting protobuf-serialized bytes into etcd. We should support an API for doing this from the coordinator.

**Comment by obitech** [comment]
I created a design doc for this patch: https://docs.google.com/document/d/1xNk3c-XEA-ZBOmS6kdoZavlb1G9NZBpYa0l6ls7JaDI/edit?usp=sharing

**Comment by schallert** [comment]
Just left a comment on the doc. Thanks for taking a stab at this @obitech!

**Comment by xmcqueen** [comment]
The design doc has this in the dbnode.  I see this ticket is tagged with coordinator.  I'm thinking the coordinator is a safer place for it.

Is anybody working on this?  I'm thinking of getting this going so I can add some more to the m3ctl cli tool. I want to get rid of this stuff:

`echo -n "ChF1bnN0cmljdF9tYWpvcml0eQ==" | base64 -d | ETCDCTL_API=3 etcdctl put _kv/kube-monitoring/persistent-cluster/m3db.client.bootstrap-consistency-level`

**Comment by obitech** [comment]
Hey @xmcqueen I started a little work on this but am currently unable to contribute a lot because of life. Feel free to take this issue 🙂
