### ISSUE TITLE
How to solve the problem about  BAD_REQUEST Message:datapoint too far in past

### ISSUE THREAD

**Issue by kengan** [m3db/m3#1990]
I use m3db to save the data from prometheus. For some reason, m3db was down  at 7 days ago.
Today I restart the m3db and get the error:
BAD_REQUEST Message:datapoint too far in past which is output by m3  coordinator. Can you tell me how to solve this problem . Thank you

**Comment by Betula-L** [comment]
+1 

In addition, restart m3db do not solve that.

**Comment by ocarino** [comment]
+1

3-node m3db setting, all nodes were rebooted during CentOS updates. Help would be appreciated.

**Comment by arnikola** [comment]
Hey sorry we've let the issues backlog get a bit out of hand!

Would you mind sharing your namespace configs? We've often seen this message arising from improperly set up `bufferPast` values

**Comment by rayjcwu** [comment]
+1 

I saw the same error as well, it shows off_by > 50 mins.
here is my namespace configuration.

```
GET /api/v1/services/m3db/namespace
{
  "registry": {
    "namespaces": {
      "metrics": {
        "bootstrapEnabled": true,
        "flushEnabled": true,
        "writesToCommitLog": true,
        "cleanupEnabled": true,
        "repairEnabled": false,
        "retentionOptions": {
          "retentionPeriodNanos": "604800000000000",
          "blockSizeNanos": "7200000000000",
          "bufferFutureNanos": "120000000000",
          "bufferPastNanos": "600000000000",
          "blockDataExpiry": true,
          "blockDataExpiryAfterNotAccessPeriodNanos": "300000000000",
          "futureRetentionPeriodNanos": "0"
        },
        "snapshotEnabled": true,
        "indexOptions": {
          "enabled": true,
          "blockSizeNanos": "7200000000000"
        },
        "schemaOptions": null,
        "coldWritesEnabled": false
      }
    }
  }
}
```

**Comment by SQUIDwarrior** [comment]
I am also seeing this using the m3db-operator "preset" namespaces.

**Comment by pickfire** [comment]
@gibbscullen Is this fixed?

**Comment by lcanon** [comment]
@kengan how you fixed it?
