### ISSUE TITLE
Why m3db node  OOM

### ISSUE THREAD

**Issue by kengan** [m3db/m3#1992]
I setup m3db cluster on three  machince, each machine has 32G memory, each node I had set up m3db and etcd ， m3db call etcd with external url. I found the m3db use 95% memory and the system auto kill the m3db because out of memory.
I want to know for m3db node, how many memory it need? Thank you.

**Comment by jakubgs** [comment]
Same here, my node is running out of memory when bootstrapping:
```
{"level":"info","ts":1586947566.7714722,"msg":"bootstrap prepare"}
{"level":"info","ts":1586947750.7460046,"msg":"bootstrap started","numShards":64}
{"level":"info","ts":1586947753.0344174,"msg":"bootstrap range starting","bootstrapper":"base","namespace":"default","numShards":64,"dataFrom":1576540800,"dataTo":1586908800,"dataRange":10368000,"indexFrom":1576540800,"indexTo":1586908800,"indexRange":10368000}
{"level":"info","ts":1586947753.0363436,"msg":"bootstrap from source requested","bootstrapper":"filesystem","namespace":"default","numShards":64,"dataRange":10368000,"dataFrom":1576540800,"dataTo":1586908800,"indexRange":10368000,"indexFrom":1576540800,"indexTo":1586908800}
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x1f4da28, 0x16)
        /usr/local/go/src/runtime/panic.go:617 +0x72
```
What am I supposed to do with this?

**Comment by jakubgs** [comment]
Any reason why this was closed? If there's a minimum memory requirement for bootstrapping maybe it should be documented?

**Comment by gibbscullen** [comment]
Re-opening to ensure this gets captured in updated M3 documentation. @ChrisChinchilla
