### ISSUE TITLE
Optimize add/delete node api

### ISSUE THREAD

**Issue by Betula-L** [m3db/m3#1996]
**What is wrong?**
Currently, if user added a broken node to placement, then cluster is hard to fix up. I can not do anything to fix this condition if just by m3db api.

For example, 
1. add a broken node
```
curl -X POST localhost:7201/api/v1/services/m3db/placement -d '{
  "instances": [
        {
            "id": "broken-node",
            "isolationGroup": "a",
            "zone": "embedded",
            "weight": 100,
            "endpoint": "x.x.x.x:9000",
            "hostname": "broken-node",
            "port": 9000
        }
  ]
}'
```
2. i find `broken-node` can not be available, and wanna remove this `broken-node`, everything is stuck.
```
{"error":"instances [available-node-1,available-node-2,available-node-3,broken-node] do not have all shards available"}
```

Furthermore, there is no health check before executing `add node` actually.

**Comment by shasha047** [comment]
i'm facing the same issue, have you found any solution ?

**Comment by wang1219** [comment]
+1
