### ISSUE TITLE
-bash: ./m3dbnode: /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory

### ISSUE THREAD

**Issue by yangxiangyu** [m3db/m3#2003]
run version 0.14.0 on RHEL results in message 
-bash: ./m3dbnode: /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory

OS info:
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core)

**Comment by schallert** [comment]
Hey, thanks for the report @yangxiangyu. We're looking at cutting a new release linked against glibc rather than musl.

**Comment by schallert** [comment]
Turns out we just had to ensure cgo was disabled in our release process just as it is in our make targets :)
