### ISSUE TITLE
m3query doesn't filter labels properly using the != operator

### ISSUE THREAD

**Issue by pavelnikolov** [m3db/m3#2008]
M3Query fails to filter our results when using the not equal operator with labels (i.e. `!=` )
The query below:
```
sum(up{some_label!=""}) by (job)
```
works fine in Prometheus but consistently fails in M3Query...
Just a little bit more context - the `some_label` only exists on some of our metrics. M3Query returns every single target (i.e. `up` series) from M3DB instead of just returning the targets that contain the specified label.

1. What service is experiencing the issue?
**M3Query**

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary). 
**n/a**

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
**Prometheus -> M3Coordinator -> M3DB, then M3Query reads from M3DB**

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
**I'd be happy to jump on a call and demonstrate this. I haven't had the time to build an example or to write a unit test that fails.**

**Comment by robskillington** [comment]
Interesting, I think this will actually be fixed when this PR is merged:
https://github.com/m3db/m3/pull/1986

cc @arnikola

**Comment by pavelnikolov** [comment]
Yes, it's resolved
