### ISSUE TITLE
Explanation of nouns in m3

### ISSUE THREAD

**Issue by ophlr** [m3db/m3#2042]
I`m new to use M3, so during my use of m3, I have a lot of names that don't know the specific meaning, for example, tag, placement, namespace, datapoint... So I hope that the documentation can update some chapters on the interpretation of these terms.

**Comment by benraskin92** [comment]
Working on this PR to add a glossary: https://github.com/m3db/m3/pull/2077

**Comment by benraskin92** [comment]
Closing this out.
