### ISSUE TITLE
start_m3.sh fails to start complaining about DS_PROMETHEUS 

### ISSUE THREAD

**Issue by xmcqueen** [m3db/m3#2054]
# Filing M3 Issues

## General Issues

General issues are any non-performance related issues (data integrity, ease of use, error messages, configuration, documentation, etc).

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)

startup script for devel setup. i can send in a PR if its appropriate. diff is shown below.

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).

for some reason I had to edit the Dockerfile for the grafana like this:

remove the variable interpolation syntax around DS_PROMETHEUS in the grafana Dockerfile

```
[xxx m3_stack]$ git diff
diff --git a/docker/grafana/Dockerfile b/docker/grafana/Dockerfile
index e454d5456..8b579ccec 100644
--- a/docker/grafana/Dockerfile
+++ b/docker/grafana/Dockerfile
@@ -13,5 +13,6 @@ COPY ./integrations/grafana/temporal_function_comparison.json /tmp/grafana_dashb
 # JustWorksTM. Use a temporary directory to host the dashboards since the default
 # directory is owned by root.
 COPY ./integrations/grafana/m3db_overlaid_dashboard.json /tmp/m3db_overlaid_dashboard.json
-RUN awk '{gsub(/\${DS_PROMETHEUS}/,"Prometheus");print}' /tmp/m3db_overlaid_dashboard.json \
-  | awk '{gsub(/\${DS_M3QUERY}/,"M3Query - Prometheus");print}' > /tmp/grafana_dashboards/m3db_overlaid_dashboard.json
+RUN grep DS_PROMETHEUS /tmp/m3db_overlaid_dashboard.json
+RUN awk '{gsub(/DS_PROMETHEUS/,"Prometheus");print}' /tmp/m3db_overlaid_dashboard.json \
+  | awk '{gsub(/DS_M3QUERY/,"M3Query - Prometheus");print}' > /tmp/grafana_dashboards/m3db_overlaid_dashboard.json
[xxx m3_stack]$ 

```
3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.

on linux RH7 from head of latest:
```
commit a64a80f37b4b997ceebfb5135db8cf3bbb449b49 (HEAD -> master, origin/master, origin/HEAD)
Author: Rob Skillington <rob.skillington@gmail.com>
Date:   Sat Nov 23 09:32:58 2019 -0800

```

## Performance issues

If the issue is performance related, please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the performance issue? (M3Coordinator, M3DB, M3Aggregator, etc)
2. Approximately how many datapoints per second is the service handling?
3. What is the approximate series cardinality that the series is handling in a given time window? I.E How many unique time series are being measured?
4. What is the hardware configuration (number CPU cores, amount of RAM, disk size and types, etc) that the service is running on? Is the service the only process running on the host or is it colocated with other software?
5. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
6. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?

In addition to the above information, CPU and heap profiles are always greatly appreciated.

### CPU / Heap Profiles

CPU and heap profiles are critical to helping us debug performance issues. All our services run with the [net/http/pprof](https://golang.org/pkg/net/http/pprof/) server enabled by default.

Instructions for obtaining CPU / heap profiles for various services are below, please attach these profiles to the issue whenever possible.

#### M3Coordinator

CPU
`curl <HOST_NAME>:<PORT(default 7201)>/debug/pprof/profile?seconds=5 > m3coord_cpu.out`

Heap
`curl <HOST_NAME>:<PORT(default 7201)>/debug/pprof/heap > m3coord_heap.out`

#### M3DB

CPU
`curl <HOST_NAME>:<PORT(default 9004)>/debug/pprof/profile?seconds=5 > m3db_cpu.out`

Heap
`curl <HOST_NAME>:<PORT(default 9004)>/debug/pprof/heap -> m3db_heap.out`

### M3DB Grafana Dashboard Screenshots

If the service experiencing performance issues is M3DB and you're monitoring it using Prometheus, any screenshots you could provide using [this](https://grafana.com/dashboards/8126) dashboard would be helpful.

**Comment by arnikola** [comment]
I've seen this too; will investigate

**Comment by arnikola** [comment]
If you'd like to put up the PR I can approve @xmcqueen

**Comment by xmcqueen** [comment]
PR is up here: https://github.com/m3db/m3/pull/2069
