### ISSUE TITLE
System requirements for M3DB cluster

### ISSUE THREAD

**Issue by uzhinskiy** [m3db/m3#2067]
Hi.

Please help me to calculate CPU/MEM/Storage requirements for M3DB cluster.
We have a Prometheus with a load of 3k metrics  per second  and we need a HA decision for long-term storage (approx 1 year retention).

I plan to start with a 3 nodes in cluster and want to know a recomended system requirements to solve this.

Thank you

**Comment by arnikola** [comment]
Would you mind adding additional details about your requirements, especially around cardinality and desired resolutions? It may be easier to hop on our slack (http://bit.ly/m3slack) and ask there for a bit more visibility
