### ISSUE TITLE
m3coordinator requires unaggregated namespace

### ISSUE THREAD

**Issue by mmedvede** [m3db/m3#2076]
As of v0.14.2, m3coordinator requires at least one unaggregated namespace to run.

It may be a problem, especially if we use remote aggregation, i.e. we do not want to write any unaggregated metrics to m3db. In that setup having unaggregated namespace means that coordinators would still consume resources forwarding unaggregated metrics to m3db, and m3db would also have an additional namespace to maintain.

There should be a way to run coordinators without requiring it to have an unaggregated namespace.

**Comment by mmedvede** [comment]
I think the linked PR is still open. Did this get addressed elsewhere?

**Comment by gibbscullen** [comment]
Re-opening as linked PR is still open.

**Comment by gibbscullen** [comment]
Closing as PR is now closed.
