### ISSUE TITLE
Panic: SIGSEGV Invalid memory address writing to commitlog

### ISSUE THREAD

**Issue by aravindvs** [m3db/m3#2162]
## General Issues

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)
**M3DB** (running 0.14.2)
2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
* Nine node cluster spread across 3 isolation groups
* One namespace with blocksize 3h 
3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
* Writes through prometheus
4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
* No

Things were just going fine but suddenly at saw SIGSEGV on a couple of DB nodes on 2 different isolation groups ~ at the same time (just one second apart).. Interestingly this was off-peak so the throughput was low. Also resident memory was just at 40% and disk util was at ~30% too (so not alarming at all).

And there were no logs prior to this as well (error/info).

This is the stack trace:

```
textPayload: "panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xeae5d3]

goroutine 13801 [running]:
github.com/m3db/m3/src/dbnode/persist/fs/commitlog.(*writer).Write(0xc0ee9e96c0, 0xbb176f7, 0x1f8d8e0, 0xc0eee3d980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/m3db/m3/src/dbnode/persist/fs/commitlog/writer.go:230 +0x483
github.com/m3db/m3/src/dbnode/persist/fs/commitlog.(*commitLog).write(0xc00000b2c0)
	/go/src/github.com/m3db/m3/src/dbnode/persist/fs/commitlog/commit_log.go:533 +0x408
created by github.com/m3db/m3/src/dbnode/persist/fs/commitlog.(*commitLog).Open
	/go/src/github.com/m3db/m3/src/dbnode/persist/fs/commitlog/commit_log.go:320 +0x14f

```

**Comment by gibbscullen** [comment]
Closing. If you still have this issue after upgrading to M3 v0.15, feel free to re-open the issue. We have not seen this issue in the 0.15 release.
