### ISSUE TITLE
An aggregate namespace who write data to it

### ISSUE THREAD

**Issue by ning1875** [m3db/m3#2194]
here is my usage ：promethues  remote write to m3coordinator  then write to m3dbnode 。And my question is that : Is it written to m3db after m3coordinator aggregation, or is it aggregated by m3db itself?

**Comment by arnikola** [comment]
It is aggregated in m3coordinator, and sent to aggregated namespaces in the dbnode

**Comment by ning1875** [comment]
> It is aggregated in m3coordinator, and sent to aggregated namespaces in the dbnode
ok,get .


I have been looking at the code of m3coordinator recently, some places are not very understandable。
      - namespace: metrics
        type: aggregated
        retention: 720h
        resolution: 5m
If an aggregated namespace is specified in the configuration file like above. Does m3coordinator write all the aggregated results to m3dbnode, such as avg, last, max, min, or just write last? if all agg result has been written to dbnode ,how to query max ,min by query ? add a method tag like agg_type="max" ?
here 
https://github.com/m3db/m3/blob/07e7df8ae65101a585308d3896acc37508ecb67b/src/aggregator/aggregator/gauge_elem_gen.go#L210
consumeLocalMetric -->consum  -->processValueWithAggregationLock
then finally call this to write to dbnode 
https://github.com/m3db/m3/blob/07e7df8ae65101a585308d3896acc37508ecb67b/src/cmd/services/m3coordinator/downsample/flush_handler.go#L174


https://github.com/m3db/m3/blob/07e7df8ae65101a585308d3896acc37508ecb67b/src/aggregator/aggregator/gauge_elem_gen.go#L403

**Comment by robskillington** [comment]
Hey @ning1875 apologies for getting back to you late.

So right now by default the aggregation is always "last" value, you can use mapping rules to choose different aggregations:
https://docs.m3db.io/operational_guide/mapping_rollup/

This PR will then allow for adding tags per mapping rule so you can differentiate them as you need:
https://github.com/m3db/m3/pull/2414
