### ISSUE TITLE
not able to build m3database

### ISSUE THREAD

**Issue by tejasbhosale009** [m3db/m3#2204]
Getting this error 

make m3dbnode
mkdir -p /home/users/tejas/go/src/github.com/m3db/m3/bin
Building m3dbnode
[ -d /home/users/tejas/go/src/github.com/m3db/m3/vendor ] || make install-vendor-m3
make[1]: Entering directory '/home/users/tejas/go/src/github.com/m3db/m3'
[ -d /home/users/tejas/go/src/github.com/m3db/m3/vendor ] || make install-vendor
make[2]: Entering directory '/home/users/tejas/go/src/github.com/m3db/m3'
package github.com/Masterminds/glide
        imports github.com/Masterminds/vcs
        imports github.com/mitchellh/go-homedir
        imports github.com/Masterminds/semver
        imports gopkg.in/yaml.v2
        imports github.com/codegangsta/cli
        imports context: unrecognized import path "context"
package github.com/Masterminds/glide
        imports github.com/Masterminds/vcs
        imports github.com/mitchellh/go-homedir
        imports github.com/Masterminds/semver
        imports gopkg.in/yaml.v2
        imports github.com/codegangsta/cli
        imports github.com/cpuguy83/go-md2man/v2/md2man
        imports github.com/cpuguy83/go-md2man/v2/md2man
        imports github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
        /usr/lib/go/src/pkg/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
        /home/users/tejas/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
.ci/common.mk:29: recipe for target 'install-glide' failed
make[2]: *** [install-glide] Error 1
make[2]: Leaving directory '/home/users/tejas/go/src/github.com/m3db/m3'
Makefile:104: recipe for target 'install-vendor-m3' failed
make[1]: *** [install-vendor-m3] Error 2
make[1]: Leaving directory '/home/users/tejas/go/src/github.com/m3db/m3'
Makefile:160: recipe for target 'm3dbnode' failed
make: *** [m3dbnode] Error 2

Can any one please help how to fix this ..

**Comment by arnikola** [comment]
You may need to run `glide install` in your `/m3` directory

**Comment by tejasbhosale009** [comment]
make install-glide
package context: unrecognized import path "context"
package github.com/cpuguy83/go-md2man/v2/md2man
        imports github.com/cpuguy83/go-md2man/v2/md2man
        imports github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
        /usr/lib/go/src/pkg/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
        /home/users/tejas/go/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
.ci/common.mk:29: recipe for target 'install-glide' failed
make: *** [install-glide] Error 1

**Comment by tejasbhosale009** [comment]
used executable files lastly
