### ISSUE TITLE
"make m3dbnode" command doesn't work

### ISSUE THREAD

**Issue by Skover** [m3db/m3#2208]
## Issue

I'm currently having an issue when running the `make m3dbnode` command.

I tried both on Debian Docker container and Ubuntu Vagrant VM, with different m3db releases, but I get the same error.

I have the go1.13.8 version which works. I run this command in my `/m3` repository (cloned from git), which is inside the `go` repository. I already ran `glide install`.

After cloning MichaelTJones/pcg, a new one is missing. It seems that dependencies are not automatically downloaded. I just want to get the binary file.

## Error

CGO_ENABLED=0 go build -ldflags '-X github.com/m3db/m3/src/x/instrument.Revision=351e12de6 -X github.com/m3db/m3/src/x/instrument.Branch=HEAD -X github.com/m3db/m3/src/x/instrument.Version=v0.14.1 -X github.com/m3db/m3/src/x/instrument.BuildDate=2020-03-12-14:58:18 -X github.com/m3db/m3/src/x/instrument.BuildTimeUnix=1584025098 -X github.com/m3db/m3/src/x/instrument.LogBuildInfoAtStartup=true' -o /usr/local/go/src/github.com/m3db/m3/bin/m3dbnode ./src/cmd/services/m3dbnode/main/.
build github.com/m3db/m3/src/cmd/services/m3dbnode/main: cannot load github.com/MichaelTJones/pcg: open /usr/local/go/src/github.com/MichaelTJones/pcg: no such file or directory
make: *** [Makefile:119: m3dbnode] Error 1

#### Thank you in advance for your help !

**Comment by gibbscullen** [comment]
Closing as this issue should be fixed with latest M3 V0.15 update. Let us know if you're still having issues with latest M3 version with Go Mod.
