### ISSUE TITLE
graphs via PromQL query on Grafana change a lot between refreshes

### ISSUE THREAD

**Issue by aravindvs** [m3db/m3#2214]
## General Issues

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)
M3Query (M3Coordinator) Version: 0.14.2

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
Default config. One namespace (unaggregated) - retention 90d

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
Prometheus scrapes (1 min scrape interval) and writes through M3Coordinator(s) and reads are performed via dedicated M3Query (M3Coordinator)

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
Write histogram metrics with ~30 buckets (slightly higher cardinality ~20000) and try to graph in Grafana via M3Query like this:
`
histogram_quantile(0.50, sum(rate(query_latency_ms_bucket{cluster_name="$Cluster", kubernetes_namespace="$Namespace"}[5m])) by (le, $groupby))
` 

The graphs will change every time we refresh. The same query performed via prometheus (remote read) doesn't do that so looks like something to do with M3Coordinators (also Visulaization on Grafana is set to "null value - null as connected"). Attaching screenshots and see the difference between 2 refreshes:

<img width="1667" alt="Screen Shot 2020-03-13 at 5 45 43 PM" src="https://user-images.githubusercontent.com/13004672/76776916-a15f7680-6764-11ea-873e-cc661697e795.png">
<img width="1670" alt="Screen Shot 2020-03-13 at 5 45 58 PM" src="https://user-images.githubusercontent.com/13004672/76776926-a3c1d080-6764-11ea-8033-23a6d6c71287.png">

**Comment by fingon** [comment]
This is occurring also in 0.15rc3 and even on relatively simple queries.

**Comment by arnikola** [comment]
Do you see the same flapping when running the query through a Prom remote read endpoint?

**Comment by aravindvs** [comment]
> Do you see the same flapping when running the query through a Prom remote read endpoint?

No.. I didn't notice it with prom remote read.. if I use M3Query directly that is when I saw this. And as the previous comment, seems to happen for a lot of queries like `sum(increase()` as well in addition to histogram.

**Comment by coelho** [comment]
We continue to have this issue @arnikola 
```
sum(irate(requests{code="total",host!="*"}[5s])) by (host)
```
The tags change order on every refresh. It does not occur if you query through Prometheus remote_read.
