### ISSUE TITLE
m3 prometheus mode does not support operators between scalar/scalar and scalar/vector 

### ISSUE THREAD

**Issue by yuecong** [m3db/m3#2227]
# Filing M3 Issues

## General Issues

General issues are any non-performance related issues (data integrity, ease of use, error messages, configuration, documentation, etc).

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue?
M3Coordinator
2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
N/A
3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
use M3 in peormetheus mode

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.

In Prometheus doc, it defines operators spec as [here](https://prometheus.io/docs/prometheus/latest/querying/operators/#binary-operators)
```
Binary arithmetic operators are defined between scalar/scalar, vector/scalar, and vector/vector value pairs.

```

But for m3, it only supports vector/vector value pairs. here is one simple example to reproduce this.

OK (?):
 `vector(time() * 2000) - vector(time() * 1000)`, but the result is not correct. it always shows 0
`vector(time() * 2000) -(time() * 1000)`, the result is not correct as well, but at least no error

NG:
with error of  `vector matching parameters must be provided for binary operations between series`
`time() * 2000 - time() * 1000`

**Comment by yuecong** [comment]
also another real example
`max(system_cpu{key='nr_cpus', kubernetes_pod_name=~'accounts-director.*'}` returns all 16, and it is a instant vector.

`(system_cpu{key='load_5m', kubernetes_pod_name=~'accounts-director.*'})` returns some vector

but `(system_cpu{key='load_5m', kubernetes_pod_name=~'accounts-director.*'}) / 16` works 
while

```
(system_cpu{key='load_5m', kubernetes_pod_name=~'accounts-director.*'}) / scalar(max(system_cpu{key='nr_cpus', kubernetes_pod_name=~'accounts-director.*'}))
```
does not work

**Comment by robskillington** [comment]
@yuecong thanks for the report, @arnikola is looking at this now.

**Comment by robskillington** [comment]
The default Prometheus engine handles this correctly now.

I'll put this into the backlog and we can track this as a pure non-default query engine fix with lower priority (since any and all users of M3 will use the standard Prometheus engine by default now).
