### ISSUE TITLE
tags change order on refresh

### ISSUE THREAD

**Issue by coelho** [m3db/m3#2253]
## General Issues

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)
M3Query (M3Coordinator) Version: v0.15.0-rc.4

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
Kubernetes via operator 1 namespace 2 second 48 hour retention

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
Prometheus scrapes

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
Any data should do

If you query the database with a group by query, the tags will be returned in a random order. 

For example:
```
max(test{type="node"}) by (name)
```

This causes issues on for ex. Grafana where graph refreshes change the order of the tags. Through Prometheus "remote_read", this does not happen.

**Comment by fingon** [comment]
Related links: 
- Prometheus not keen on adding function for ordering ( https://github.com/prometheus/prometheus/pull/1533 )
- Grafana not keen to fix ordering of Prometheus responses ( https://github.com/grafana/grafana/issues/13325 )

**Comment by gibbscullen** [comment]
Closing as this is fixed for default Prometheus query engine.
