### ISSUE TITLE
Missing `db_num_shards` or similar metric for alerting

### ISSUE THREAD

**Issue by mmedvede** [m3db/m3#2257]
We alert on `cluster_shards_available` being less than `numShards` specified in placement for that cluster. There is no easy way to get that value into an alert without hardcoding it in some way.

Edit: another placement value we hardcode for use in alerting is `replicaFactor`

**Comment by gibbscullen** [comment]
Thanks for the feedback! We are working on putting this into our upcoming sprint. Will keep you posted!

**Comment by robskillington** [comment]
We added both total cluster shards and the cluster replication factor as a metric emitted from each node now, hope this helps @mmedvede.
