### ISSUE TITLE
v0.15.0.rc3 db memory leak

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#2270]
There seems to be some sort of memory leak in 0.15.0.rc3. After about 3 weeks of running the DB, it was using about 150GB of ram, but restarting it let it drop to under 50GB:
![image](https://user-images.githubusercontent.com/508811/79499698-5b166500-7ff9-11ea-8ad6-0c28400fa67c.png)

## Performance issues

If the issue is performance related, please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the performance issue? (M3Coordinator, M3DB, M3Aggregator, etc)
M3DB
2. Approximately how many datapoints per second is the service handling?
About 20k (pre-replication), up to ~350k (pre-replication) in the last 24 hours. Note that the memory was already at 130GB before we turned on the load.
3. What is the approximate series cardinality that the series is handling in a given time window? I.E How many unique time series are being measured?
Have about 60M ticking, not a lot of churn
4. What is the hardware configuration (number CPU cores, amount of RAM, disk size and types, etc) that the service is running on? Is the service the only process running on the host or is it colocated with other software?
32 core, 256 GB, dedicated
5. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
2 namespaces configured for 21d retention, no aggregation.
6. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?

In addition to the above information, CPU and heap profiles are always greatly appreciated.

### CPU / Heap Profiles

I'm attaching a "low" heap (just restarted) and a "high" heap (a peer that has been running for a few weeks)

[m3db_high_heap.out.zip](https://github.com/m3db/m3/files/4489497/m3db_high_heap.out.zip)
[m3db_low_heap.out.zip](https://github.com/m3db/m3/files/4489498/m3db_low_heap.out.zip)

I think the issue is something in the AggregateValuesMap based on the heap:
![image](https://user-images.githubusercontent.com/508811/79501745-8cdcfb00-7ffc-11ea-9940-c7f7b253512d.png)

**Comment by robskillington** [comment]
👍 we're looking into this, thanks for sharing the heap @BertHartm
