### ISSUE TITLE
Coldwriting not working for non existing metrics

### ISSUE THREAD

**Issue by SUL-sj** [m3db/m3#2344]
I am aware, that this is an issue in an early stage for the feature of cold writing.

However we successfully configured and activated it in our setup and were observing the following issue:

A cold write of graphite data for a metric that is not yet in the database has no effect - the data will not be written to the m3db. Also there is no log entry for this behavior.

After submitting a value with current timestamp for the same metric and redoing the coldwriting performed before, the cold written data was written to m3db.

Maybe a log entry for the failed insert in the first place would be enough for now...

**Comment by gibbscullen** [comment]
Closing this issue as we do not currently have this on our roadmap.

**Comment by asafm** [comment]
@gibbscullen He describes the issue of reverse index not being updated during cold write. I understand that this something you currently work on to fix: 
https://github.com/m3db/m3/pull/1825
https://github.com/m3db/m3/pull/2039
https://github.com/m3db/m3/issues/1809
