### ISSUE TITLE
[Question] Querying by ID

### ISSUE THREAD

**Issue by MarcMagnin** [m3db/m3#2346]
Is it possible to query a namespace via a list of ids directly?
Also is there is a documentation on how to do a json query to use term query/conjunction queries?

Many thanks

**Comment by benraskin92** [comment]
If I understand your question, you can use m3query to query specified namespaces [through headers](https://m3db.github.io/m3/m3query/api/#header-params). As for docs on how to use term and conjunction queries, I'm not sure if we have those, but can look into adding them.

**Comment by gibbscullen** [comment]
Closing for now. We will be addressing this in updated documentation. Feel free to re-open if you have any further questions.
