### ISSUE TITLE
Error registering conflicting prom metrics during startup

### ISSUE THREAD

**Issue by mmedvede** [m3db/m3#2347]
I see a few `"msg":"register metric error","error":"a previously registered descriptor with the same fully-qualified name as Desc` show up during M3Coordinator, M3DB, and M3Aggregator startup.

Running `v0.15.0-rc.9`.

The metrics it complains about:

```
aggregator
 m3aggregator_aggregator_client_invalid_write counter
 m3aggregator_aggregator_election_manager_campaign_errors counter
 m3aggregator_aggregator_election_manager_resign_errors counter
 m3aggregator_aggregator_flush_handler_invalid_write counter
 m3aggregator_aggregator_flush_times_manager_flush_times_persist_errors counter
 m3aggregator_aggregator_flush_times_manager_flush_times_persist_errors_latency histogram
 m3aggregator_aggregator_flush_times_manager_flush_times_persist_success_latency histogram
 m3aggregator_aggregator_list_writer_errors counter

coordinator
 coordinator_downsampler_remote_aggregator_client_invalid_write counter
 coordinator_fetch_errors counter
 coordinator_fetch_success counter
 coordinator_fetch_success_latency summary
 coordinator_max_datapoints gauge

dbnode
 coordinator_fetch_errors counter
 coordinator_fetch_success counter
 coordinator_fetch_success_latency summary
 coordinator_max_datapoints gauge
```

Both coordinators and aggregators are using m3msg protocol.

Startup logs:

[m3aggr-start.log](https://github.com/m3db/m3/files/4652580/m3aggr-start.log)
[m3coord-start.log](https://github.com/m3db/m3/files/4652581/m3coord-start.log)
[m3dbnode-start.log](https://github.com/m3db/m3/files/4652582/m3dbnode-start.log)

**Comment by robskillington** [comment]
@linasm is going to take a look at this, thanks @mmedvede .

**Comment by linasm** [comment]
@mmedvede you should see an improvement with v0.15.2 (in `m3dbnode` and `m3coordinator`, but not in `m3coordinator` yet).

**Comment by linasm** [comment]
@mmedvede #2443 should fix all the metrics conflicts in the aggregator.
There is still `coordinator_downsampler_remote_aggregator_client_invalid_write` to be fixed in the coordinator.

**Comment by linasm** [comment]
Turns out I was wrong, but in a good way: I see that #2443 also fixed `coordinator_downsampler_remote_aggregator_client_invalid_write`.

**Comment by gibbscullen** [comment]
As an update, we are continuing to work on this.

**Comment by linasm** [comment]
Fixed via https://github.com/m3db/m3/pull/2406 and https://github.com/m3db/m3/pull/2443.
