### ISSUE TITLE
placement/set api syntax incorrect

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#2433]
While using the placement/set api, I noticed that the format in the documentation was wrong. Specifically, the nodes are documented as being an array, but that fails, and passing in an object works instead. Also, the "version" and "confirm" parameters are documented as part of placement, but appear to be top level objects instead.

This was tested on 0.15.0-rc.6

**Comment by BertHartm** [comment]
error message when passing instances as an array:
```
{"error":"json: cannot unmarshal array into Go value of type map[string]json.RawMessage"}
```

**Comment by robskillington** [comment]
Hey @BertHartm yes that's true it needs to be an object, like what comes back from the placement get response.

We'll get these docs updated.
