### ISSUE TITLE
placement/set api doesn't cause shard allocation

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#2434]
When using the placement/set api, and not passing in shards (as per the docs), the shards weren't reallocated, so the m3db nodes rejected the placement update. Passing through a shard allocation and setting is_sharded: true was the only way I found to proceed.

This was tested on 0.15.0-rc.6

**Comment by BertHartm** [comment]
error message from the node
```
Jun 30 11:51:39 dbnode-500173825-3-711227871 m3dbnode[66987]: {"level":"info","ts":1593517899.0451584,"msg":"successfully parsed placement","version":5}
Jun 30 11:51:39 dbnode-500173825-3-711227871 m3dbnode[66987]: {"level":"warn","ts":1593517899.0452871,"msg":"dynamic topology received invalid update","error":"shard is missing"}
```

**Comment by gibbscullen** [comment]
Thanks, Bert! We'll take a look at this and also update docs if need be.

**Comment by gibbscullen** [comment]
Closing issue; can re-open if still an issue.
