### ISSUE TITLE
Inaccurate peers bootstrap consistency

### ISSUE THREAD

**Issue by justinjc** [m3db/m3#2458]
**Scenario:**
* Environment:
  * Cluster with three nodes `A`, `B`, `C`
  * `RF3`
  * Bootstrap consistency `majority`
* Bootstrap the cluster to healthy state
* Bring `B` and `C` down
* Bring `B` back up

Here, I would expect `B` to fail to bootstrap again because only node `A` contains the data for when the other two nodes are down, which is not enough for `majority`.

This happens because the peers bootstrapper assumes that we'll be able to get data from peers here:
https://github.com/m3db/m3/blob/e48539a1764a7471e65d3bb4fb605cf775481110/src/dbnode/storage/bootstrap/bootstrapper/peers/source.go#L1039-L1042

And when actually fetching metadata (this happens when fetching blocks too), we count the bootstrapping node itself as a successful peer response:
https://github.com/m3db/m3/blob/e48539a1764a7471e65d3bb4fb605cf775481110/src/dbnode/client/session.go#L2209-L2211

This means that the database considers quorum to have been met since nodes `A` and `B` returned "successfully".

Here's a docker integration test modeling the above scenario, expecting the test to fail here:
https://github.com/m3db/m3/blob/c8a8a845a3f8043a221161696d658ffe184b4976/scripts/docker-integration-tests/peers_bootstrap/test.sh#L98-L99

**Comment by gibbscullen** [comment]
Hi Justin -- looking into this..

**Comment by robskillington** [comment]
Hey @justinjc I believe this is relevant perhaps:
https://github.com/m3db/m3/pull/1105

In the example you outlined, shouldn't B having merged data from a single other replica (i.e. replica A) actually count as majority quorum? (i.e. 2 of 3 nodes worth of data)

The place where this falls down is if you're adding a new node and it takes itself into account for consistency and then you're only getting one other node's worth of data (1 of 3 nodes worth of actual data).

**Comment by justinjc** [comment]
Caught up offline with @robskillington.

There is a slight assumption here that the write consistency level is set to `majority`. If the write consistency is set to anything lower, then the `majority` bootstrap consistency cannot be guaranteed (as described by the scenario in this issue). Given that it's rather strange to have this combination of majority consistency for bootstrapping, but a less strict consistency for writes, I'm going to close this issue.

We're actually good when adding a new node as well, since we check `peers.selfExcludedAndSelfHasShardAvailable()` before assuming a successful peer response (the new node will not have shards available).
