### ISSUE TITLE
valid query returns error

### ISSUE THREAD

**Issue by AmirAliSobhGol** [m3db/m3#2470]
the following query which is fine in prometheus, returns an error from m3.
`sum_over_time((hadoop_nodemanager_containersrunning > 0)[1m:])`
`"unexpected error: runtime error: integer divide by zero"`

although the following is fine:
`sum_over_time((hadoop_nodemanager_containersrunning > 0)[1m:30s])`

M3 version: 0.15.5

**Comment by arnikola** [comment]
Do you happen to have logs from the m3query host for this error? Just tried to repro with a random metric and no luck

**Comment by AmirAliSobhGol** [comment]
this is the exact log from m3coordinator:

`
{"level":"error","ts":1595269461.936335,"msg":"error executing instant query","error":"unexpected error: runtime error: integer divide by zero","errorVerbose":"runtime error: integer divide by zero\nunexpected error\ngithub.com/prometheus/prometheus/promql.(*evaluator).recover\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/promql/engine.go:806\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:679\nruntime.panicdivide\n\t/usr/local/go/src/runtime/panic.go:178\ngithub.com/prometheus/prometheus/promql.(*evaluator).eval\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/promql/engine.go:1328\ngithub.com/prometheus/prometheus/promql.(*evaluator).evalSubquery\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/promql/engine.go:1000\ngithub.com/prometheus/prometheus/promql.(*evaluator).eval\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/promql/engine.go:1071\ngithub.com/prometheus/prometheus/promql.(*evaluator).Eval\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/promql/engine.go:814\ngithub.com/prometheus/prometheus/promql.(*Engine).execEvalStmt\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/promql/engine.go:535\ngithub.com/prometheus/prometheus/promql.(*Engine).exec\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/promql/engine.go:486\ngithub.com/prometheus/prometheus/promql.(*query).Exec\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/promql/engine.go:188\ngithub.com/m3db/m3/src/query/api/v1/handler/prom.(*readInstantHandler).ServeHTTP\n\t/go/src/github.com/m3db/m3/src/query/api/v1/handler/prom/read_instant.go:119\ngithub.com/m3db/m3/src/query/util/logging.withPanicErrorResponderFunc.func1\n\t/go/src/github.com/m3db/m3/src/query/util/logging/log.go:181\ngithub.com/m3db/m3/src/query/util/logging.withResponseTimeLoggingFunc.func1\n\t/go/src/github.com/m3db/m3/src/query/util/logging/log.go:137\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/m3db/m3/src/query/api/v1/httpd.(*router).ServeHTTP\n\t/go/src/github.com/m3db/m3/src/query/api/v1/httpd/router.go:70\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212\ngithub.com/m3db/m3/src/x/net/http/cors.(*Handler).ServeHTTP\n\t/go/src/github.com/m3db/m3/src/x/net/http/cors/cors.go:102\ngithub.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5\n\t/go/pkg/mod/github.com/opentracing-contrib/go-stdlib@v0.0.0-20190519235532-cf7a6c988dc9/nethttp/server.go:140\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420081721-18254838fbe2/util/httputil/compression.go:90\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","query":"sum_over_time((hadoop_nodemanager_containersrunning > 0)[1m:])"}
`

**Comment by arnikola** [comment]
Looks like it's somehow getting a step size of 0 which is a bit weird since that should error out beforehand, at least on the m3 side; how are you calling the function, just through grafana?

Potentially we may not be setting the prom default step size on our internal engine, will have a look

**Comment by AmirAliSobhGol** [comment]
yes, just through grafana.

**Comment by arnikola** [comment]
Still unable to repro, what are your prom settings?

**Comment by AmirAliSobhGol** [comment]
what do you mean by prom settings? 
My prometheus version is 2.19 if that's what you mean.

and there is the curl:
`
curl 'http://xxx.xxx.xxx.xxx:7201/api/v1/query?query=sum_over_time((up%3E%200)%5B1m%3A%5D)'
`
maybe you could reproduce it with:
`
sum_over_time((up> 0)[1m:])
`

**Comment by arnikola** [comment]
Thanks for help, it was indeed the unset default duration as expected :+1: PR should solve it

**Comment by arnikola** [comment]
Sorry it autocloses, leaving this open until verified solved

**Comment by gibbscullen** [comment]
Closing as associated PR has been merged.
