### ISSUE TITLE
[M3DB] HTTP Json API of Query returns empty results when Query JSON Body is wrong

### ISSUE THREAD

**Issue by asafm** [m3db/m3#2473]
1. Write tagged data point, say to namespace `default`, with tag `city: new-york`
2. Read it using `9003:/query` to dbnode, having a range which includes the timestamp inserted in step 1. 
```
{
  "namespace": "default",
  "query": {
    "term": {
      "field": "city",
      "value": "new_york"
    }
  },
  "rangeStart": 0,
  "rangeEnd": 1595325840
}
```
Notice the error in the query (`term` was replaced with `value`).

Response: 200 OK, with
```
{
    "results": [],
    "exhaustive": true
}
```

Expected: 400 Bad Request with error stating `term` is required in `query.term`

**Comment by robskillington** [comment]
Thanks for filing this @asafm, we've merged a fix for returning an error on an unknown field.
