### ISSUE TITLE
m3coordinator crashing at 100% cpu

### ISSUE THREAD

**Issue by tejasbhosale009** [m3db/m3#2525]
My cluster was running fine for 1 month.
Yesterday one vpn gone down for sometime . After it came up suddenly cpu reached on coordinaotr to 100% and process crashed .
i see coordinator logs error as "error":"datapoint for aggregation too far in past
I agree that i set bufferpastduration to 10m so it given that error.

but after m3coordinator crashed the data for host which are sending to coordinator locally that also gone missing i mean i can see data when timestamp is last 5 min - 1 hr in grafana
but if i select last 6 hrs data then whole data gets missing in grafana 

How this happened any idea ? and how we can prevent this from future ..

**Comment by gibbscullen** [comment]
We are looking into this.

**Comment by robskillington** [comment]
Hey @tejasbhosale009 this is likely due to log spam since you are sending lots of sample in the past after being down for so long.

Your best bet would be if you have a huge back log like you mention to clear that backlog before bringing back the link.
