### ISSUE TITLE
m3query re2 flags support

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#2534]
I'm noticing a query discrepancy between m3query and prometheus when trying to use the `case-insensitive` flag as specified in https://github.com/google/re2/wiki/Syntax

I have a timeseries with the labels `up{endpoint="7979",instance="x.x.x.x:7979",job="kube-metrics-adapter",pod="kube-metrics-adapter-66c748c554-f6xk5",service="kube-metrics-adapter"}` which is written to M3 from a kubernetes cluster.

The query `up{service=~"(?i:(KUBE-METRICS-ADAPTER))"}` works to select when using the in-cluster prometheus, but returns nothing when I query in m3. I tried through both the remote read interface, and via the /api/v1/query path.

I've tested this behavior on m3query 0.14.1 and 0.15.8, and the dbnodes are 0.15.6

**Comment by BertHartm** [comment]
Looks like there's an open bug with fix in Vellum: https://github.com/couchbase/vellum/issues/30

**Comment by mmedvede** [comment]
Created the PR against m3dbx https://github.com/m3dbx/vellum/pull/1
