### ISSUE TITLE
/api/v1/namespace returns details from default_env instead of other environments in etcd

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#2708]
Description:
We have multiple m3db clusters sharing an etcd using different "environments" to do so.
In upgrading m3query from 0.14.1 to 0.15.13 (was able to reproduce in 15.15) we noticed that it refused to talk to our non-default environment (we call lts_env) to return data. changing the `cacheDir` to one that was writable inside the container (/var/lib/m3kv -> /tmp/m3kv) fixed our ability to query, but /api/v1/namespace is still returning the wrong namespace information.

also: noticed this in the logs which seems odd `{"level":"info","ts":1602177589.812735,"msg":"successfully created new cache dir","path":"/tmp/m3kv","mode":0}`

## General Issues

General issues are any non-performance related issues (data integrity, ease of use, error messages, configuration, documentation, etc).

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)

- m3query / m3coordinator

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).

- relevant portion seems to be that `clusters[0].client.config.service.env` is set to `lts_env` instead of `default_env`

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?

- running the m3query binary via docker in k8s

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.

happens every time I hit /api/v1/namespace

--- relevant logs below ---
```
2020/10/08 17:19:49 Go Runtime version: go1.13.15
2020/10/08 17:19:49 Build Version:      v0.15.15
2020/10/08 17:19:49 Build Revision:     ef83ec4ef
2020/10/08 17:19:49 Build Branch:       HEAD
2020/10/08 17:19:49 Build Date:         2020-09-21-02:25:19
2020/10/08 17:19:49 Build TimeUnix:     1600655119
{"level":"warn","ts":1602177589.6786585,"msg":"using deprecated configuration field","field":"DeprecatedMaxComputedDatapoints"}
{"level":"warn","ts":1602177589.6786978,"msg":"using deprecated configuration field","field":"DeprecatedQueryConversion"}
{"level":"warn","ts":1602177589.6787052,"msg":"using deprecated configuration field","field":"DeprecatedCache"}
{"level":"info","ts":1602177589.6792135,"msg":"initializing Jaeger tracer"}
{"level":"info","ts":1602177589.812735,"msg":"successfully created new cache dir","path":"/tmp/m3kv","mode":0}
{"level":"warn","ts":1602177589.8128014,"msg":"could not load cache from file","file":"/tmp/m3kv/_kv_lts_env_m3db_embedded.json","error":"error opening cache file /tmp/m3kv/_kv_lts_env_m3db_embedded.json: open /tmp/m3kv/_kv_lts_env_m3db_embedded.json: permission denied"}
{"level":"info","ts":1602177589.8781471,"msg":"waiting for dynamic topology initialization, if this takes a long time, make sure that a topology/placement is configured"}
{"level":"info","ts":1602177589.8781822,"msg":"adding a watch","service":"m3db","env":"lts_env","zone":"embedded","includeUnhealthy":true}
{"level":"info","ts":1602177589.8783314,"msg":"successfully created new cache dir","path":"/tmp/m3kv","mode":0}
{"level":"warn","ts":1602177589.878415,"msg":"could not load cache from file","file":"/tmp/m3kv/m3db_embedded.json","error":"error opening cache file /tmp/m3kv/m3db_embedded.json: open /tmp/m3kv/m3db_embedded.json: permission denied"}
{"level":"info","ts":1602177589.983336,"msg":"resolved cluster namespace","namespace":"90d"}
{"level":"info","ts":1602177589.9835289,"msg":"rpc serve enabled"}
{"level":"info","ts":1602177589.9835448,"msg":"creating gRPC server"}
{"level":"info","ts":1602177589.9835863,"msg":"gRPC server reflection configured","enabled":false}
{"level":"info","ts":1602177589.995831,"msg":"","level":"debug","component":"prometheus_engine","msg":"lookback delta is zero, setting to default value","value":300}
{"level":"info","ts":1602177590.0056307,"msg":"no m3msg server configured"}
{"level":"info","ts":1602177590.005671,"msg":"registered new interrupt handler"}
{"level":"info","ts":1602177590.0058355,"msg":"starting API server","address":"[::]:7201"}
{"level":"info","ts":1602177590.0712116,"msg":"initial topology / placement value received"}
{"level":"warn","ts":1602177590.0782957,"msg":"error creating cache file","file":"/tmp/m3kv/m3db_embedded.json","error":"open /tmp/m3kv/m3db_embedded.json: permission denied"}
{"level":"warn","ts":1602177590.0783796,"msg":"failed to write cache to file","error":"invalid cache file: /tmp/m3kv/m3db_embedded.json"}
{"level":"info","ts":1602177590.5190547,"msg":"successfully updated topology","numHosts":3}
```

**Comment by ryanhall07** [comment]
> happens every time I hit /api/v1/namespace

@BertHartm can you provide the command you running

**Comment by BertHartm** [comment]
> > happens every time I hit /api/v1/namespace
> 
> @BertHartm can you provide the command you running

I'm hitting http://ip:7201/api/v1/namespace in the browser

**Comment by ryanhall07** [comment]
do you need to set the appropriate `Cluster-Environment-Name` header?

https://m3db.github.io/m3/operational_guide/namespace_configuration/

**Comment by BertHartm** [comment]
ah, that would make sense.

I don't normally hit that endpoint in an automated fashion, usually only when debugging, so setting the header is non-trivial.

is there a way to set the default via config file? or at least pass as a get parameter so debugging is more practical?

**Comment by BertHartm** [comment]
This appears to no longer be an issue on v1.0, so I'll close.
