### ISSUE TITLE
lookbackDuration ignored for prometheus query engine

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#2710]
when running the m3query dockerfile, the config passed in has: `lookbackDuration: 60m` but in the logs it notes `{"level":"info","ts":1602194364.4528055,"msg":"","level":"debug","component":"prometheus_engine","msg":"lookback delta is zero, setting to default value","value":300}`

This config works as expected in v0.14.1, but seems to be broken in v0.15.15

**Comment by gibbscullen** [comment]
Closing for now; can re-open if still an issue.

**Comment by BertHartm** [comment]
Hi @gibbscullen , I don't seem to have rights to re-open, but @dhyaneshpoojary recently re-confirmed that this is still an issue in v1.0

**Comment by dhyaneshpoojary** [comment]
The issue still exist. Can you please re-open the issue?

**Comment by dhyaneshpoojary** [comment]
@gibbscullen
We have been waiting for this issue to be resolved for a long time.  Our production users are impacted.
Is there a ETA for the issue to be resolved.

**Comment by gibbscullen** [comment]
@dhyaneshpoojary taking this to the team to investigate... will follow up shortly.

**Comment by wesleyk** [comment]
Hi @dhyaneshpoojary, can you share your m3query config file?

**Comment by wesleyk** [comment]
So looks like this issue was resolved with the following PR, which wasn't included in the 1.0 release: https://github.com/m3db/m3/pull/2913

We should be releasing 1.1.0 in the next couple weeks.

**Comment by wesleyk** [comment]
here's the 1.1.0 release: https://github.com/m3db/m3/releases/tag/v1.1.0

**Comment by gibbscullen** [comment]
Closing as 1.1.0 release resolves this issue.
