### ISSUE TITLE
network bandwidth so high

### ISSUE THREAD

**Issue by wedooo** [m3db/m3#2726]
![image](https://user-images.githubusercontent.com/18000018/95838917-f1430200-0d74-11eb-87c9-4ccba7f123a0.png)

**Comment by gibbscullen** [comment]
Hi @wedooo -- do you mind providing a bit more context on the problem you're seeing?

**Comment by fingon** [comment]
Compression between m3coordinator and m3dbnode is what fixes this. Not particularly new, see e.g. https://github.com/m3db/m3/issues/949

**Comment by gibbscullen** [comment]
Closing for now, feel free to re-open if still an issue.
