### ISSUE TITLE
Aggregator follower flush manager should check shard cutover time when determining CanLead()

### ISSUE THREAD

**Issue by abliqo** [m3db/m3#2824]
# Aggregator follower flush manager should check shard cutover time when determining CanLead()

Currently, when aggregator follower flush manager determines whether it [CanLead()](https://github.com/m3db/m3/blob/master/src/aggregator/aggregator/follower_flush_mgr.go#L229), it checks the shards it owns and compares the last flush times of each resolution to the time when the node started (`openedAt`).

The `CanLead()` calls `mgr.electionManager.IsCampaigning()` to check for cutover/cutoff shards. In addition to that, it should probably use `max(shard.CutoverNanos(), openedAt.UnixNanos())` as the time of comparison with last flush times instead of using `openedAt`.

The possible case of concern is when shards are moved, their Cutover time is most likely going to be much more recent than the `openedAt` time of the node that started owning them and, in case of failure, could mistakenly promote the follower to a leader role with a data loss.

**Comment by gibbscullen** [comment]
@abliqo -- have you been able to test / confirm this?

**Comment by gibbscullen** [comment]
Closing for now, but open to a contribution here.
