### ISSUE TITLE
CommitLog acks back though batch was not written

### ISSUE THREAD

**Issue by asafm** [m3db/m3#2936]
I was reading through `commit_log.go` to understand a bit better how the Commit Log works. I'm not sure, but I think I found a bug in the `write()` method of `commitLog` struct:

```
		// For writes requiring acks add to pending acks
		if write.eventType == writeEventType && write.callbackFn != nil {
			l.writerState.primary.pendingFlushFns = append(
				l.writerState.primary.pendingFlushFns, write.callbackFn)
		}
```

For a given Write read from the channel (queue), if it has a callbackFn  (only if `StrategyWriteWait` was configured), it adds it to a list of pending flush function to call when flush was done (bytes written to file).
Later on, for every record in the batch, the following is called:
```
			err := l.writerState.primary.writer.Write(write.Series,
				write.Datapoint, write.Unit, write.Annotation)
```
Which writes to the `writer`, in which it checks if it should flush _before_ writing the record to the buffer. 
```
	// Avoid writing across the checksum boundary if we can avoid it
	if w.buffer.Buffered() > 0 && totalLen > w.buffer.Available() {
		if err := w.buffer.Flush(); err != nil {
			return err
		}
		return w.write(data)
```

`w.buffer.Flush()` eventually runs all functions added to `l.writerState.primary.pendingFlushFns` which in turn releases the `wg` which allows to return an ack. 

The problem is that this means a record is acked before it was actually written to the buffer, in case the buffer was full when it was about time to write the record to it.

A second problem is that the pending flush function is defined per per batch (multiple records in Write), so it can be that if a batch as 5 records, you insert the 1st and 2nd record, then on the 3rd buffer is full, thus buffer is written to disk, and then the pending flush function is called, but the 3rd to 5th record of that write have not been written to disk yet meaning we acked the Write but only written half of it to the disk.

**Comment by gibbscullen** [comment]
@asafm - Following up on this: this is possible -- the ack function may get called slightly earlier than expected for a time series that falls on the edge of a batch of writes to the Commit Log.

Closing for now, but would definitely welcome any contributions here.

**Comment by asafm** [comment]
From my perspective, it's not about slightly earlier - it's about correctness in case of failures. We ack back a record although data wasn't written to the disk, so it can easily be lost in case of machine lost. It breaks the guarantee of the Write Wait strategy.

I would love to contribute, so it seems reasonable to keep this issue open, as this bug is a indeed a bug, and needs fixing - @gibbscullen
