### ISSUE TITLE
 panic: runtime error: index out of range [41] with length 8

### ISSUE THREAD

**Issue by qiangmzsx** [m3db/m3#2939]
# m3db version
v0.15.16

# log
panic: runtime error: index out of range [41] with length 8

goroutine 14947 [running]:
github.com/m3db/m3/src/m3ninx/index/segment/builder.(*indexWorkers).indexJob(...)
        /go/src/github.com/m3db/m3/src/m3ninx/index/segment/builder/builder.go:150
github.com/m3db/m3/src/m3ninx/index/segment/builder.(*builder).flushShardedIndexJobWithLock(0xc135670280, 0x29, 0xc13789ac40, 0xc0daad62a0)
        /go/src/github.com/m3db/m3/src/m3ninx/index/segment/builder/builder.go:473 +0x266
github.com/m3db/m3/src/m3ninx/index/segment/builder.(*builder).insertBatchWithLock(0xc135670280, 0xc16f282000, 0x1, 0x1755, 0x1, 0x0)
        /go/src/github.com/m3db/m3/src/m3ninx/index/segment/builder/builder.go:420 +0x145
github.com/m3db/m3/src/m3ninx/index/segment/builder.(*builder).InsertBatch(0xc135670280, 0xc16f282000, 0x1, 0x1755, 0xc00e7d8c01, 0x0, 0x0)
        /go/src/github.com/m3db/m3/src/m3ninx/index/segment/builder/builder.go:345 +0xd0
github.com/m3db/m3/src/dbnode/storage/index.(*mutableSegments).WriteBatch(0xc02eb87400, 0xc00002ca50, 0x0, 0x0)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index/mutable_segments.go:175 +0x16d
github.com/m3db/m3/src/dbnode/storage/index.(*block).WriteBatch(0xc09d953080, 0xc00002ca50, 0xed74d38d0, 0x31011a0, 0x221f9e0, 0xc09d953080)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index/block.go:282 +0x12a
github.com/m3db/m3/src/dbnode/storage.(*nsIndex).writeBatchForBlockStart(0xc02dac6c00, 0x0, 0xed74d38d0, 0x31011a0, 0xc00002ca50)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:793 +0x10d
github.com/m3db/m3/src/dbnode/storage/index.(*WriteBatch).ForEachUnmarkedBatchByBlockStart(0xc00002ca50, 0xc02fb17dc0)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index/types.go:612 +0x528
github.com/m3db/m3/src/dbnode/storage.(*nsIndex).writeBatches(0xc02dac6c00, 0xc00002ca50)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index.go:755 +0x409
github.com/m3db/m3/src/dbnode/storage.(*nsIndexInsertQueue).insertLoop(0xc02ca96d80)
        /go/src/github.com/m3db/m3/src/dbnode/storage/index_insert_queue.go:162 +0x271
created by github.com/m3db/m3/src/dbnode/storage.(*nsIndexInsertQueue).Start
        /go/src/github.com/m3db/m3/src/dbnode/storage/index_insert_queue.go:244 +0xc2

# OS
centos 7.5 KVM
 8c16g

# namespace
```
{
  "name": "my_m3db",
  "options": {
    "bootstrapEnabled": true,
                "flushEnabled": true,
                "writesToCommitLog": true,
                "cleanupEnabled": true,
                "repairEnabled": false,
    "retentionOptions": {
                    "retentionPeriodNanos": "604800000000000",
                    "blockSizeNanos": "1800000000000",
                    "bufferFutureNanos": "30000000000",
                    "bufferPastNanos": "30000000000",
                    "blockDataExpiry": true,
                    "blockDataExpiryAfterNotAccessPeriodNanos": "150000000000",
                    "futureRetentionPeriodNanos": "0"
                },
    "snapshotEnabled": true,
    "indexOptions": {
      "enabled": true,
    "blockSizeNanos": "1800000000000"
    },
    "runtimeOptions": {
      "flushIndexingPerCPUConcurrency": 60,
      "writeIndexingPerCPUConcurrency": 60
    }
  }
}
```

**Comment by gibbscullen** [comment]
@qiangmzsx looking into this...

**Comment by arnikola** [comment]
Does this reproduce constantly? When did you see this error, was the node bootstrapped?

**Comment by qiangmzsx** [comment]
If you set the flushIndexingPerCPUConcurrency and writeIndexingPerCPUConcurrency to 1, it does not appear again.
```
{
  "name": "my_m3db",
  "options": {
    "bootstrapEnabled": true,
                "flushEnabled": true,
                "writesToCommitLog": true,
                "cleanupEnabled": true,
                "repairEnabled": false,
    "retentionOptions": {
                    "retentionPeriodNanos": "604800000000000",
                    "blockSizeNanos": "1800000000000",
                    "bufferFutureNanos": "30000000000",
                    "bufferPastNanos": "30000000000",
                    "blockDataExpiry": true,
                    "blockDataExpiryAfterNotAccessPeriodNanos": "150000000000",
                    "futureRetentionPeriodNanos": "0"
                },
    "snapshotEnabled": true,
    "indexOptions": {
      "enabled": true,
    "blockSizeNanos": "1800000000000"
    },
    "runtimeOptions": {
      "flushIndexingPerCPUConcurrency": 1,
      "writeIndexingPerCPUConcurrency": 1
    }
  }
}
```

**Comment by gibbscullen** [comment]
@qiangmzsx -- closing this unless you're still having an issue here? We'll look into making it more manageable when an invalid value is used for this.
