### ISSUE TITLE
Breaking changes not documented in v1.0.0 change log

### ISSUE THREAD

**Issue by AKarbas** [m3db/m3#2947]
These changes aren't documented as backward-incompatible in the v1.0.0 changelog:

- `db.fs` config key has been renamed to `df.filesystem`. (https://github.com/m3db/m3/commit/d86e3ef2bb3419ac45094257b7e9dc7aeffaf004; Not sure when support dropped.)
- `db.writeNewSeriesLimitPerSecond` has been removed. (https://github.com/m3db/m3/pull/2839/commits/89dc079c926221a882fa39739e13fee5931cab3e)

**Comment by rallen090** [comment]
Ah thank you for catching this and sorry for any troubles. We'll update the changelog to reflect these additional changes.

**Comment by wesleyk** [comment]
Updated the changelog. Thank you for the feedback!

**Comment by AKarbas** [comment]
Cheers.
