### ISSUE TITLE
Add bootstrapping status endpoint

### ISSUE THREAD

**Issue by prateek** [m3db/m3#303]
We need the ability to tell if a m3dbnode is currently bootstrapping for `dtest`. Expose that in the health endpoint if it's cheap, else expose under a new detailed status endpoint.

**Comment by schallert** [comment]
Talked with @richardartoul offline about implementing this. We need a separate endpoint for bootstrapping in addition "liveness" health to provide signal to orchestration platforms that can't parse out the bootstrap status from the `/health` JSON.

**Comment by richardartoul** [comment]
@schallert So this new endpoint should only return success if it is both healthy and bootstrapped, correct?

**Comment by schallert** [comment]
Yeah, it would need to return anything >= 400 if it's not healthy and bootstrapped. As an example [here's](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request) Kube's interpretation of readiness endpoints.

**Comment by prateek** [comment]
@richardartoul addressed in #943
