### ISSUE TITLE
Duplicate time series from different regions when cutting over

### ISSUE THREAD

**Issue by TommyCpp** [m3db/m3#3034]
## General Issues
1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)
   M3 query version 1.0
2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
   multiple m3-queries, each configured to talk to 1 namespace, but fanning out to each other. This situation could happen when we cut over remote write from one cluster to another. Ideally, users shouldn't feel any difference. But now same metric will show as two time series in prometheus.  
3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
   Prometheus remote read endpoint set to m3query 
4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.
```
1. Set m3 query to fanout to two cluster.
2. Write metric to first cluster for 10 mins
3. Stop writing for a few mins.
4. Write the same metric to second metrics.
5. Start prometheus to remote read from m3 query
6. Query the metrics we just wrote. Expected to see one time series. But see two time series.   
```

This is a follow up issue of #2184  cc @BertHartm

**Comment by gibbscullen** [comment]
@BertHartm -- following up on issue #2184 here.

We will look into this more.

**Comment by arnikola** [comment]
Hey, really sorry somehow missed this for a while, but this functionality should exist if you add the following to your query config:

```
query:
  consolidation:
    matchType: "tags"
```

Which will have series matched by tags rather than by ID.

**Comment by gibbscullen** [comment]
Closing as this has been resolved.
