### ISSUE TITLE
M3Coordinator does not overwrite the storage policy based on request headers "M3-Metrics-Type" & "M3-Storage-Policy" for Influx write API

### ISSUE THREAD

**Issue by anuprout** [m3db/m3#3144]
# Filing M3 Issues
The M3Coordinator currently does not process the requests headers **"M3-Metrics-Type" & "M3-Storage-Policy" for Influx write API "/api/v1/influxdb/write"** . As a result , it always writes with the default storage policy. This prevents from writing any Influx protocol data to a specific namespace.

The current code for Influx write API is missing the logic to overwrite the storage policy based on the above request headers.

**How to reproduce the error:**

1. Set up M3DB with one unaggregated and one aggregated namespace with certain resolution & retention. 
2. Configure coordinator with both the namespaces and set _downsample_ option _all: false_ for the aggregated namespace. 
3. Send an Influx write request with these headers. 
```
Ex - curl -i -X POST http://localhost:7201/api/v1/influxdb/write \
-d "test,tag_1=test_tag value=5 $(date "+%s" )" \
-H "M3-Storage-Policy: 10s:240h" \
-H "M3-Metrics-Type: aggregated"
```

The above data is always written to the unaggregated namespace.

**Proposed solution:**

Add the logic in the **/src/query/api/v1/handler/influxdb/write.go:ServeHTTP**  to overwrite the default storage policy based on the headers passed in the write request.
```
       opts := ingest.WriteOptions{}

	// ****  changes to overwrite the storage policy based on  request headers  *****

	if v := strings.TrimSpace(r.Header.Get(headers.MetricsTypeHeader)); v != "" {
		metricsType, err := storagemetadata.ParseMetricsType(v)
		if err != nil {
			xhttp.WriteError(w, err)
			return
		}

		opts.DownsampleOverride = true
		opts.DownsampleMappingRules = nil

		strPolicy := strings.TrimSpace(r.Header.Get(headers.MetricsStoragePolicyHeader))
		switch metricsType {
		case storagemetadata.UnaggregatedMetricsType:
			if strPolicy != "" {
				xhttp.WriteError(w, errUnaggregatedStoragePolicySet)
				return
			}
		default:
			parsed, err := policy.ParseStoragePolicy(strPolicy)
			if err != nil {
				err = fmt.Errorf("could not parse storage policy: %v", err)
				xhttp.WriteError(w, err)
				return
			}

			// Make sure this specific storage policy is used for the writes.
			opts.WriteOverride = true
			opts.WriteStoragePolicies = policy.StoragePolicies{
				parsed,
			}
		}
	}

	// ****

	iter := &ingestIterator{points: points, tagOpts: iwh.tagOpts, promRewriter: iwh.promRewriter}
	batchErr := iwh.handlerOpts.DownsamplerAndWriter().WriteBatch(r.Context(), iter, opts)
```

**Comment by gibbscullen** [comment]
@anuprout -- looking into this... also take a look at our API docs for more info (you should be able to use the headers you're wanting to for this): https://m3db.io/docs/m3coordinator/api/remote/#optional.
