### ISSUE TITLE
Add instrumentation for background processing tasks

### ISSUE THREAD

**Issue by prateek** [m3db/m3#323]
Add more instrumentation for background processes (tick/flush/bootstrap/cleanup/...), i.e. 
(1) Add logging per namespace (info level), 
(2) Add metrics per namespace,
(3) Add logging per shard (probably debug level, with ability to turn up), 
(4) Add write/read numbers per shard - useful to gauge load distribution

While we're here, also:
(4) Migrate to using Zap for logging
(5) Use lumberjack to specify output directory for logs, rotation policy
(6) Document dynamic log level changing per namespace/shard via curl

**Comment by richardartoul** [comment]
Would be nice to have am always written to debug file (with short retention) once we set this up
