### ISSUE TITLE
m3db defaults streamXConcurrency options to 0 if a subset is specified

### ISSUE THREAD

**Issue by nicklan** [m3db/m3#3286]
Running `m3db v1.1.0`

We had a config with:
```
"db":
  "bootstrap":
    "peers":
      "streamPersistShardConcurrency": 4
      "streamShardConcurrency": 4`
```

but no `streamPersistShardFlushConcurrency`. This meant that it defaulted to 0, and after doing the first stage of bootstrapping shards, that is until getting 4 messages of the form: 
```
{"level":"info","ts":X,"msg":"peer bootstrapped shard","bootstrapper":"peers","shard":X,"numSeries":X,"blockStart":X}
```

m3db would just go idle and make no further progress.

Setting `streamPersistShardFlushConcurrency` to 4 fixes things.

**Comment by gibbscullen** [comment]
@nicklan -- we will be implementing this change, and will follow back up on this issue shortly.
