### ISSUE TITLE
Migrate M3Aggregator to simple (non-staged) placement in etcd

### ISSUE THREAD

**Issue by abliqo** [m3db/m3#3287]
Currently, the M3Aggregator placement is stored as "staged" placement in etcd using protobuf type `*placementpb.PlacementSnapshots` as a remnant of the concept of "staged" placement that was deprecated in https://github.com/m3db/m3/pull/3254 and https://github.com/m3db/m3/pull/3274, so that only single snapshot is actually stored. The `PlacementsWatcher` was introduced as part of that simplification to abstract clients from that detail. 

There are still some cleanups remaining to do:

1. Migrate M3Aggregator to use protobuf type `*placementpb.Placement` to store placement in etcd in a manner that doesn't break M3Aggregator clients and M3Aggregator itself. There are two approaches to do that: simple and complex (and maybe more).

Simple approach:
- change placement watcher to try to unmarshal `*placementpb.Placement` (scalar type), if fails - try the legacy type
- upgrade all deployed clients and M3Aggregator nodes 
- modify placement management code to store placement using scalar type, and get rid of `stagedPlacementHelper`

Complex approach:
- change code that manages placement to store both types of placement protobufs in different well-known etcd keys within a single transaction
- deploy that code and make at least one placement change
- change this watcher code to read the non-staged placement from respective etcd key
- upgrade all deployed clients and M3Aggregator nodes
- modify placement management code to stop storing staged placement

2. Reconcile `placement.Watch` and `placement.Watcher` into one placement watcher that notifies subscribers of placement changes, just like `placement.PlacementsWatcher` already does it.

**Comment by gibbscullen** [comment]
@abliqo -- let's have a discussion if we should have these longer term issues here or in github.com/m3db/proposal.
