### ISSUE TITLE
documentation missing about etcd

### ISSUE THREAD

**Issue by lironrisk** [m3db/m3#3356]
Hi,

I've noticed that the official documentation doesn't mention what exactly are the components of m3 that uses etcd. There is also no graph that shows it.
Diving into the code I saw that all of the m3 components are using it.
Am I right? Is it true to say that all of the m3 components (m3 coordinator, m3db & m3 aggregator) relies on etcd as source of truth in order to manage the m3db cluster?

Thanks in advance!

**Comment by gibbscullen** [comment]
Hi @lironrisk -- yes, that is correct - etcd stores the metadata used by each of the components. 

Also, @ChrisChinchilla and I will make sure to update / add this to the M3 docs - thanks for raising this issue!

**Comment by lironrisk** [comment]
Thank you!

**Comment by ChrisChinchilla** [comment]
etcd as a dependency is mentioned in a few places, but I will note to add a bit more detail at some point.

**Comment by lironrisk** [comment]
Im not sure if I should write it in here or open a new issue - 
but its also unclear how M3 Qurey queries blocks that hasn't been flushed to the disk yet.
i.e -
if we have a block size configured to 2 hours - metrics will reside in-memory and be flushed to the disk only when the block is full. lets say i want metrics from the last hour or the last 5 hours - will the M3 Query query solely m3db (and then recieve data from both disk and memory) or will it query other components in order to get recent data - such as the M3 Coordinstor or Promethous itself even?

**Comment by gibbscullen** [comment]
M3 Query will read / query metrics directly from M3DB in most cases -- see the attached graph: 
![image](https://user-images.githubusercontent.com/59837500/111500356-4adf9c00-871a-11eb-8683-f457afc35d08.png)

**Comment by gibbscullen** [comment]
So in this example, query requests are coming in from Grafana to the M3 Query tier, which will then read metrics from the M3DB nodes (using quorum read) to fulfill the query requests.

**Comment by lironrisk** [comment]
thank you @gibbscullen , but what about recent metrics that hasn't been flashed to the disk yet ?

**Comment by gibbscullen** [comment]
Resolving as questions were addressed offline:
