### ISSUE TITLE
helm chart for M3

### ISSUE THREAD

**Issue by lironrisk** [m3db/m3#3383]
Hi,

I know that there is a helm chart for the M3DB operator, but I wonder if there is a helm chart that also installs the other components of m3 - m3 query, m3 coordinator and m3 aggregator.
I also wondered if there is a tutorial on how to install m3 coordinator as a sidecar to Prometheus on k8s (I saw this tutorial - https://m3db.io/docs/integrations/prometheus/#m3-coordinator-configuration but it doesn't really explain how to install it next to Prometheus on k8s as a sidecar container in its sts).

Thanks!

**Comment by gibbscullen** [comment]
@lironrisk -- working on this...

**Comment by lironrisk** [comment]
@gibbscullen Thank you

**Comment by gibbscullen** [comment]
Hi @lironrisk following up here... we have added this to our backlog.. but in the meantime here is a doc that may help: https://m3db.io/docs/cluster/kubernetes_cluster/. I would also suggest posing this request / question in the M3 slack channel so get further feedback from the community.
