### ISSUE TITLE
"literal too long" throws 5xx instead of 4xx

### ISSUE THREAD

**Issue by BertHartm** [m3db/m3#3410]
# Filing M3 Issues

## General Issues

It seems like when "literal too long" is thrown for data, it's returned as a 5xx error causing prometheus to continue to try to send the same data over and over again. It seems like that should be a 4xx error instead since the data is never acceptable.

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)

m3db v0.15.17_hotfix_2 (coordinator is v0.15.17)

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).

single namespace, nothing too weird

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?

prometheus remote writes

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.

Not sure. Have only seen it once, but it kept happening across multiple coordinators and dbnodes until the prometheus was restarted.

**Comment by gibbscullen** [comment]
Hi @BertHartm -- thanks for raising this issue! We have added it to our backlog.

**Comment by BertHartm** [comment]
just an update that we did confirm this behavior on v1.1.0 (both dbnode and coordinator) as well
