### ISSUE TITLE
Avoid redundant creating pools during Options construction 

### ISSUE THREAD

**Issue by prateek** [m3db/m3#343]
In the production code path, we call `storage.NewOptions()`, which constructs all underlying pools. And then overwrite them to the pools specified in the configuration. We can save a lot of allocs by avoiding this redundant creation. One possible way to do this is to take a create ctor which doesn't initialise pool values. 

We should audit the code-base to see where else this applies – pretty much all `Options` which have pools specified need to be considered.

**Comment by richardartoul** [comment]
I ran into this issue as well. Another possible solution is for the Options to have an Init() method, but that comes with its own set of issues
