### ISSUE TITLE
Quickstart doc runs into: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by svolpe43** [m3db/m3#3437]
## General Issues

General issues are any non-performance related issues (data integrity, ease of use, error messages, configuration, documentation, etc).

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)

M3DB

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).

The configuration is exactly how it is described [here](https://m3db.io/docs/quickstart/docker/).

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?

I am following the documentation [here](https://m3db.io/docs/quickstart/docker/). It is a single node setup with Prometheus and a node_exporter exporting data.

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.

Follow the exact documentation found [here](https://m3db.io/docs/quickstart/docker/)

I started by running the docker run command in the documentation which launched quay.io/m3db/m3dbnode:v1.0.0. It seemed to run fine and I was able to "ready" the namespace. After a few seconds of idle time I started getting this error. These errors continued as I started Prometheus and the node_exporter then eventually crashed.

```
{"level":"error","ts":1619116892.9956217,"msg":"error when flushing data","violation":"invariant_violated","time":1619116890.5512135,"error":"namespace default failed to snapshot data for blockStart 2021-04-22 18:30:00 +0000 UTC: shard 0 failed to snapshot: open /var/lib/m3db/snapshots/default/0/fileset-1619116200000000000-11-info.db: input/output error\nshard 1 failed to snapshot: open /var/lib/m3db/snapshots/default/1/fileset-1619116200000000000-11-info.db: input/output error\nshard 2 failed to snapshot: open /var/lib/m3db/snapshots/default/2/fileset-1619116200000000000-11-index.db: input/output error\nshard 3 failed to snapshot: open /var/lib/m3db/snapshots/default/3/fileset-1619116200000000000-11-digest.db: input/output error\nshard 4 failed to snapshot:
```

After I removed the container. I also removed the m3db_data folder in order to start over completely. After creating and starting a new container, I received the following error and have not been able to continue even on a fresh restart with brand new container.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12e8a4b]

goroutine 8555 [running]:
github.com/m3db/m3/src/query/storage/m3.(*m3storage).writeSingle(0xc06a70e4e0, 0x22f1ae0, 0xc068f9be60, 0xc0669cd680, 0x1ab3f000, 0xed813ba5e, 0x32a1140, 0x7ff8000000000001, 0x230a7e0, 0xc06a914c20, ...)
	/go/src/github.com/m3db/m3/src/query/storage/m3/storage.go:720 +0x11b
github.com/m3db/m3/src/query/storage/m3.(*m3storage).Write(0xc06a70e4e0, 0x22f1ae0, 0xc068f9be60, 0xc0669cd680, 0x22ceee0, 0xc0669cd680)
	/go/src/github.com/m3db/m3/src/query/storage/m3/storage.go:635 +0x7b8
github.com/m3db/m3/src/query/storage/fanout.(*fanoutStorage).Write(0xc0674d5900, 0x22f1ae0, 0xc068f9be60, 0xc0669cd680, 0x7, 0x0)
	/go/src/github.com/m3db/m3/src/query/storage/fanout/storage.go:422 +0x2f4
github.com/m3db/m3/src/cmd/services/m3coordinator/ingest.(*downsamplerAndWriter).WriteBatch.func2()
	/go/src/github.com/m3db/m3/src/cmd/services/m3coordinator/ingest/write.go:416 +0x252
github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker.func1(0xc06a920150, 0x0, 0x152ca78d152ca78d, 0xc067863740, 0x1e4f801)
	/go/src/github.com/m3db/m3/src/x/sync/pooled_worker_pool.go:177 +0x18c
created by github.com/m3db/m3/src/x/sync.(*pooledWorkerPool).spawnWorker
	/go/src/github.com/m3db/m3/src/x/sync/pooled_worker_pool.go:156 +0x66
```

Any help would be appreciated. I would like to get a very simple example spun up so I can see if I want to move forward with this project. At least I can identify a potential nil pointer exception.

I also noticed this in the logs. Might help.

```
{"level":"warn","ts":1619132128.763323,"msg":"could not load cache from file","file":"/var/lib/m3kv/_kv_default_env_m3db_embedded.json","error":"error opening cache file /var/lib/m3kv/_kv_default_env_m3db_embedded.json: open /var/lib/m3kv/_kv_default_env_m3db_embedded.json: no such file or directory"}
```

PS.
The docs also mention that you need to [create a namespace](https://m3db.io/docs/quickstart/docker/#create-a-placement-and-namespace). I don't think that is true anymore. Looks like the docker container came with a default namespace that was already in a ready state. I got an error when creating a namespace that it already exists.

**Comment by gibbscullen** [comment]
@svolpe43 Confirming you're using the currently version of the docs (v 1.1)? If so, see a similar issue here for reference: https://github.com/m3db/m3/issues/2983. Let me know if still have this issue.

**Comment by ChrisChinchilla** [comment]
@svolpe43 I just ran through the steps and didn't have any issues, what OS are you using?
