### ISSUE TITLE
How to specify a namespace write

### ISSUE THREAD

**Issue by wuqingzhi128** [m3db/m3#3439]
Hello, I would like to ask a question, that is, how to specify the namespace to write data. I see that the document lacks this score, and the document does not have the corresponding relationship with the namespace after I write a piece of data.

**Comment by gibbscullen** [comment]
@wuqingzhi128 The following doc should help here: https://m3db.io/docs/reference/m3coordinator/api/remote/#optional

But in general... 
- If looking to downsample into a namespace: use aggregator / setup mapping rules
- If looking to direct specific writes to a namespace: use headers
M3-Storage-Policy: 1m:720h (replace with storage policy)
M3-Metrics-Type: aggregated
