### ISSUE TITLE
Duplicate time series when using m3 query fanout

### ISSUE THREAD

**Issue by TommyCpp** [m3db/m3#3456]
General issues are any non-performance related issues (data integrity, ease of use, error messages, configuration, documentation, etc).

Please provide the following information along with a description of the issue that you're experiencing:

1. What service is experiencing the issue? 
M3 query

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration
See #3411.

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
We setup fanout between different m3 query and write same time series with same tags into different m3db. Expect to see the m3 deduplicate those datapoint into same time series but it returned as different time series. 

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions. 
See #3411

This issue has been discussed in #3034 #2184. However, even with consolidation set to `tags`. The problem is still unresolved. 

Looked at #2370. I think the tag based consolidation is valid in [`m3Storage`](https://github.com/m3db/m3/blob/master/src/query/storage/m3/storage.go). However, in [`fanoutStorage`](https://github.com/m3db/m3/blob/master/src/query/storage/fanout/storage.go), [the results from different stores are not deduplicated](https://github.com/m3db/m3/blob/master/src/query/storage/fanout/storage.go#L129). 

I want to confirm if it's by design or it is a potential bug. If it's a bug, a quick fix would be deduplicate the time series in `fanoutStorage`. But I would image it will impact performance as we need to re-index tags. In this case I may need some guidance where would be the best place to do the deduplication and I am happy to put together a PR to fix it.

cc: @BertHartm

**Comment by gibbscullen** [comment]
@TommyCpp Working on this here https://github.com/m3db/m3/pull/3482.
