### ISSUE TITLE
Make `persist/fs` filesystem interactions testable

### ISSUE THREAD

**Issue by prateek** [m3db/m3#348]
We're currently passing `*os.File` around, which is a struct and not mockable. E.g. case where we needed this ability: #347. Should migrate the codebase to use something like https://talks.golang.org/2012/10things.slide#8 which allows us to mock fs interactions.

**Comment by robskillington** [comment]
Can do, right now we just treat places needing a file handle as integration tests by actually using the file system for those tests.

I'm all for mocking but it seems it's as easy/difficult to just write to file system the data wishing to test reading in, etc with the benefit of testing any strange edge cases with the file system itself (e.g. Passing invalid flags to FS APIs, etc).  

Thoughts?

**Comment by prateek** [comment]
That'll cover most of the usual situations, but I don't see how we can emulate all the failure modes without mocking the interface. E.g. I don't see how we can write a test for #347 without guaranteeing `file.Close()` returns an error.

**Comment by robskillington** [comment]
For sure, for those cases yes we should use a mock.
