### ISSUE TITLE
Add dtest to test dynamic namespace updates

### ISSUE THREAD

**Issue by prateek** [m3db/m3#355]
- Add dtests to ensure dynamic namespaces are created/removed as expected

**Comment by richardartoul** [comment]
@prateek Is this done? I know we have a test for dynamic namespace delete.

If its not done, if you could write a brief description of what needs testing I could probably tackle it since I just debugged the namespace delete test and have a sense of that part of the codebase

**Comment by prateek** [comment]
Nah it's still open. It'll be a good introduction to the m3db e2e testing framework (dtests) we use. The point is to add a test case for namespace addition/deletion to this list ~ https://github.com/m3db/m3db/tree/master/tools/dtest/tests. It's similar to the integration test you fixed, but using a distributed test harness.
