### ISSUE TITLE
perCPU: <float> wont accept values described in documentation

### ISSUE THREAD

**Issue by EdvinasBoguckis** [m3db/m3#3574]
1. What service is experiencing the issue? (M3Coordinator, M3DB, M3Aggregator, etc)
M3Query (but as config is shared i expect that M3Coordinator aswell)

2. What is the configuration of the service? Please include any YAML files, as well as namespace / placement configuration (with any sensitive information anonymized if necessary).
Not needed

3. How are you using the service? For example, are you performing read/writes to the service via Prometheus, or are you using a custom script?
Not needed

4. Is there a reliable way to reproduce the behavior? If so, please provide detailed instructions.

Put a perCPU: <float> parameter with a value of any except 0.0, M3Query will fail with:
unable to load config from [/etc/m3query/m3query.conf]: MultiProcess.PerCPU: greater than max
Per documentation minimal value is 0.0 and maximum is 1.0, but as discussed in slack yaml is configured to not accept anything but 0.0
https://m3db.slack.com/archives/CKARJDKT2/p1624873995053200

**Comment by wesleyk** [comment]
Thanks, here's a fix! https://github.com/m3db/m3/pull/3616

**Comment by wesleyk** [comment]
Landed the fix, thank you!
