### ISSUE TITLE
Switch to model where metadata for unread blocks can be removed from memory

### ISSUE THREAD

**Issue by robskillington** [m3db/m3#359]
Right now we retain block metadata in memory after we unwire the actual data from memory.  This means looking up whether series exist or don't exist is very fast but also means we use a whole lot more memory than necessary.  Since our performance currently is adversely affected by how large our heap is due to Go's GC and that we also do not want to be memory bound long term, we need to move to a model where we can look this up on demand.

This requires a significant amount of changes at the shard layer due to our current checks of existence is a simple map lookup, etc.

It is something that can drastically reduce the hardware footprint required for large datasets (100s of TBs).

**Comment by richardartoul** [comment]
This was resolved over a year ago
