### ISSUE TITLE
Website Kubernetes cluster documentation has "Ready a Namespace" step listed twice

### ISSUE THREAD

**Issue by skupjoe** [m3db/m3#3609]
The documentation [here](https://m3db.io/docs/cluster/kubernetes_cluster/#create-a-placement-and-namespace) has the [Ready a Namespace](https://m3db.io/docs/cluster/kubernetes_cluster/#ready-a-namespace) step listed twice ("Ready a Namespace" > "View Details of a Namespace" > "Ready a Namespace" > "Replication Factor" > "Shards" > ..)

The documentation source [on GitHub](https://github.com/m3db/m3/blob/master/site/content/cluster/kubernetes_cluster.md) does not include these steps twice (but some template is being used that might be resulting in this).

**Comment by gibbscullen** [comment]
Thanks, @skupjoe! Working on a fix for this..

**Comment by wesleyk** [comment]
Fix is here! https://github.com/m3db/m3/pull/3617
