### ISSUE TITLE
M3msg usage doc wanted

### ISSUE THREAD

**Issue by bakerLecter** [m3db/m3#3628]
# Filing M3 Issues

## General Issues

Hi, it's there any doc about how to use m3msg? I find it on the doc that talk about aggregator and coordinator data communicate, but there is nothing more to talk about it in the whole doc, at least I cant find any. So can you guys offer some doc about it?

**Comment by gibbscullen** [comment]
@bakerLecter have you seen this yet? https://github.com/m3db/m3/tree/master/src/msg#readme

**Comment by bakerLecter** [comment]
@gibbscullen Ops, I haven't read this. Thanks.
