### ISSUE TITLE
m3db node memory leak(v1.3)

### ISSUE THREAD

**Issue by wisre** [m3db/m3#3868]
# memory of cluster node increate slowly, like memo leak

## General Issues

m3db node memory increase slowly, i  want to know which config can slove this problem. this is the  trend, the node version is v1.3

![image](https://user-images.githubusercontent.com/15846757/138601300-b28e0327-1fad-455e-80af-2a89fb0f462a.png)

### namespace config:
    namespaces": {
    "default": {
    "bootstrapEnabled": true,
    "flushEnabled": true,
    "writesToCommitLog": true,
    "cleanupEnabled": true,
    "repairEnabled": false,
    "retentionOptions": {
    "retentionPeriodNanos": "8640000000000000",
    "blockSizeNanos": "7200000000000",
    "bufferFutureNanos": "600000000000",
    "bufferPastNanos": "600000000000",
    "blockDataExpiry": true,
    "blockDataExpiryAfterNotAccessPeriodNanos": "300000000000",
    "futureRetentionPeriodNanos": "0"
    },
    "snapshotEnabled": true,
    "indexOptions": {
        "enabled": true,
    "blockSizeNanos": "7200000000000"
    },
    "schemaOptions": null,
    "coldWritesEnabled": false,
    "runtimeOptions": null,
    "cacheBlocksOnRetrieve": false,
    "aggregationOptions": {
    "aggregations": [
    {
        "aggregated": false,
        "attributes": null
    }
    ]
    },
    "stagingState": {
        "status": "READY"
    },
    "extendedOptions": null
    }

### cache config
![image](https://user-images.githubusercontent.com/15846757/138601371-32c20a35-1d69-45b6-a2fe-0a0cc4c45b70.png)

if you need any other data, please tell me ,thanks

**Comment by wesleyk** [comment]
Thanks for reporting! We'll be cutting a release with a fix included (from https://github.com/m3db/m3/pull/3806).

**Comment by wisre** [comment]
> Thanks for reporting! We'll be cutting a release with a fix included (from #3806).

thank you @wesleyk , i will wait next release

**Comment by wesleyk** [comment]
@wisre v1.4.0 is cut now! Closing this out, please re-open if you still experience issues.

**Comment by wesleyk** [comment]
@wisre if you still observe the issue, could you ping me on the M3 slack? Would be good to get debug profiles from you from startup to when you observe memory growth.

**Comment by wisre** [comment]
@wesleyk  the issue is exists too, and i found that #3806  not merge in 1.4.0?
![image](https://user-images.githubusercontent.com/15846757/145348302-c34d1902-6455-4e1c-ba24-187e513141c2.png)
