### ISSUE TITLE
Add support for `last_over_time`

### ISSUE THREAD

**Issue by ryansammonaiven** [m3db/m3#3883]
The `<aggregation>_over_time()` function `last_over_time` ([docs link](https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time)) was added to Prometheus in v2.26.0 ([changelog link](https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2260--2021-03-31)) and is not currently supported by M3DB.

**Comment by gibbscullen** [comment]
@ryansammonaiven see note in #3884
