### ISSUE TITLE
can't fix up cluster when add a wrong placement

### ISSUE THREAD

**Issue by angelala00** [m3db/m3#4076]
Currently, if user added a node to placement, then cluster is hard to fix up. I can not do anything to fix this condition if just by m3db api.

For example,

add a broken node
curl -X POST localhost:7201/api/v1/services/m3db/placement -d '{
  "instances": [
        {
            "id": "node-4",
            "isolationGroup": "a",
            "zone": "embedded",
            "weight": 100,
            "endpoint": "x.x.x.x",
            "hostname": "broken-node",
            "port": 9000
        }
  ]
}'
than i find endpoint without port ,and wanna remove this node, everything is stuck.
{"error":"instances [node-1,node-2,node-3,node-4] do not have all shards available"}
How can i fix this?

**Comment by crazy-pizza** [comment]
same question

**Comment by angelala00** [comment]
fixed
