### ISSUE TITLE
Potential encoding improvements. 

### ISSUE THREAD

**Issue by swong15** [m3db/m3#505]
Hi there,

One of my friends at Uber pointed me at this project. It looks super cool! I was glancing through the code and noticed that the LeadingAndTrailingZeros routine manually counts the number of leading one and zero bits in a loop. In Gorilla we currently use __builtin_cl.*(https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html) and friends and it looks like in Go theres a much more sensibly named TrailingZeros64(https://golang.org/src/math/bits/bits.go?s=2824:2858#L74).

Have you guys considered using something like this?

**Comment by xichen2020** [comment]
Hey @swong15 , thanks for pointing it out!

Yes we'd definitely be happy to switch provided the builtin function is benchmarked to be faster than the counting logic (and it probably will). Looks like the new builtin function was introduced relatively recently (go 1.10) so we might to use conditional compilation flags so m3db still builds with earlier go versions.
