### ISSUE TITLE
Write and add linter to M3DB for detecting locks that are locked and then never unlocked

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#581]
I.E the linter should be able to detect simple errors like this

``` golang
func (s *someStruct) someMethod() error {
    s.Lock()
    err := s.doSomeWork()
    if err != nil {
        return err
    }
    s.Unlock()
    return nil
}
```

This will allow us to avoid defer's in hot-paths, but still be confident our code isn't buggy.

**Comment by prateek** [comment]
Did a little research on this a while back, more details here: https://github.com/m3db/build-tools/issues/14
