### ISSUE TITLE
Investigate a wrapper type that avoids actually finalizing some types when they are refs to longly lived data structures

### ISSUE THREAD

**Issue by robskillington** [m3db/m3#611]
Based on this discussion:
https://github.com/m3db/m3db/pull/607#discussion_r187116499

There are some places we'd like to return refs to existing data that should not be finalized when traditionally they would be.  One instance is return ID and Tags from series that exist in memory (should not be finalized as we return a ref to these data structures) mixed with ID and Tags that come from disk (should be finalized as we read data into a byte buffer and now no longer need that data as the request has been served).

So we'd like to find a way to return a cheap wrapper type for `ident.ID` and `ident.Tags` (or `ident.TagIterator`) that when you call `Finalize()` on them is a no-op.

**Comment by richardartoul** [comment]
Already implemented via the `NoFinalize()` method
