### ISSUE TITLE
Document tuning of vm.max_map_count in deployment guide

### ISSUE THREAD

**Issue by schallert** [m3db/m3#660]
We mmap a lot of files under some circumstances. The kernel parameter `vm.max_map_count` limits how many mmap areas a process can have open, and [defaults](https://www.kernel.org/doc/Documentation/sysctl/vm.txt) to 65536. We should document the impact of this and provide guidance for tuning, maybe in the form of a formula based on number of namespaces, block size, etc. Maybe the host can even warn on boot if the setting is not tuned correctly.

**Comment by schallert** [comment]
Can this be closed as of #714?

**Comment by richardartoul** [comment]
@prateek Can close this when #1118 lands
