### ISSUE TITLE
Cannot Build on Windows

### ISSUE THREAD

**Issue by jeromefroe** [m3db/m3#692]
Presently we cannot build m3db on Windows because we use certain constants in the [`syscall`](https://godoc.org/syscall) package which are not available on Windows. The constants are used only by the mmap code in `dbnode` and `m3x`:

```
src/dbnode/x/mmap/mmap_other.go:36:34: undefined: syscall.MAP_PRIVATE
src/dbnode/x/mmap/mmap_other.go:44:29: undefined: syscall.MAP_ANON
src/dbnode/x/mmap/mmap_other.go:44:46: undefined: syscall.MAP_PRIVATE
src/dbnode/x/mmap/mmap_other.go:57:17: undefined: syscall.PROT_READ
src/dbnode/x/mmap/mmap_other.go:60:17: undefined: syscall.PROT_WRITE
src/dbnode/x/mmap/mmap_other.go:63:12: undefined: syscall.Mmap
src/dbnode/x/mmap/mmap_other.go:78:12: undefined: syscall.Munmap
...
vendor/github.com/m3db/m3x/pool/heap.go:215:15: undefined: mmap
vendor/github.com/m3db/m3x/pool/mmap.go:26:2: const initializer syscall.PROT_READ | syscall.PROT_WRITE is not a constant
vendor/github.com/m3db/m3x/pool/mmap.go:26:24: undefined: syscall.PROT_READ
vendor/github.com/m3db/m3x/pool/mmap.go:26:44: undefined: syscall.PROT_WRITE
vendor/github.com/m3db/m3x/pool/mmap.go:27:2: const initializer syscall.MAP_ANON | syscall.MAP_PRIVATE is not a constant
vendor/github.com/m3db/m3x/pool/mmap.go:27:24: undefined: syscall.MAP_ANON
vendor/github.com/m3db/m3x/pool/mmap.go:27:43: undefined: syscall.MAP_PRIVATE
vendor/github.com/m3db/m3x/pool/mmap.go:31:9: undefined: syscall.Munmap
vendor/github.com/m3db/m3x/pool/native.go:98:15: undefined: mmap
```

**Comment by isaachier** [comment]
This doesn't surprised me. `mmap` is a POSIX API. Windows has an equivalent, but it looks like Go doesn't support it out of the box. There are some third-party libraries that support Windows.

**Comment by gedw99** [comment]
Look at boltdb to see how they support mmap on windows..also badger dB uses the same.

It should be pretty easy to support windows

**Comment by gedw99** [comment]
Would the Uber team take a PR though ? I can imagine you have no interest in windows.

**Comment by isaachier** [comment]
I think so.

**Comment by gedw99** [comment]
https://github.com/boltdb/bolt/pull/191/files

The original PR for BoltDB to make it work on Windows. 
Just adding the notes here in case someone is interested in making the changes.

**Comment by prateek** [comment]
@gedw99 I don't think we'd ever deploy M3DB on Windows internally at Uber. That said if you have a need to do so, we're definitely open to taking changes if you wanna contribute back. 

It'd be a bit involved, some of the stuff that I can think off the top of my head that would need to be changed: 
- `mmap` as identified in this ticket
- internal instrumentation for number of open fds relies on `/proc` right now
- file path handling (i'm sure there's plenty of code that relies on `/a/b/c` paths) 
- probably need to get our test suites to run on a Windows CI too

Do you have a need for Windows support?

**Comment by gedw99** [comment]
@prateek thanks for the list showing where the changes would be needed.

Right now i am not sure as i am still evaluating this lib for inclusion into our stack.  
SO maybe leave this open for now ?

**Comment by prateek** [comment]
@gedw99 sure thing. Feel free to reach out on [chat](https://gitter.im/m3db/Lobby) or the [forums](https://bitly.com/m3db-forums) if you have other questions.

**Comment by gedw99** [comment]
https://github.com/edsrzf/mmap-go

Just a very clear library with lots of docs showing mmap on windows and other OS's.
Might help... and putting here since i was working on golang mmap compiled to WASM for a problem i had.
