### ISSUE TITLE
Make coordinator/namespace handlers easier to use

### ISSUE THREAD

**Issue by prateek** [m3db/m3#693]
Currently we require users to submit all parameters when configuring namespaces, e.g. #690. We should make this easier to use where we fall back to defaults for un-specified fields.

**Comment by justinjc** [comment]
Might be difficult given the way it is set up right now, but previously, users specify durations like go `time.Duration`s, e.g. `"12h"`. I would be nice to support this as opposed to specifying nanos.

**Comment by richardartoul** [comment]
This is pretty vague and we've made our APIs a lot easier to use since
