### ISSUE TITLE
About M3DB benchmark and resource usage

### ISSUE THREAD

**Issue by linxGnu** [m3db/m3#801]
Hi m3db team, thank you so much for your hard and great work.

Currently, I am giving m3db a try. I created a benchmark code at: https://gist.github.com/linxGnu/66ab7ecf3f4e8480874734e9fe08165d

As running, I saw the result:

```
* Hardware: Macbook Pro 15-inch 2017 (MacBookPro14,3)
* CPU: 2.8 GHz Intel Core i7
* Memory: 16GB 2133MHz LPDDR3
* SSD: 256GB
* OS: High Sierra 10.13.5
```

```
  RAM (usage): ~1.3 GB
  Number of points: 131072
  Duration: 12.655(s)
  Average: 10357.277 data point/s
  Disk Usage: 127MB 
```
I wonder:
1. My benchmark code is wrong?
2. Why main memory consume a lot (because of too much buffer pool, object pool, etc)?
3. The throughput is so slow, about 50% compared to single node of InfluxDB (I also write to InfluxDB point by point, sequentially)
4. The disk usage also double/triple size compared to InfluxDB.

Thank you in advance for your help.

**Comment by richardartoul** [comment]
Hey linxGnu,

Those numbers do seem low and not in-line with our internal benchmarks (unfortunately we don't have a good reproducible set of benchmarks, but we're working on it). Could you provide us with some more information:

- The influxdb benchmark you're running
- The M3DB configuration you're using
- The size of the M3DB files on disk when the benchmark is done (specifically the data/commitlog folders)

To answer your questions in order:

1) Your benchmark code is not "wrong" but it could definitely be improved. For example, you're doing something like `ident.StringID("default")` in the inner portion of the loop. This will cause an allocation everytime, even though it never changes. You could create this value one time and then use it throughout.

2) Hard to determine without seeing your configuration. Also are you talking about the client usage or the dbnode itself? M3DB does a lot of object pooling, so its possible that the default pool values for M3DB are simply much larger than those of influxdb.

3) Some of this is probably the result of the client code you've written, but it would be good to see your M3DB configuration as well.

4) Thats very surprising. Could you tell us the size of the M3DB data / commit log directories once the benchmark is complete? My suspicious is that you're running M3DB with a block size of 2 hours or some period of time that is much longer than the benchmark. As a result, all of the persisted data remains in the commit log and M3DB doesn't get a chance to write out the data in compressed format. We're working on a new snapshotting feature that would alleviate this issue significantly, but in practice its not a big issue for production workloads as the vast majority of the data ends up in the compressed blocks and only the most recent data is in the commit log.

Also thanks for taking the time to run the benchmark!

**Comment by linxGnu** [comment]
Hi @richardartoul, please kindly find my configuration, code and data size (it's almost default): 
* m3db (standalone node) config: https://gist.github.com/linxGnu/bccbab35461265d277b75745db1a2691
* influxdb config: https://gist.github.com/linxGnu/7156ba73ad9aaa2f417a43d477e75096
* code for influxdb benchmark: https://gist.github.com/linxGnu/fdac6a08ac99858e9b8328986718f097
* Size on disk:
```
m3db: 127MB
influxdb: 41MB
```
PS: I think the allocation of `ident.StringID("default")` is small, not impact on benchmark.

**Comment by linxGnu** [comment]
Kindly ping @richardartoul 

Could you please let me know if there are updates for the issue, thank you very much.

P/S: I will try to create real cluster for m3db benchmark, and will report back asap.

**Comment by richardartoul** [comment]
@linxGnu Hey sorry didn't mean to ignore you. @r Is actually building a reproducible benchmarking suite for us so that we can have meaningful comparisons

**Comment by linxGnu** [comment]
Oh no problem, thank you for replying. I am looking forward to see the benchmarking suite 👍

**Comment by tangyong** [comment]
The same problem using https://gist.github.com/linxGnu/66ab7ecf3f4e8480874734e9fe08165d happened on our env as following:

10W data points ，duration: 27.527s  3632.735/s

I am looking forward to see the benchmarking suite too!

**Comment by kingjcy** [comment]
I want to use your benchmarking suite, but I can not find your vendor? There are Many problems in the compilation process!!

**Comment by sorinmuchi** [comment]
@linxGnu @richardartoul Any updates on this?

If anyone could please point me to a more comprehensive comparison between M3DB and InfluxDB that would be greatly appreciated!

**Comment by ieipi** [comment]
+1 for waiting for benchmark between m3db and influxdb

**Comment by mehmoodz** [comment]
For benchmarking this is added here,

https://github.com/m3dbx/promremotebench
https://github.com/m3dbx/bench_multiregion
