### ISSUE TITLE
does m3 support advanced analysis ?

### ISSUE THREAD

**Issue by djvulee** [m3db/m3#844]
I just read the document http://m3db.github.io/m3/query_engine/architecture/functions/, but find the function suppported by m3db is simple, does m3db support function like`groupBy`.

**Comment by robskillington** [comment]
Hey @djvulee - sorry for the delay.  M3QL query execution isn't implemented yet, right now the only way of querying data from M3DB is either fetching raw data or using a Prometheus instance to execute PromQL by pulling data through the Prometheus remote read endpoint.  

However, back to your original question, yes the language, similar to PromQL, supports group by.  Each aggregation function takes an optional list of tags (labels) to group by.

@nikunjgit @benraskin92 @arnikola who are developing the query engine can provide more details.

**Comment by djvulee** [comment]
Thanks for your reply! Glad to see more details and the plan for  open source version.
