### ISSUE TITLE
E | rafthttp: request cluster ID mismatch (got 35c7dcf7684ddd23 want 1c45a069f3a1d796)

### ISSUE THREAD

**Issue by tannh** [m3db/m3#856]
I have setup 3 nodes cluster 3mdb manual. Anh i get a messages log above:
E | rafthttp: request cluster ID mismatch (got 35c7dcf7684ddd23 want 1c45a069f3a1d796).

**Comment by robskillington** [comment]
Interesting, this seems similar to this etcd issue:
https://github.com/coreos/etcd/issues/8169

**Comment by richardartoul** [comment]
Closing as stale
