### ISSUE TITLE
datapoint is too far in the past

### ISSUE THREAD

**Issue by Arslanbekov** [m3db/m3#891]
Hi, I have a problem, pls help :) 

Installation arch:
![download](https://user-images.githubusercontent.com/579213/45214849-3cd87700-b2a4-11e8-9aef-6620426b71dc.png)

And many many errors in m3dbcoordinator:

```
2018-09-07T09:54:08.915Z	ERROR	Write error	
{
"rqID": "877b3e90-9860-4d7a-aa05-06e6707aa636", 
"err": "failed to meet consistency level one with 0/1 success, 1 nodes responded, errors: [error writing to host m3db_local: Error({Type:BAD_REQUEST Message:datapoint is too far in the past
}
...
```

I tried different timezone, but I do not think that they affect

**Comment by Arslanbekov** [comment]
helped restart prometheus

**Comment by prateek** [comment]
@Arslanbekov as things stand right now, each m3db namespace only accepts writes within `(now()-namespace.BufferPast, now() + namespace.BufferFuture)`. Any write outside of that time window will be dropped. The values for `BufferPast` and `BufferFuture` default to 2min (they are configurable per namespace in the event you want to modify them). 

Few things to look at the next time you run into this issue:
- Check the clock skew looks like between your kube cluster hosts and the m3db bare metal hosts. If you're not already running `ntpd` or some such, it might be worth doing so. 
- Was prom backed up? i.e. somehow emitting metrics older than 2min?

If this happens again, might be worth upping the 2min to 10min on the m3db namespace. 

ps: nice diagram!

**Comment by Arslanbekov** [comment]
@prateek thanks for your answer!
Prometheus not backed up, but it's test env, no problem restart.

I think that when you run the m3coordinator on a working prometheus, it tries to send all its metrics to the m3dbnode, so I got this error

**Comment by duanyifei1937** [comment]
I have same error in m3dbcoordinator.
I have 1300+ targets and about 80k samples/sec. try split target 500 + 800 to two prometheus, not encounter this error;
so, I think m3dbcoordinator have a  queue limit or Performance bottleneck.
