### ISSUE TITLE
Error: 405 Method Not Allowed while adding node(s)

### ISSUE THREAD

**Issue by lukmanulhakimd** [m3db/m3#893]
Hi,
I followed the exact instruction on this page: http://m3db.github.io/m3/how_to/kubernetes/. Everything works fine until "Adding nodes". The error is `curl: (22) The requested URL returned error: 405 Method Not Allowed`.

My environment is kubernetes cluster on gke v1.10.6-gke.2.

**Comment by justinjc** [comment]
Apologies for this - the documentation is out of date. To add a placement, `POST` to `localhost:7201/api/v1/placement` and _not_ `localhost:7201/api/v1/placement/add`

I'll update the docs.

**Comment by robskillington** [comment]
This was fixed with https://github.com/m3db/m3/pull/907.
