### ISSUE TITLE
Docs: /etc/security/limits.conf don't work with systemd

### ISSUE THREAD

**Issue by matejzero** [m3db/m3#959]
The [documentation](https://m3db.github.io/m3/how_to/cluster_hard_way/) on the home page says that we should set `nofile` limits in `/etc/security/limits.conf`. On systems using `systemd`, this setting wont have any effect, because `systemd` is not taking it into an account.

Quote from [ArchLinux wiki](https://wiki.archlinux.org/index.php/Limits.conf):
```
Note: /etc/security/limits.conf does not work if systemd exists. The files /etc/systemd/system.conf, /etc/systemd/user.conf, and /etc/systemd/<systemd_unit>/override.conf would control the limit. See the systemd-system.conf(5) man page for details.
```

I think it would be good to edit/add documentation for users with `systemd` to set those limits in `/etc/systemd/.conf` files or in the specific systemd service file.

**Comment by richardartoul** [comment]
@schallert Do you mind taking a look at this one when you get a chance?

**Comment by schallert** [comment]
Yeah I'll see if it makes sense to just add a base systemd service config to the repo.
