### ISSUE TITLE
M3DB should warn about low vm.max_map_count values

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#960]
M3DB makes heavy use of mmap'd regions to avoid G.C overhead. In situations with a large number of shards/blocks, the number of mmap'd regions can exceed the vm.max_map_count value preventing M3DB from mmap'ing and munmap'ing regions which can prevent it from booting, or cause it to panic/OOM.

We should add some logic to M3DB to warn about low values for this configuration, and perhaps even do some rudimentary calculations to estimate how high this value needs to be for the given configuration.

**Comment by richardartoul** [comment]
Also consider warning about ulimits and kernel process thread limits

**Comment by schallert** [comment]
Ref #660

**Comment by richardartoul** [comment]
@prateek Can close this when #1118 lands
