### ISSUE TITLE
Reduce error logging in m3coordinator

### ISSUE THREAD

**Issue by prateek** [m3db/m3#973]
When m3coordinator is having trouble writing to m3dbnode, it logs too much. 

![973-2](https://user-images.githubusercontent.com/199982/46227051-08e4f480-c32c-11e8-8de5-0b68ce9c5925.png)
![973](https://user-images.githubusercontent.com/199982/46227052-08e4f480-c32c-11e8-8610-0d0446bdfad7.png)

Reported in Gitter by @eahydra

**Comment by benraskin92** [comment]
Taking a look at this one

**Comment by arnikola** [comment]
PR up: https://github.com/m3db/m3/pull/1163

**Comment by arnikola** [comment]
This has been fixed.
